### ISSUE TITLE
Chinese voice language cannot be changed back to English

### ISSUE THREAD

**Issue by tlpbu** [Hypfer/Valetudo#1013]
## Describe the bug
During Valetudo upgrade English voice language was changed to Chinese.
As per [docs description](https://valetudo.cloud/pages/faq.html) voice language can be changes by editing `/mnt/default/roborock.conf` file.
But there is not such file on my vacuum and closest to that is `/mnt/default/device.conf` file but it is not editable.
`Error writing /mnt/default/device.conf: Read-only file system` 

### Vacuum Model
RoborockV1ValetudoRobot

### Valetudo Version
2021.07.1

## Expected behavior
Possibility to change voice language to English.

**Comment by Hypfer** [comment]
You're banned.
