### ISSUE TITLE
How do I login to my robot via SSH when I forgot the Key but still have access to the key in access control sttings?

### ISSUE THREAD

**Issue by liquidbear99** [Hypfer/Valetudo#1027]
I have valetudo successfully installed on my S5 but forgot to save the key and would like to update. Is there a way I can use the key under access control settings to login and update? How would I do that?

**Comment by charliesz** [comment]
If you have access to the valetudo gui you can use the ssh key in -> settings -> access control to login via ssh or even add another ssh key for a another device to get access with multiple ssh keys.
