### ISSUE TITLE
draw robot and charger on map

### ISSUE THREAD

**Issue by petabyteboy** [Hypfer/Valetudo#106]
How can I make Valetudo draw the robot and the charger on the map in the web interface?

**Comment by Hypfer** [comment]
It did that at some point. Guess it's missing in the new 0.2.0 Map.

@matthiasharrer ?

**Comment by petabyteboy** [comment]
I will try to add it back.

**Comment by matthiasharrer** [comment]
You can have a look at https://github.com/matthiasharrer/Valetudo/tree/add-robot-drawing?files=1

It seemed to work but the robots orientation was incorrect. Would be nice if you can figure it out:)

**Comment by petabyteboy** [comment]
But it's exactly the code that was used before..? That's weird.

**Comment by matthiasharrer** [comment]
Yup that's what confused me too.
Did you try it with your robot? Is it working for you?

**Comment by petabyteboy** [comment]
Nope, the angle is very weird.

**Comment by matthiasharrer** [comment]
Ah I think the problem is the flipping of the map. I'm not exactly sure but depending on where the map is read from the api returns a flag that indicates a flipped map. I think we have to account for that with the robots angle too.

**Comment by petabyteboy** [comment]
I mean most of the time it looks okay, but just because of how this code works it will always look a bit weird in some cases.
![foo](https://i.imgur.com/5bLfLgD.png)
![foo](https://i.imgur.com/i2oXuTC.png)
![foo](https://i.imgur.com/3tIrpI0.png)
![foo](https://i.imgur.com/XkKtuHX.png)
You can see that the first two look fine, but the last two look off somehow.
Actually it makes a lot of sense that these angles have not been adjusted for a flipped map.

**Comment by petabyteboy** [comment]
I don't understand this: The whole path should have been flipped to account for the map being flipped. So did the old code somehow flip the y axis, so it is flipped twice now? @Hypfer

**Comment by petabyteboy** [comment]
Nevermind, the way this the path is used the transform is not being applied.

**Comment by matthiasharrer** [comment]
I think the flipping is applied when the meter based path coordinates are transformed to the 1024*1024 px map coordinates. For calculating the angle I used the original path coordinates .. so they miss the flipping.

**Comment by petabyteboy** [comment]
Yes, that's how it is. 
I am having a few other problems where the charger is shown in the wrong place, is that a known issue?

**Comment by matthiasharrer** [comment]
You mean a little bit or completely off? We discussed it in #72 but I never really looked into it.

**Comment by petabyteboy** [comment]
It was completely off. I stopped the robot in the middle of a run and after that it thought it was at its charging point and it couldn't find the charger when I told it to go home. So I guess not-our-bug.

**Comment by Hypfer** [comment]
#107
