### ISSUE TITLE
vendor.dreame: Manual Control

### ISSUE THREAD

**Issue by hereticmaggot** [Hypfer/Valetudo#1065]
Hello, I see in the autogenerated changelog of 2021.08.0 release that vendor.dreame: Manual Control was added.
However, I don't see how to use it. Is there a way using the rest api?

**Comment by ingoschi** [comment]
see /swagger/#/ManualControlCapability

**Comment by hereticmaggot** [comment]
Thank you I see the commands. However applying them does not work.
The robot indeed says starting remote cleanup but never moves.

**Comment by ingoschi** [comment]
I haven't tried it myself yet.
But according to https://gist.github.com/Hypfer/fcfa39996bd7522bbe2c5f18acb1fcf4#file-valetudo_gamepad_experiments_v1-js
you first have to send 

{"action":"enable"}

 to /api/v2/robot/capabilities/ManualControlCapability
before you send a.e.

 {"action": "move",
   "movementCommand": "forward" }
 
And I guess  {"action":"disable"} when you're finished with your movements.

**Comment by hereticmaggot** [comment]
Thanks it works.
Just would be nice to have that function integrated into Valetudo UI
