### ISSUE TITLE
port to strict mode

### ISSUE THREAD

**Issue by petabyteboy** [Hypfer/Valetudo#110]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

Strict mode has many advantages. It allows for better optimization in the browser runtime, it prevents programming bugs that can be caused by the strange behaviour of `var`, and so on. It should really be considered best practise for modern Javascript applications.

**Comment by Hypfer** [comment]
Superseded by the port to es6, I think
