### ISSUE TITLE
Not cleaning the whole room anymore?

### ISSUE THREAD

**Issue by UnbekanntesPferd** [Hypfer/Valetudo#115]
After rooting and installing valetudo on my S50, I'm facing the problem that not every time the whole room is cleaned. I'm pretty sure this can't be connected to valetudo as it's not touching the "cleaning logic" itself, but I'm curious if anyone else is noticing similar issues...?
![IMG_4323](https://user-images.githubusercontent.com/5243510/54110609-1ece0980-43e2-11e9-9674-1635705001af.PNG)

**Comment by matthiasharrer** [comment]
Hi,

there are known issues that the path is not drawn completely. (#84)
Are you sure the room is actually not cleaned? Or could it be that it is simply not shown?

**Comment by UnbekanntesPferd** [comment]
Hi!
That would explain the semicircles on the top of the above map - they look pretty strange.
I will investigate that a bit further and post an update here.
Thanks!

**Comment by matthiasharrer** [comment]
@UnbekanntesPferd did you figure out if it's the same issue as #84 ?

**Comment by UnbekanntesPferd** [comment]
Couldn't figure this out, as I had not been in the room while this happened so far.
But I think closing is ok. I will check again with v0.3.

**Comment by cryptomilk** [comment]
The route is chosen by the robot, Valtetudo has no influence. Routing seems to change with every new firmware version, it seems there isn't the perfect solution found yet
