### ISSUE TITLE
Date and time resets to wrong date

### ISSUE THREAD

**Issue by alexeykap** [Hypfer/Valetudo#1156]
## Describe the bug
Date and time always is wron on the robot.

## To Reproduce

1. Reboot robot
2. Open logs and find NTP syncronysation message such as "[2021-10-13T16:42:17.002Z] [INFO] Successfully set the robot time via NTP to 2021-10-13T16:42:17.894Z"
3. Wait several minutes or make some actions from ui that adds log mesages(for examlple try to enable manual control)
4. Open log and look at date and time on log messages
Result: date and time is wrong.
Expections: date and time is correct.
### Screenshots

[TimeBug](https://user-images.githubusercontent.com/20066453/137178487-86fe6858-fc38-4c29-a892-b33247585460.png)

### Vacuum Model

Xiaomi Mi Robot Vacuum-Mop P

### Valetudo Version

2021.10.0

## Expected behavior

Date must be correct.

## Additional context
<!-- Add any other context about the problem here. --
!
>

**Comment by TopicsLP** [comment]
Hey my Viomi v7 (Xiaomi Mi Robot Vacuum Pro) does also have a time-sync problem.
When i´m connected by SSH after a reboot i´m always dated back to 1970, sound like a hard reset of time.

`root@TinaLinux:~# reboot
root@TinaLinux:~#
login as: root
Authenticating with public key "root@vaccuum"

BusyBox v1.24.1 () built-in shell (ash)

 _____  _              __     _
|_   _||_| ___  _ _   |  |   |_| ___  _ _  _ _
  | |   _ |   ||   |  |  |__ | ||   || | ||_'_|
  | |  | || | || _ |  |_____||_||_|_||___||_,_|
  |_|  |_||_|_||_|_|  Tina is Based on OpenWrt!
 ----------------------------------------------
 Tina Linux (Neptune, 57513AA3)
 ----------------------------------------------
root@TinaLinux:~# date
Sat Jan 17 23:56:02 CET 1970
root@TinaLinux:~#
`

Also i can see as soon as Valetudo updates the time by NTP for some seconds the system time changes, 
but reverts back, additionally I noticed that the time from NTP is retrieved in UTC, but the Valetudo NTP client seems not to specify to set the time as UTC `date -u -s "<timestamp>"` which seems to cause an issue on the viomi.

In my testing the time get´s out of sync when the robots internal system is not set for UTC and the NTP time drift is more than 5 minutes.
I was able to manually modify my time with following commands on SSH
`echo UTC > /etc/TZ
date -u --set "2021-11-05 20:53:00" && sleep 3s && date -u --set "2021-11-05 20:53:03" && sleep 3s && date -u --set "2021-11-05 20:53:06" && sleep 3s && date`

Also with the change of the /etc/TZ file to UTC the NTP sync of Valetudo does not have a "drift" and now my NTP does work.
_Note: /etc/TZ was a Symlink to /tmp/TZ on my Vacuum by default it was configured "CST-8"_

I hope with this information someone else can test it too and verify my provided information. And a workaround can be developed.

**Comment by Hypfer** [comment]
> When i´m connected by SSH after a reboot i´m always dated back to 1970, sound like a hard reset of time.

That's happening because the robot doesn't feature an RTC. That is actually quite common on embedded devices. It's the same for the Raspberry Pi btw.

> Also with the change of the /etc/TZ file to UTC the NTP sync of Valetudo does not have a "drift" and now my NTP does work.
Note: /etc/TZ was a Symlink to /tmp/TZ on my Vacuum by default it was configured "CST-8"

Would it be possible to change the script that starts Valetudo on Viomi to do that? That's how it's done on Dreame

**Comment by Omrigan** [comment]
The trick with setting correct time three times in a row worked for me, even though my TZ is not set to UTC, but to my actual timezone. Valetudo keeps nagging with `[WARN] Error while adjusting timezone to UTC`. Any reason why it wants TZ to be set to UTC?

**Comment by Hypfer** [comment]
Because timezones suck.

**Comment by TopicsLP** [comment]
Ok, now after some testing following other workaround worked, it does extend the boot/start time, but I currently do not care.
I added following to my `/etc/init.d/valetudo` to the function `_fix_timezone`
```
	echo UTC > /etc/TZ
	for i in  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16     #{1..16} did not work on my device
	do
		ntpd -q -p pool.ntp.org
		sleep 2
		date -u -I'seconds' | tr T " " | cut -d'U' -f1    # for testing, can be remove later
	done
```

Let me know your feedback and other testing.

**Comment by Omrigan** [comment]
> Because timezones suck and there is no need for an appliance to have one.
> 
> To avoid any confusion, Valetudo just enforces UTC

That is tricky, since I have to set some time-related stuff, such as DND time. Which timezone should I use? Should I add an offset, or maybe subtract an offset between UTC and my timezone.

IMO timezones are alright and I don't see a reason why we shouldn't set a correct timezone on a robot.

**Comment by TopicsLP** [comment]
> 
> 
> > Because timezones suck and there is no need for an appliance to have one.
> > To avoid any confusion, Valetudo just enforces UTC
> 
> That is tricky, since I have to set some time-related stuff, such as DND time. Which timezone should I use? Should I add an offset, or maybe subtract an offset between UTC and my timezone.
> 
> IMO timezones are alright and I don't see a reason why we shouldn't set a correct timezone on a robot.

The timezone in the UI will automatically convert from your Browsers time zone to UTC (that´s what it does on my end)
Using UTC is way better then catching every timezone related issue. Using UTC is common practice as long as it is not visible to the average User, and the webUI does the job for the timezone.
I´m in UTC+1 (CET) and it does convert my input.
![image](https://user-images.githubusercontent.com/9019121/141656354-0aa7e16d-077a-4fcb-aec7-374d101b3485.png)

**Comment by Omrigan** [comment]
I guess some issues may arise if summer time happes. Not sure if this would be handled properly in valetudo context, I just try to set correct TZ on all my devices. Excuse me if I am not aware enough of how timezones are handled in linux properly.

**Comment by TopicsLP** [comment]
I created a new workaround commit in my Fork https://github.com/TopicsLP/Valetudo/commit/2fb49a3df6d8694b360a12770b01a1d579961f50 
It does work for me and users that do not want it can remove the lines.
 
I´m not sure if the update does touch this file, as it is only for viomi, but for the future new installs will use it and we can link to it if new issue come up.

If this gets approved i will open a pull request on a different repo too to make it update it there too (https://github.com/rumpeltux/viomi-rooting)

Please let me know if this is suitable.

**Comment by Hypfer** [comment]
@TopicsLP what about the suggested wrapper for the date command?

**Comment by TopicsLP** [comment]
> @TopicsLP what about the suggested wrapper for the date command?

I did not check that yet, because i though, it´s stupid to use a workaround everytime NTP does set the time,
with the workaround in the startup it does only delay the time update once and is more accurate.
But i will just check on it again.

**Comment by TopicsLP** [comment]
@Hypfer 
Adding a script to /usr/sbin/date did work on my robot.
```
/bin/date -u -s "$2"
sleep 2
/bin/date -u -s "$2"
sleep 2
/bin/date -u -s "$2"
```

So simply running following commands will add this workaround
```
echo '/bin/date -u -s "$2"' >> /usr/sbin/date
echo sleep 2 >> /usr/sbin/date
echo '/bin/date -u -s "$2"' >> /usr/sbin/date
echo sleep 2 >> /usr/sbin/date
echo '/bin/date -u -s "$2"' >> /usr/sbin/date
echo sleep 2 >> /usr/sbin/date
echo '/bin/date -u -s "$2"' >> /usr/sbin/date
chmod +x /usr/sbin/date
```
Can confirm this does work too.

**Comment by Hypfer** [comment]
That way it's still possible to change the ntp server using the webinterface

**Comment by Hypfer** [comment]
```
echo 'echo "UTC" > /etc/TZ' > /usr/sbin/date
echo '/bin/date -u -s "$2"' >> /usr/sbin/date
echo sleep 2 >> /usr/sbin/date
echo '/bin/date -u -s "$2"' >> /usr/sbin/date
echo sleep 2 >> /usr/sbin/date
echo '/bin/date -u -s "$2"' >> /usr/sbin/date
echo sleep 2 >> /usr/sbin/date
echo '/bin/date -u -s "$2"' >> /usr/sbin/date
chmod +x /usr/sbin/date
```

should probably be added to the viomi rooting script
