### ISSUE TITLE
Viomi V8 map not saved

### ISSUE THREAD

**Issue by benoegen** [Hypfer/Valetudo#1170]
## Describe the bug

Whenever the checkbox for persistant data is checked and save is pressed, the next time the page is opened it is unchecked again.
The robot also creates a new map whenever it starts cleaning.

## To Reproduce

1. Go to 'persistant data'
2. Check 'enabled' & 'save'
3. Leave page and go back to 'persistant data'

### Vacuum Model
Viomi V8, April 2021

### Valetudo Version
2021.10.0 and older

## Expected behavior
Checkbox remains checked and map data is saved.

## Additional context
```
[1970-01-04T03:41:20.889Z] [DEBUG] Map upload started with: {
  query: {
    ts: '271919636806325',
    suffix: 'urls',
    Expires: '272818',
    index: '0',
    method: '_sync.gen_tmp_presigned_url'
  },
  params: { filename: undefined }
}
[1970-01-04T03:41:20.950Z] [DEBUG] <<< cloud: {"result":["ok"],"id":15746}
[1970-01-04T03:41:20.951Z] [DEBUG] << cloud: ignoring response for non-pending request {"result":["ok"],"id":15746}
[1970-01-04T03:41:38.217Z] [DEBUG] <<< cloud* {"stamp":272497}
[1970-01-04T03:41:38.218Z] [DEBUG] >>> cloud* {"stamp":272497}
[1970-01-04T03:41:58.217Z] [DEBUG] <<< cloud* {"stamp":272517}
[1970-01-04T03:41:58.218Z] [DEBUG] >>> cloud* {"stamp":272517}
[1970-01-04T03:42:04.051Z] [DEBUG] >>> cloud: {"method":"set_remember","params":[1],"id":15750}
[1970-01-04T03:42:04.098Z] [DEBUG] <<< cloud: {"result":["ok"],"id":15750}
```

**Comment by reallyuniquename** [comment]
I think I'm having the same issue on v7. Log is flooded with this.

```
[2021-10-19T13:10:04.770Z] [DEBUG] >>> cloud* {"stamp":1634649005}
[2021-10-19T13:10:12.221Z] [DEBUG] Map upload started with: {
  query: {
    ts: '51897555027',
    suffix: 'urls',
    Expires: '1634649608',
    index: '0',
    method: '_sync.gen_tmp_presigned_url'
  },
  params: { filename: undefined }
}
[2021-10-19T13:10:12.327Z] [DEBUG] <<< cloud: {"result":["ok"],"id":12}
[2021-10-19T13:10:12.328Z] [DEBUG] << cloud: ignoring response for non-pending request {"result":["ok"],"id":12}
[2021-10-19T13:10:24.768Z] [DEBUG] <<< cloud* {"stamp":1634649025}
[2021-10-19T13:10:24.769Z] [DEBUG] >>> cloud* {"stamp":1634649025}
```
And this is when I try to enable persistent data although if still stays off in UI.
```
[2021-10-19T13:28:10.769Z] [DEBUG] >>> cloud: {"method":"set_remember","params":[1],"id":36}
[2021-10-19T13:28:10.808Z] [DEBUG] <<< cloud: {"result":["ok"],"id":36}
```

**Comment by drticcz** [comment]
I am having same issue, although slightly different symptoms - I don't see anything about the map upload attempt in the logs at all (level TRACE)

```
/etc/miio/device.conf:
...
vendor=viomi
mac=50:EC:50:EF:2C:D2
model=viomi.vacuum.v7
```


```
/mnt/UDISK/valetudo_config.json:

{
  "embedded": true,
  "robot": {
    "implementation": "auto",
    "implementationSpecificConfig": {
      "ip": "127.0.0.1"
    }
  },
  "webserver": {
    "port": 80,
    "basicAuth": {
      "enabled": false,
      "username": "valetudo",
      "password": "valetudo"
    },
    "blockExternalAccess": true
  },
  "zonePresets": {},
  "goToLocationPresets": {},
  "mqtt": {
    "enabled": false,
    "connection": {
      "host": "foobar.example",
      "port": 1883,
      "tls": {
        "enabled": false,
        "ca": ""
      },
      "authentication": {
       "credentials": {
          "enabled": false,
          "username": "",
          "password": ""
        },
        "clientCertificate": {
          "enabled": false,
          "certificate": "",
          "key": ""
        }
      }
    },
    "identity": {
      "friendlyName": "",
      "identifier": ""
    },
    "interfaces": {
      "homie": {
        "enabled": true,
        "addICBINVMapProperty": false,
        "cleanAttributesOnShutdown": false
      },
      "homeassistant": {
        "enabled": true,
        "cleanAutoconfOnShutdown": false
      }
    },
    "customizations": {
     "topicPrefix": "",
      "provideMapData": true
    }
  },
  "ntpClient": {
    "enabled": true,
    "server": "pool.ntp.org",
    "port": 123,
    "interval": 28800000,
    "timeout": 10000
  },
  "timers": {},
  "logLevel": "info",
  "debug": {
    "systemStatInterval": false,
    "debugHassAnchors": false,
    "storeRawUploadedMaps": false
  },
  "networkAdvertisement": {
    "enabled": true
  },
  "updater": {
    "enabled": true,
    "updateProvider": {
      "type": "github",
      "implementationSpecificConfig": {}
    }
  }
}

```


```
/mnt/UDISK/config/sysConfig.ini:

[Sys_Config]
server_cmd_address=das.3irobotics.net
server_map_address=das.3irobtoics.net
server_log_address=log.3irobotics.net
server_ota_address=ota.3irobotics.net
server_ssl_cmd_port=5010
server_ssl_map_port=5030
server_ssl_enable=0
server_cmd_port=4010
server_map_port=4030
server_sync_time_port=4050
server_log_port=21
server_ota_check_port=5000
server_ota_download_port=2300
wlan_port=8111
wlan_broad_port=8888
deviceFirmsID=1021
deviceType=4
languageType=1
hardwareRtc=0
timezoneSec=28800
```

```
/etc/hosts:

127.0.0.1 localhost

::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
127.0.0.1 ot.io.mi.com ott.io.mi.com
127.0.0.1 de.ot.io.mi.com de.ott.io.mi.com
127.0.0.1 ea.ot.io.mi.com ea.ott.io.mi.com
127.0.0.1 in.ot.io.mi.com in.ott.io.mi.com
127.0.0.1 pv.ot.io.mi.com pv.ott.io.mi.com
127.0.0.1 ru.ot.io.mi.com ru.ott.io.mi.com
127.0.0.1 sg.ot.io.mi.com sg.ott.io.mi.com
127.0.0.1 st.ot.io.mi.com st.ott.io.mi.com
127.0.0.1 tw.ot.io.mi.com tw.ott.io.mi.com
127.0.0.1 us.ot.io.mi.com us.ott.io.mi.com
127.0.0.1 das.3irobotics.net
127.0.0.1 log.3irobotics.net
127.0.0.1 ota.3irobotics.net
```

**Comment by johnappletree** [comment]
I had a similar issue on my Viomi V7.
For me the map data was not received by Valetudo. I was therefore stuck at the no map data image.
During debugging it looked like spoofing the miio_client did not do what it was supposed to do. 
With the help from @Hypfer , it turned out to be the WiFi settings! After entering my WiFi credentials again in the Valetudo WiFi sections the map started working again.

Could you try that? maybe this also works for you?

**Comment by drticcz** [comment]
Re adjusting the wifi settings did not help..
I am trying to decipher how this whole ecosystem should work in order to debug where it is failing but so far I am confused. This is afaik not described in any existing documentation. Maybe if you help me to understand the basics, I will be able to compose some troubleshooting wiki.

The maps suddenly appeared but I think it is still partially broken as the communication is timing out - most likely the time setting is the issue here, as Valetudo keeps complaining on the time sync, although I applied the workaround from https://github.com/Hypfer/Valetudo/issues/1156

```
2022-02-05T04:57:27.807Z] [TRACE] Raw robot angle -0.22859540581703186 -13.097551969396234 calculated 193.09755196939622
[2022-02-05T04:57:27.895Z] [DEBUG] <<< cloud: {"id":79,"error":{"code":-9999,"message":"user ack timeout"}}
[2022-02-05T04:57:27.896Z] [TRACE] Miio error response { id: 79, error: { code: -9999, message: 'user ack timeout' } }
[2022-02-05T04:57:27.898Z] [WARN] Error while adjusting timezone to UTC
[2022-02-05T04:57:27.900Z] [DEBUG] <<< cloud: {"id":78,"error":{"code":-9999,"message":"user ack timeout"}}
[2022-02-05T04:57:27.901Z] [TRACE] Miio error response { id: 78, error: { code: -9999, message: 'user ack timeout' } }
[2022-02-05T04:57:27.903Z] [WARN] Error while adjusting timezone to UTC
```

/usr/sbin/date
```
echo "UTC" > /etc/TZ
/bin/date -u -s "$2"
sleep 2
/bin/date -u -s "$2"
sleep 2
/bin/date -u -s "$2"
sleep 2
/bin/date -u -s "$2"
```

the real system date is UTC

```
root@TinaLinux:~# /bin/date
Sat Feb  5 05:17:44 UTC 2022
```

However /etc/config/system is still different, originally there was ICT-8 / Beijing

```
config system
        option hostname TinaLinux
        option timezone Asia/Bangkok
        option timezone ICT-7

config timeserver ntp
        list server 192.168.1.2
        list server ntp5.aliyun.com
        list server 0.openwrt.pool.ntp.org
        list server 0.cn.pool.ntp.org
        option enable 1
        option enable_server 0
```

Am I missing another setting?

**Comment by johnappletree** [comment]
This is my NTP story for my Viomi v7: I noticed that the robot has two NTP clients. I found this out because my robot is connected to An internet disabled WiFi vlan. First I set the NTP server in the valetudo config file to a lan NTP Server. Afterwards, i noticed some DNS requests to the
 http://0.openwrt.pool.ntp.org/  wich I had chanced in the config file. Changing the NTP server in the web interface resolved the DNS  http://0.openwrt.pool.ntp.org/  requests. I think valetudo has a build in NTP client which is disconnected from the systems NTP client.

How did you configure NTP in the config and webinterface? Is the data consistent?

**Comment by drticcz** [comment]
Seems like I will have to try dig deeper in the Valetudo code to figure out how exactly is it trying to set the TZ. I tried to disable the internal NTP in Valetudo and it looks like the system NTP client is not running at all although from the config ut seems like it does, as the time stays on 1970...

**Comment by lukyjay** [comment]
> Seems like I will have to try dig deeper in the Valetudo code to figure out how exactly is it trying to set the TZ. I tried to disable the internal NTP in Valetudo and it looks like the system NTP client is not running at all although from the config ut seems like it does, as the time stays on 1970...

See the FAQ on setting timezones: https://valetudo.cloud/pages/faq.html

>**Where do I configure the Timezone?**
>The timezone on the device cannot be changed. It is always UTC.

>Every feature in Valetudo that uses time will automatically use the local time reported by your browser. This means you do not have to worry about it. It is handled by the application itself.

>The only instance where the time is relevant, is when looking at the Valetudo logs, which are in UTC (as mentioned above).

**Comment by Hypfer** [comment]
Please check if this is still an issue with the latest version of Valetudo and a fresh firmware built with the dustbuilder.

If so, please open a new ticket
