### ISSUE TITLE
Volume slider is stuck

### ISSUE THREAD

**Issue by thekoma** [Hypfer/Valetudo#1187]
## Describe the bug

The volume slider is stuck in place

## To Reproduce

Go to settings page and try to move the slider.

### Vacuum Model

Roborock Model V1
Also tested on Roborock s6 pure

### Valetudo Version
Release 2021.11.0
Commit 711cd05d92d2917c14807c0b696db5d6af0f9905

## Expected behavior

Change of volume
## Additional context

In the old interface it works perfectly

I've tested on:
Linux:
Chrome Vivaldi and Firefox
MacOS:
Chrome Firefox and Safari
Android:
Chrome and Firefox

**Comment by poindexter12** [comment]
also having this problem AND #1170 with a roborock s5. seems like it's having trouble loading settings or writing to them altogether.

**Comment by Hypfer** [comment]
32898d1c
