### ISSUE TITLE
Dreame L10 Pro Valetudo crashes

### ISSUE THREAD

**Issue by buhralex** [Hypfer/Valetudo#1193]
## Describe the bug

I just received my Dreame L10 Pro and installed Valetudo 2021.11.0. First it seems like everything is working but when the Robot builds his map it loses connection. The strange thing is however that it still reports to HA via mqtt.

I cannot connect via SSH and the robot is not pingable in this state. Valetudo webinterface connection times out.
According to my UDM it still has an IP Address.

## To Reproduce

1. Buy Dreame L10 Pro
2. Install dustbuilder image
3. Install Valetudo
4. Start a cleanup

### Vacuum Model

Dreame L10 Pro
### Valetudo Version

2021.11.0
## Expected behavior

The robot should remain accessible via ssh and Valetudo shut be reachable.
## Additional context

I used the Dustbuilder firmware 1073

**Comment by Hypfer** [comment]
![image](https://user-images.githubusercontent.com/974410/140162620-5f76a08c-c534-4d93-bd70-752b833e3be9.png)
