### ISSUE TITLE
Jitter while pinch zooming map in mobile phone

### ISSUE THREAD

**Issue by xuefer** [Hypfer/Valetudo#1195]
## Describe the bug
Pinch zooming the map in mobile will case the map jitter (jumping randomly)

## To Reproduce
1. Go to Home tab in mobile phone
2. Pinch zoom with two finger

### Screenshots

https://user-images.githubusercontent.com/1741312/140465480-d190b82e-e0b9-4a1d-bb64-a99eed3ec37a.mp4

### Vacuum Model
Roborock T6

### Valetudo Version
2021.11.0

iOS 13.6, Chrome latest

## Expected behavior
None

**Comment by Hypfer** [comment]
Can't reproduce with Firefox Mobile on Android
