### ISSUE TITLE
missing battery level and run time in mqtt

### ISSUE THREAD

**Issue by xuefer** [Hypfer/Valetudo#1196]
### Screenshots
![1](https://user-images.githubusercontent.com/1741312/140476842-2e3dff93-c927-45a5-8f2f-e239e68cf3e8.png)
![2](https://user-images.githubusercontent.com/1741312/140476861-2e1133dc-85bd-4c5e-9ab9-eedf8df45793.png)

### Vacuum Model
Roborock T6

### Valetudo Version
2021.11.0

## Expected behavior
the example mqtt topic shown in connectivity settings means it is expected to supprt battery level

**Comment by Hypfer** [comment]
The battery level is part of the vacuum entity.
Runtime statistics aren't published to mqtt
