### ISSUE TITLE
My firewall is blocking MQTT because of "Zephyr OS Memory Corruption Vulnerability threat"

### ISSUE THREAD

**Issue by slippern** [Hypfer/Valetudo#1201]
My firewall is blocking MQTT from my vaccum, is this a false positive or not?

<img width="445" alt="image" src="https://user-images.githubusercontent.com/1651061/140644536-8237449d-2087-4ead-8148-e162ad3664d9.png">

https://research.nccgroup.com/wp-content/uploads/2020/05/NCC_Group_Zephyr_MCUboot_Research_Report_2020-05-26_v1.0.pdf

**Comment by Hypfer** [comment]
How does someone who is this bad at understanding information on their screen as well as asking a question get their hands on a presumably enterprise firewall appliance?
