### ISSUE TITLE
Roborock disoriented after first run with NoGo Area

### ISSUE THREAD

**Issue by podkilla** [Hypfer/Valetudo#1210]
## Describe the bug
Robot becomes disoriented after not being able to circle nogo area. It stays disoriented for future runs until map is reset and a normal run afterwards regenerates the map data.

## To Reproduce

1. Fresh installation
2. First run to get map (persistent Map enabled)
3. Create NoGo Area in WebIF
4. Let the vaccuum clean the segment with the prior created NoGo area. During this run the robot is unable to circle the nogo area because of chair legs. It tries but fails multiple times. After a while it stops trying and continues its cleaning run. But instead of going back to the previous "lane" it drives mysterious circle paths until it finishes the area.
5. In all following runs the robot drives the same circle paths and is very ineffecient. The picture below shows the start of the run. I canceled it after a minute.

### Screenshots

![screenshto](https://user-images.githubusercontent.com/16955839/141644384-648af753-168c-4e89-b8bf-69823600f60c.JPG)

### Vacuum Model

Roborock S5
### Valetudo Version

2021.11.0
## Expected behavior
Normal cleaning runs

**Comment by Hypfer** [comment]
This is neither a bug in valetudo nor has it anything to do with the no go area.

The side sensor is dirty

**Comment by podkilla** [comment]
Wrong - i cleaned everything multiple times. This has nothing to do with any sensor. The robot runs perfectly fine without the nogo area for weeks.

**Comment by rimrul** [comment]
Still, not a bug in Valetudo. The robot firmware does all the pathing logic.

**Comment by minils** [comment]
I'm facing a similar issue where the robot gets confused and ends its cleaning early after it cleans for the first time. It starts its way as always following the edges of the rooms but after cleaning a small part returns to its dock through very crazy paths, skipping the rest of our apartment.  Will upload a screenshot later.
