### ISSUE TITLE
Redudant UI to check for Valetudo version updates

### ISSUE THREAD

**Issue by JayFoxRox** [Hypfer/Valetudo#1243]
## Describe the bug

With the introduction of the updater, the "About" screen "Latest release" box information should be moved / migrated into the updater.

I already had a version which had the updater (I think), but I still updated manually because I found the "Latest release" box in the updater, which did not allow me to update directly, so I figured there was no auto-updater.
Only after manually upgrading valetudo using SSH, I noticed the "Updater" tab which I probably could have used before.

Even in this new version, the version check / updating is split across 2 UI tabs.
This is redundant and confusing

### Screenshots

![Screenshot_2021-11-27_09-06-13](https://user-images.githubusercontent.com/360330/143673489-9d34cacf-75da-43e0-a9cf-6bb8501430c1.png)
![Screenshot_2021-11-27_09-03-15](https://user-images.githubusercontent.com/360330/143673414-6bd30515-1032-46c9-94d2-5c26f292f477.png)

### Vacuum Model

Dreame D9 (probably a generic problem)

### Valetudo Version

2021.11.1

## Expected behavior

The additional information from "Latest release" information should migrate into the updater; so it also displays the dates of the newest version + the changelog link.
The about dialog version should hyper-link to the new "Updater".

**Comment by Hypfer** [comment]
This is not a bug.
This is something you think that would make sense.


You're really pushing it man.

**Comment by Hypfer** [comment]
253d9f99
