### ISSUE TITLE
New log viewer misses some lines

### ISSUE THREAD

**Issue by ccoors** [Hypfer/Valetudo#1256]
## Describe the bug
The log viewer misses a few lines:

![image](https://user-images.githubusercontent.com/8963459/144273584-15c283cd-bb45-44bd-811d-4ca068f2c17e.png)

## To Reproduce
Open the log viewer, set the log level to 'debug' and wait for a line starting with "Map upload started with". The object printed in [this line](https://github.com/Hypfer/Valetudo/blob/master/backend/lib/robots/MiioValetudoRobot.js#L83) is not displayed correctly.

Looking at the log file via SSH shows the missing lines:
![image](https://user-images.githubusercontent.com/8963459/144273952-c85effc5-6661-4ff2-9c6e-4e6cb78d82ca.png)

### Vacuum Model
Dreame Z10 Pro, FW 1099

### Valetudo Version
2021.11.1 (Dev-build from 4c9dc3bfb99d09319749b6f26451248b2e493bb2)

## Expected behavior
The missing lines are displayed in the log.

**Comment by Hypfer** [comment]
![image](https://user-images.githubusercontent.com/974410/144275610-ca56db9d-0238-4135-a386-2e688b220b5a.png)

huh.
mind sharing the logfile?

**Comment by ccoors** [comment]
Huh. Just noticed it only happens when getting new log lines via SSE. After reloading the page they are displayed correctly.
