### ISSUE TITLE
Dustbin attachment status not working on Rockrobo Gen1

### ISSUE THREAD

**Issue by obelix05** [Hypfer/Valetudo#1269]
## Describe the bug

The AttachmentStateAttribute does not change to false if I remove the dustbin.

## To Reproduce

1. Start listening to AttachmentStateAttribute/# on MQTT
1a. Login to the web-gui and watch the dustbin status on the main page
2. Remove the dustbin from the vacuum --> no change
3. put it in again --> no change

### Vacuum Model

Rockrobo Gen1

### Valetudo Version

2021.12.0

## Expected behavior

The AttachmentStateAttribute should switch to false if i remove the dustbin and switch back to true if the dustbin is installed.

**Comment by Hypfer** [comment]
> The AttachmentStateAttribute does not change to false if I remove the dustbin.

Yes. It's not reported by the robot unfortunately
