### ISSUE TITLE
A way to show MAP tab on default ?

### ISSUE THREAD

**Issue by thundergreen** [Hypfer/Valetudo#127]
Dear all involved. It is just amazing how this project is going so far :) THUMBS UP!

As i use valetudo webinterface for my Dashboard. I was wondering if it would be possible or HOW it would be possible to show the MAP tab as default when valetudo webinterface is loading.

Just to give you an idea:

I implemented this webinterface in my Dashboard looking like this, but each time I call this dashboard it loads the main view which is not very useful for me.

![image](https://user-images.githubusercontent.com/13320319/55149099-d0429e00-5149-11e9-921c-adc89b48d7db.png)

I would rather like to have this view as fedault:

![image](https://user-images.githubusercontent.com/13320319/55149194-0718b400-514a-11e9-8d9b-e9778dc92775.png)

Further more the map seems to be aligned to the left. is it possible having the map centered?

Another questions would be if it is possible to replace the two dots green and red with more beautiful icons?

![image](https://user-images.githubusercontent.com/13320319/55149544-a5a51500-514a-11e9-8372-bebb8e00e8bb.png)

![image](https://user-images.githubusercontent.com/13320319/55149707-f288eb80-514a-11e9-901f-bee68402a4ee.png)

and 

![image](https://user-images.githubusercontent.com/13320319/55149745-07fe1580-514b-11e9-9c7a-29400b3dfc8f.png)

would be an alternative maybe.

Last but not least:

Where or how could I change the color of the map?

Thanks for any hints and help

:) Cheers

**Comment by leonardpitzu** [comment]
this is default:
`<ons-tab label="Home" icon="ion-home" page="home.html" active></ons-tab>`
key here is the `active` keyword which determines the tab active at startup, i.e. it should look like this:
`<ons-tab label="Map" icon="fa-map-marker" page="map.html" active></ons-tab>`

**Comment by thundergreen** [comment]
@leonardpitzu  I guess i will have to build valetudo from source then?

**Comment by thundergreen** [comment]
I  but i cannot compile it.

Gesendet von Mail für Windows 10

Von: leonardpitzu
Gesendet: Donnerstag, 28. März 2019 15:47
An: Hypfer/Valetudo
Cc: ThUnD3r|Gr33n; Author
Betreff: Re: [Hypfer/Valetudo] A way to show MAP tab on default ? (#127)

this is default:
<ons-tab label="Home" icon="ion-home" page="home.html" active></ons-tab>
key here is the active keyword which determines the tab active at startup, i.e. it should look like this:
<ons-tab label="Map" icon="fa-map-marker" page="map.html" active></ons-tab>

**Comment by Hypfer** [comment]
Why don't you just use the map which is available via mqtt?

**Comment by matthiasharrer** [comment]
When still using the webinterface this suggestion might be the solution #109

**Comment by thundergreen** [comment]
I might have missed that bit how would I get this map via mqtt?

Sören Beye <notifications@github.com> schrieb am Do., 28. März 2019, 17:17:

**Comment by Hypfer** [comment]
If you enable mqtt the robot sends a buffer with the map as png to `valetudo/rockrobo/map`

At least thats the default topic.
