### ISSUE TITLE
MQTT auto discovery in home assistant fails

### ISSUE THREAD

**Issue by m3730r** [Hypfer/Valetudo#1279]
The autodiscovery in home assistant fails with the following error:

`Exception in async_discover when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'state_topic': 'valetudo/h0bivac/hass/h0bivac_sensor_ConsumableMonitoringCapability_sensor_all', 'unit_of_measurement': 'Minutes', 'icon': 'mdi:progress-wrench', 'entity_category': 'diagnostic', 'name': 'Sensor cleaning', 'unique_id': 'h0bivac_sensor_ConsumableMonitoringCapability_sensor_all', 'availability_topic': 'valetudo/h0bivac/$state', 'payload_available': 'ready', 'payload_not_available': 'lost', 'device': {'manufacturer': 'Dreame', 'model': 'Z10 Pro', 'name': 'h0bivac', 'identifiers': ['h0bivac'], 'sw_version': '2021.11.1 (Valetudo)', 'configuration_url': 'http://valetudo-gracioustrustworthycrow.local'}, 'platform': 'mqtt'},) Traceback (most recent call last): File "/home/h0bi/homeassistant/lib/python3.8/site-packages/homeassistant/components/mqtt/mixins.py", line 180, in async_discover config = schema(discovery_payload) File "/home/h0bi/homeassistant/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/home/h0bi/homeassistant/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/home/h0bi/homeassistant/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/home/h0bi/homeassistant/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/home/h0bi/homeassistant/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/home/h0bi/homeassistant/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/home/h0bi/homeassistant/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/home/h0bi/homeassistant/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: extra keys not allowed @ data['entity_category']`

Home Assistant 2021.10.6
Valetudo 2021.11.1

Regards

**Comment by Hypfer** [comment]
https://github.com/Hypfer/Valetudo/releases/tag/2021.11.1

> Valetudo 2021.11.1 makes use of new features introduced in Home Assistant 2021.11 (namely configuration_url and entity_category). This means that Home Assistant >= 2021.11 is now required if you want to use it with Valetudo.
