### ISSUE TITLE
Dustbin attachment status not working on Dreame F9

### ISSUE THREAD

**Issue by Schorsch99** [Hypfer/Valetudo#1306]
## Describe the bug
Dustbin attachment status does not change when dustbin is removed. Status is permanently "attached"

## To Reproduce

1. Go to Valetudo WebUI
2. View "Attachments" in WebUI and/or MQTT Status
3. Place/Remove dustbin
4. -> No dustbin Status Change (always "attached")
5. Place/remove watertank/mop
6. -> Status change of watertank/mop reported correctly

### Vacuum Model

Dreame F9

### Valetudo Version

2021.12.1

## Expected behavior

Dustbin status change reported correctly in WebUI and MQTT according to attachment status

## Additional context

There is also no voice message when removing or placing the dustbin.

**Comment by Hypfer** [comment]
The dustbin status unfortunately isn't reported by the robot.

**Comment by Schorsch99** [comment]
The factory firmware had voice messages when placing/removing dustbin, so it must report the state somewhere, I assume.

**Comment by Hypfer** [comment]
If you find it let me know

**Comment by Schorsch99** [comment]
Any hint where to start searching?

**Comment by Hypfer** [comment]
I was being sarcastic.
