### ISSUE TITLE
map.png via mqtt

### ISSUE THREAD

**Issue by desq42** [Hypfer/Valetudo#131]
Nice Feature to send the map.png via mqtt. (kudos)
I´m not a "Home Assistent"-Guy therefore I´m searching for a way to get the png from my MQTT-Broker which "lives" within ioBroker. My first try to use "node-red" was not successful.
(node-red is unable to decode the binary buffer in which he subscribes to this topic.)
Has somebody been able to subscribe to this topic and "extract" a valid png?
(perhaps via python-script which subscribes and saves the png to disk?)

Regards,
desq

**Comment by florie1706** [comment]
Have pretty much the same problem. I use FHEM and it does not show the PNG.it has just funny signs as reading.

**Comment by Hypfer** [comment]
![image](https://user-images.githubusercontent.com/974410/55412490-d4b2f080-5567-11e9-9d92-acfac5fa4d01.png)
![image](https://user-images.githubusercontent.com/974410/55412497-da103b00-5567-11e9-8447-71cee77e27d2.png)

This looks okay? What was your experience @desq42 ?

**Comment by desq42** [comment]
Mine looks like this; (Problem with my mqtt-Broker?)
![Bildschirmfoto 2019-04-03 um 08 08 38](https://user-images.githubusercontent.com/18470786/55456605-c3a9c400-55e7-11e9-97a7-5c177f4fc5de.png)

**Comment by Hypfer** [comment]
Theres definitely something wrong there. PNGs always start with 0x89 0x50 0x4e 0x47. Yours starts with 0xef

There was someone on the Home Assistant discord who also had issues and succeeded with a different mqtt broker so that might indeed be the problem here. It works fine using Mosquitto 1.4.10

**Comment by desq42** [comment]
Thanks for the Info. I´m raising an issue for the mqtt-Adapter within ioBroker.
Closing.
