### ISSUE TITLE
WebUI not accessible anymore after update

### ISSUE THREAD

**Issue by Naabmaster69** [Hypfer/Valetudo#1321]

**Comment by Naabmaster69** [comment]
I tried to access the robot over my private network, no VPN or sth in between

**Comment by Hypfer** [comment]
Valetudo uses the `is-in-subnet` library and allows access from either localhost or all private IP ranges.

See here:
https://github.com/natesilva/is-in-subnet/blob/1a9da7b8713fe3e7db0eaf6398dca9f2fa83f651/src/ipRange.ts#L3-L25

If you're not able to access your robot your network is likely misconfigured.

**Comment by Naabmaster69** [comment]
True, I‘m not using the standard private ip address. Is there a way hiw to access the WebUI again wirhout changing my network ip address?

**Comment by Hypfer** [comment]
Please reconfigure your network to use a non-publicly-routable address range then.
I'm fairly certain that the way it is now already causes a lot of breakage in other applications.
