### ISSUE TITLE
Logo Design for Valetudo

### ISSUE THREAD

**Issue by newfinal100** [Hypfer/Valetudo#136]
Hello! I really like this project and I thought I could design a logo for it since it doesn't have one. Here are some variations I made with different shapes of the icon as well as different fonts, you can pick one from these 12 and also let me know if there's anything you'd like me to change.

If you like the idea and the whole look of it, I'll provide you with different color variations so it wont be only black and white, and I'll also send it to you in all formats you may need :) Let me know what you think!

![variations](https://user-images.githubusercontent.com/49202520/55504781-da850080-5651-11e9-82b6-8c951fff270d.jpg)

**Comment by unfassbarstephan** [comment]
Great, I really like the idea of a logo. 
 
The designs are very beautiful.  How about combining the V-shaped logo and "aletudo" in a clear font, for example the second one from the upper right square.

But it's only a suggestion.

**Comment by newfinal100** [comment]
I'm glad you liked them! And that's a really good idea, I'll try that and send it to you. Also, which V-shaped icon do you like the most from all three? So that I know which one to work with :)

**Comment by unfassbarstephan** [comment]
So I think modern clear design is best, so I'm for the V from the 2nd line.  Maybe you can also shorten or straighten the ends a little bit, so that the V comes to the fore even more.  It would also be conceivable to highlight the lettering a little, for example with a dark blue, so that the "Valetudo" is visible at first sight.

**Comment by newfinal100** [comment]
![valetudo 2](https://user-images.githubusercontent.com/49202520/55512063-6bfc6e80-5662-11e9-9082-90a3430bd9b1.jpg)

What do you think about these?

**Comment by unfassbarstephan** [comment]
I've made some quick and dirty adjustments. The left brighter version looks very promising. I aligned the font according to the orange auxiliary lines and adjusted the size a bit (≈ 120%). 

I like the seconde one in the picture below.

![Valetudo_Logo](https://user-images.githubusercontent.com/25052791/55536677-a8f44f80-56ba-11e9-8db3-adcace22d39a.png)

**Comment by newfinal100** [comment]
Done :) is it okay like this?

![Valetudo 2(3)-01](https://user-images.githubusercontent.com/49202520/55556046-ea025900-56e6-11e9-968b-02109e84e089.jpg)

**Comment by Hypfer** [comment]
Looks great!

**Comment by newfinal100** [comment]
Then great :) let me know if there's nothing else you'd like me to change so that I know if I can send you the final original files

**Comment by Hypfer** [comment]
I think that it would be a good idea to use the map colors in the logo but thats just a very minor adjustment. Should be easy to change later on.

Other than that I can't say much but thank you. This brings a lot of value to the project and marks another huge step towards the end of beta

**Comment by newfinal100** [comment]
I'm very glad that you like it! I agree, it is one huge step :) And yeah, I can definitely do that but I don't know which are the map colors?

**Comment by Hypfer** [comment]
See https://github.com/Hypfer/Valetudo/blob/master/client/zone/index.html#L14

**Comment by unfassbarstephan** [comment]
I also think the result is great and using the map colors is  good, too.  These are similar shades of blue as well.

Thanks for your work!

**Comment by newfinal100** [comment]
![map colors](https://user-images.githubusercontent.com/49202520/55574931-f3eb8280-570d-11e9-8285-0f97cd176a82.jpg)

Is this it? :)

**Comment by Hypfer** [comment]
Sorry I've pointed to the wrong file since I forgot that I was workin on another branch. It's

#0076ff & #52aeff

**Comment by newfinal100** [comment]
It's okay, I'm changing it now :))

**Comment by newfinal100** [comment]
![map colors-01](https://user-images.githubusercontent.com/49202520/55575766-f7800900-570f-11e9-855b-a977e257f51b.jpg)

**Comment by unfassbarstephan** [comment]
I love it! This is a beautiful color combination.

**Comment by Hypfer** [comment]
Perfect!

**Comment by newfinal100** [comment]
Glad you liked it! :) here you can get the original files:
https://drive.google.com/drive/folders/1blWNrScNu7zhPN58l3Qj4116ruzZt5uH?usp=sharing

**Comment by Hypfer** [comment]
And it's live.

**Comment by axel-kah** [comment]
Very nice job! A version in square format with just the V part would also be useful as favicon and as "app" shortcut on mobile OS homescreens, etc.

**Comment by Hypfer** [comment]
@axel-kah

That's already there. Take a look at the latest commit on master
