### ISSUE TITLE
Area limits continue to move up in the map

### ISSUE THREAD

**Issue by piggei** [Hypfer/Valetudo#1371]
Area limits continue to move up in the map

Hi Soren,  since december release I noticed a gradual shift up of the map limits, as you can see in the pic. Red lines show the original limits; this is the result since 2 jan 2022 (three weeks about) when I reset the map and remade it with the new version.

## To Reproduce

Just use it some weeks

### Screenshots
![valetudo_error](https://user-images.githubusercontent.com/20422025/150659206-82ff640a-2d58-4ba1-97cb-2886b978f84f.png)

### Vacuum Model
Dreame L10 pro

### Valetudo Version

2022.01.0

## Expected behavior

The areas stand still :-)

## Additional context

Do you think may be useful to add a map backup/restore button in case of error like this one?

**Comment by Hypfer** [comment]
Valetudo is not a custom firmware so it can't do anything about how the robot operates.
