### ISSUE TITLE
Support for Viomi V9 with dustbin

### ISSUE THREAD

**Issue by tgrrr** [Hypfer/Valetudo#1402]
Hi,

Would you consider adding support for the Viami s9 with the auto emptying into the dustbin?

https://www.viomi.com/robot-vacuums/viomi-alpha-s9

It costs less than the dream z10, which is the only model you have rooted that has that feature.

Thanks,

Phil

**Comment by Hypfer** [comment]
See for a very verbose response to this question: https://github.com/Hypfer/Valetudo/discussions/1403#discussioncomment-2131844

Also, issues are not the right place for questions like these. Please use the discussion feature
