### ISSUE TITLE
Valetudo not able to reach Robot on S5Max

### ISSUE THREAD

**Issue by ArminPrivate** [Hypfer/Valetudo#1416]
I started yesterday with rooting my S5Max. After installing Valetudo it displayed on the webinterface that it is unable to control the robot and was unable to load anything from robot (e.g. map, state, control).
The Robot was before updated/controlled via the Roborock app and not the xiaomi home app. I guess this causes the following problem where I'm not sure if the script belongs to dontvacuumme or valetudo:

My /mnt/data/miio/wifi.conf after rooting was looking like that:
```
ssid="MySSID"
psk="MyPassword"
key_mgmt=WPA
uid=rr5f605c000000
region=EU
cfg_by=rriot
```

the cfg_by=rriout is not expected by the if condition in /mnt/reserve/_root.sh (cp from /root/_root.sh.tpl) 
```
[root@rockrobo miio]# cat /mnt/reserve/_root.sh 
#!/bin/bash
if [[ -f /mnt/data/valetudo ]]; then
	mkdir -p /mnt/data/miio/
	
	if grep -q "cfg_by=tuya" /mnt/data/miio/wifi.conf; then
		sed -i "s/cfg_by=tuya/cfg_by=miot/g" /mnt/data/miio/wifi.conf
		sed -i "s/cfg_by=rriot/cfg_by=miot/g" /mnt/data/miio/wifi.conf
		echo region=de >> /mnt/data/miio/wifi.conf
		echo 0 > /mnt/data/miio/device.uid
		echo "de" > /mnt/data/miio/device.country
	fi

	VALETUDO_CONFIG_PATH=/mnt/data/valetudo_config.json /mnt/data/valetudo >> /dev/null 2>&1 &
fi
```

the sed command for handling cfg_by=rriot is already included but it will never be executed because grep won't find cfg_by=tuya - i changed that line to `grep -q "cfg_by=rriot" ... ` and rebooted the robot, afterwards it was working like a charm.

If that script is delivered from dontvacuumme please let me know then I can transfer the issue to the other project

**Comment by Hypfer** [comment]
https://github.com/dgiese/dustbuilder-features/blob/master/fwinstaller_nand/_root.sh.tpl

Please open a PR in that repo
