### ISSUE TITLE
Can't accept nor dismiss the new map

### ISSUE THREAD

**Issue by thor171** [Hypfer/Valetudo#1469]
## Describe the bug

After rooting and installing Valetudo I did a first cleanup. I activated persistent maps and it created a map. Now I wanted it to cleanup more rooms and opened the doors, which of course triggered a map change after that second cleaning. Unfortunately, I can't confirm nor deny the message shown in the notifications. It is also not possible to change the map settings. I tried to delete the map and disable the persistent map, too. It didn't work.
The log doesn't seem to contain the error, when I click on the messagt, it says in the left corner at the bottom:
"An error occurred while updating Valetudo Events settings: Error: Request failed with status code 400
Events
yesterday at 10:54 PM

A map change is pending. Do you want to accept the new map?"

I tried different browsers, so I don't think this is the problem.
## To Reproduce

In a fresh Valetudo installation, activate persistent maps.
Start a full cleanup, but skip some areas (physically, for example closed doors).
Now do another full cleanup with new areas the robot doesn't know.
In the notifications you will be asked if you want to accept the new map, but this doesn't work.
### Vacuum Model

Xiaomi Mijia (Dreame) 1C
Firmware: 1110
Model: STYTJ01ZHM

### Valetudo Version

2022.03.1

Commit
166c69d87fc9b1fd2010e0787ad1c68ab71710ea
## Expected behavior

A click on yes or no would apply or omit the new map.
## Additional context

[valetudo.log](https://github.com/Hypfer/Valetudo/files/8470615/valetudo.log)

**Comment by Hypfer** [comment]
Oh interesting. That isn't implemented for the 1C yet.

Please try this binary and report back if it works
[valetudo.zip](https://github.com/Hypfer/Valetudo/files/8474964/valetudo.zip)

**Comment by thor171** [comment]
Thanks Hypfer, it works! No problems anymore, I can accept the new map and get it instantly.
