### ISSUE TITLE
Segment Management menu does not work

### ISSUE THREAD

**Issue by thor171** [Hypfer/Valetudo#1472]
## Describe the bug

In Segment Mangagement, it's not possible to edit segments because the UI says: "Editing segments requires the robot to be docked" even though the robot is docked. On the Home screen, the robot is docked.
## To Reproduce

After the robot made a persistent map, go to Segment Management and try to edit segments.
### Screenshots

![home_screen](https://user-images.githubusercontent.com/34920751/163333783-1beb9b30-84e6-496c-8147-cde8cd2a77e4.png)
![segment_management](https://user-images.githubusercontent.com/34920751/163333789-e6d50521-6b06-4dec-bfd8-6c3c95fc24c5.png)

### Vacuum Model

Xiaomi Mijia (Dreame) 1C
Firmware: 1110
Model: STYTJ01ZHM
### Valetudo Version

2022.03.1
## Expected behavior

Expected to be able to edit the segments.
## Additional context

[valetudo.log](https://github.com/Hypfer/Valetudo/files/8487083/valetudo.log)

**Comment by Hypfer** [comment]
> On the Home screen, the robot is docked.

![image](https://user-images.githubusercontent.com/974410/163349462-41e82184-73cb-4b67-aca0-f9c6847fa223.png)

Are you sure about that?

**Comment by thor171** [comment]
Hm, I just checked if it was, physically, docked. Maybe it was quite off. I will check that when I am at home.

**Comment by thor171** [comment]
It did a cleanup again and went to the dock, but the state is idle. If it should say docked, then there might be another problem. I don't think it's a contact problem, because it's charging.

**Comment by shepler007** [comment]
I just upgraded to 2022.3.1 and my bot is not generating segments.  It has been run twice and all I get is this big blue mapping.  My bot is a Roborock S5.
![Screenshot 2022-04-18 085416](https://user-images.githubusercontent.com/18542635/163811314-081aa941-59ae-480a-b51f-3926c651b098.png)

**Comment by Hypfer** [comment]
@shepler007 https://github.com/Hypfer/Valetudo/discussions/1463

Different robot. Different issue

**Comment by Hypfer** [comment]
Fixed with fdb51e7
