### ISSUE TITLE
config.json overwriting itself

### ISSUE THREAD

**Issue by vr6syncro** [Hypfer/Valetudo#148]
hey,

i edited the config.json for mqtt and restarted the service. but every time the original config.json was restored.

is it a problem with the vi editor? or the firmware?
(i checked if the vi editor is saving the file and it seems that he write it but im not sure.)

**Comment by vr6syncro** [comment]
it seems a vi editor issue.

i made apt-get update and apt-get install nano 
and used Editor nano

**Comment by pejotigrek** [comment]
I'm having the same issue with nano..

file is edited & saved, then if I restart valetudo or vacuum, the original config.json is coming back :(
