### ISSUE TITLE
Roborock S5: Unknown cloud message received: { method: 'event.fan_power_reduced', params: [ 0 ], id: 734069105 }

### ISSUE THREAD

**Issue by Roxxor91** [Hypfer/Valetudo#1486]
## Describe the bug

The log shows: Unknown cloud message received: { method: 'event.fan_power_reduced', params: [ 0 ], id: 734069105 }
## To Reproduce

I don't know. I think I have to clean my filter?
### Vacuum Model

Roborock S5
### Valetudo Version

2022.05.0
## Expected behavior

Show a notification that "the fan power is reduced" and provide a solution. (e.g. Clean your filter; if this is actually the case here)

**Comment by Hypfer** [comment]
As far as I can tell, this event has no handling in the MiHome app. Its meaning is unknown but likely irrelevant.

We'll filter it out c56e7a26df92e628906f78e7b2ee28b243dcd70b
