### ISSUE TITLE
mqtt map 

### ISSUE THREAD

**Issue by vr6syncro** [Hypfer/Valetudo#149]
hot should the datapoint look like?

i get this code:
`�PNGIHDR�lF����IDATx��_��g}����=�`���64����r1S-�@�h2����a*ES�H���F��}s�U��^䲑ܦ�Tj5����B[Pgu���C���S�����!�1l�_�w�ɻ?
[...]

i expected a url or something.

**Comment by Hypfer** [comment]
The mqtt message contains the png itself. What you're seeing is the png being interpreted as text

**Comment by mar565** [comment]
Is there a simple way to get the image out of it?
Would be nice to avoid another webserver.

**Comment by Hypfer** [comment]
Closing since PNG rendering is not part of valetudo anymore and has been moved to https://github.com/Hypfer/ICantBelieveItsNotValetudo
