### ISSUE TITLE
Broken links in integration page

### ISSUE THREAD

**Issue by LordDN** [Hypfer/Valetudo#1525]
The links to HA, openHAB & Node-RED under "Autodiscovery" in the [MQTT-integration page](https://github.com/Hypfer/Valetudo/blob/master/docs/_pages/integrations/mqtt.md) are missing the extension .md, breaking them:

https://github.com/Hypfer/Valetudo/blob/master/docs/_pages/integrations/home-assistant-integration
https://github.com/Hypfer/Valetudo/blob/master/docs/_pages/integrations/openhab-integration
https://github.com/Hypfer/Valetudo/blob/master/docs/_pages/integrations/node-red

Adding .md to each of these makes them functional again.

The [link pointing to MQTT](https://github.com/Hypfer/Valetudo/blob/master/pages/integrations/mqtt.html) [in the HA page](https://github.com/Hypfer/Valetudo/blob/master/docs/_pages/integrations/home-assistant-integration.md#advanced-services) ends with .html instead of .md, and is missing both /docs/ and the underscore before "pages".

The [links pointing to MQTT](https://github.com/Hypfer/Valetudo/blob/master/docs/_pages/integrations/mqtt.html) [in the Node-RED page](https://github.com/Hypfer/Valetudo/blob/master/docs/_pages/integrations/node-red.md) also work again when .html is replaced with .md.

**Comment by Hypfer** [comment]
That's because you're reading the raw markdown files.

Those are not meant to be read directly. Instead, they are converted to this website: https://valetudo.cloud/
