### ISSUE TITLE
Client-side Wi-Fi heatmap generation

### ISSUE THREAD

**Issue by Hypfer** [Hypfer/Valetudo#1528]
The Idea here would be to integrate the Wi-Fi Heatmap functionality of [Valeronoi](https://github.com/ccoors/Valeronoi) into the Valetudo frontend in a way that does not affect the backend.

First, the user would navigate to a special map view similar to the robot coverage map.
There, they'd be shown a warning dialog that this feature may exhaust browser resources, use a lot of ram etc.
If the user accepts the warning, the site would then start periodically polling the `WifiConfigurationCapability` and maybe also even the `WifiScanCapability` if available. The aggregated data would then be rendered onto the live map as a signal heatmap.

This view would need full live map controls to allow the user to start the Wi-Fi mapping without having to open the Valetudo Webinterface a second time in another tab. Furthermore, it should also feature a data export button so that it can be persisted somewhere to be viewed and processed later. It would likely make sense to use the same data format as Valeronoi does.

**Comment by badsmoke** [comment]
when and where/how was the feature added? am i missing something?
