### ISSUE TITLE
Handling vacuum errors in MQTT mode

### ISSUE THREAD

**Issue by Dinth** [Hypfer/Valetudo#1532]
## Describe the bug
Hi. Iam using Valetudo with MQTT HA integration. Unfortunately, while the error_description sensor is correctly created in HA, its value is not readable - the correct value only shows up for a fraction of a second and is replaced with "UNKNOWN ERROR CODE undefined" and then goes back to the correct one ("Cliff sensor dirty or robot on the verge of falling"). Unfortunately, this means that by the time when error notification automation is executed, the error_description sensor state is in "UNKNOWN ERROR" state. 

## To Reproduce
1. Run vacuum cleaning
2. Wait for an error
3. Check the state of "sensor.error_description" sensor and its history.

### Screenshots
![image](https://user-images.githubusercontent.com/313674/182037261-6bbbf5fe-3646-48ec-9008-1cb624104b64.png)

### Vacuum Model
S5

### Valetudo Version
 2022.02.0

## Expected behavior
The error_description sensor should change its state to the actual error and stay that way until actioned.

**Comment by Hypfer** [comment]
>Valetudo Version
>2022.02.0

Please upgrade to the latest valetudo version to see if it is fixed there
