### ISSUE TITLE
Improve Logging

### ISSUE THREAD

**Issue by Hypfer** [Hypfer/Valetudo#154]
Valetudo needs configurable loglevels instead of randomly added/removed console.log statements.

**Comment by alexkn** [comment]
@rumpeltux, @matthiasharrer, @rimrul 
Does anyone have experience with a logging framework that we could use?

Currently the logfile and the console output only contains the log message, but no timestamp and no loglevel.

**Comment by rimrul** [comment]
None that would work for Valetudo.
