### ISSUE TITLE
Dreame L10Pro: Log shows Warning about serialization of Quirks

### ISSUE THREAD

**Issue by buhralex** [Hypfer/Valetudo#1541]
## Describe the bug
After updating my L10 Pro to 2022.08 the log shows a warning about serialization of Quirks.
I found the closed bug report where it was mentioned that the firmware of the robot might be to old but I just updated to 1138.

## To Reproduce
1. Open Quirks section
2. Open Log
3. Discover warning

### Vacuum Model

Dreame Z10Pro

### Valetudo Version

2022.08.0

## Expected behavior

There probably shouldn't be a warning.

## Additional context

Log entry:
`2022-08-06T15:05:20.614Z
Warn
Error while serializing quirk with ID 01ef3ca4-1b52-4c03-a927-b688dffda1cc Error: Received invalid value 2
    at Quirk.getter (/snapshot/Valetudo/backend/lib/robots/dreame/DreameQuirkFactory.js:220:39)
    at async Quirk.serialize (/snapshot/Valetudo/backend/lib/core/Quirk.js:44:20)`

**Comment by Hypfer** [comment]
It's a different quirk than the one in the other issue.

Unfortunately it seems that the functionality that it was intended to implement cannot be implemented as easily as expected.
Thanks for reporting!

dbbd0f0c
