### ISSUE TITLE
Charging dock icon disappeared after updating Dreame L10 Pro to 1138 on Valetudo 2022.08.0

### ISSUE THREAD

**Issue by andreagdipaolo** [Hypfer/Valetudo#1545]
## Describe the bug

After updating the robot to the new firmware I see no dock icon on the map.
Tried to clear cache, use another browser, reboot the robot, but nothing.

## To Reproduce

1. Go to the robot web interface
2. See the absence on the map

### Screenshots

![image](https://user-images.githubusercontent.com/49479876/183468718-f99adfea-f9ff-400b-8d06-6353caa07a62.png)
Vacuum in docked state after full cleanup.

### Vacuum Model

Dreame L10 Pro - FW 1138

### Valetudo Version

2022.08.0

## Expected behavior

Icon present on map

## Additional context

Confident that on 1105 & Valetudo 22.08.0 the icon was showing.

**Comment by Hypfer** [comment]
That's because for whatever reason, the map uploaded by the firmware does not contain a valid charger position.
