### ISSUE TITLE
NOT FOUND https://cdn.awsbj0.fds.api.mi-img.com/updpkg/v11_003468.fullos.pkg

### ISSUE THREAD

**Issue by thundergreen** [Hypfer/Valetudo#155]
Dear all I tried flashing / Updating Valetudo but links given in Tutoral is dead. I flashed with 3466 but I cannot get states or coomtrol.

is there a link for me to donload 3468?

Thanksmates and thanks for this great piece of work

Object Not Found: Make sure your object exist in current region, request-id=fd2b2955-78e6-3038-0000-0169f8f0d886

Which country do I have to be.. I am using VPN :)

**Comment by Hypfer** [comment]
https://cdn.awsde0.fds.api.mi-img.com/updpkg/v11_003468.fullos.pkg

**Comment by thundergreen** [comment]
thanks!
