### ISSUE TITLE
No Segment edit on S5

### ISSUE THREAD

**Issue by nicedevil007** [Hypfer/Valetudo#1550]
## Describe the bug
There is no Zone to Edit the Segments of my map.

## To Reproduce
1. Go to 'Settings\Map'
2. Click on 'Segment Management'
3. See error

### Screenshots
![image](https://user-images.githubusercontent.com/17103076/184974089-6e19e725-c523-46a7-836f-2b9d9c20ffc1.png)

### Vacuum Model
Roborock S5 

### Valetudo Version
2022.08.0

## Expected behavior
I'm able to edit the map segments.

## Additional context
Persistent Map is turned on 
![image](https://user-images.githubusercontent.com/17103076/184974500-b4445e1a-f089-410b-b111-4097f2d11910.png)

**Comment by Hypfer** [comment]
![image](https://user-images.githubusercontent.com/974410/185041940-3b8cfc84-ebd2-4dee-b433-24d32ad2d2f5.png)
