### ISSUE TITLE
Fall Back Image ?

### ISSUE THREAD

**Issue by thundergreen** [Hypfer/Valetudo#156]
Dear all,

i faced a very interessting issue. I compiled built and transferred new firmware to my robo. Once flashing process was over i saw valetusoversion and Frirmware version in correct manner. After reboot i got like a fall back to my old image?

Is that possible or makes it sense.

In short. Valetudo 0.3.0 has been installed and somehow fell back to 0.2.3.

**Comment by Hypfer** [comment]
The robot does revert its firmware if something doesn't work so I guess that the new firmware image had some issues.

Did you follow the new guide? If you're using an old dustcloud checkout make sure to `git pull` to use the latest version of the imagebuilder

**Comment by thundergreen** [comment]
@Hypfer  I deleted all directories and created everything from scratch. So there sholdn't be the problem.. but i cannot download th image from the docs.. i am actually via vpn via sweden online .. should i use another country?

**Comment by thundergreen** [comment]
Unfortunately no change .. see here:


![image](https://user-images.githubusercontent.com/13320319/55689536-edffd680-5985-11e9-999b-b4d8e61e2c26.png)

new firmware version flashed 3468 but no controls possible

--> rebooted: 

![image](https://user-images.githubusercontent.com/13320319/55689629-14724180-5987-11e9-9c15-ba24b5aeafcd.png)

**Comment by thundergreen** [comment]
Finally it set it self back to factory settings now..starting from scratch

**Comment by cryptomilk** [comment]
The robot has an A/B system. If something goes wrong with the new flashed system it will boot to the old one which was working. Did you update the imagebuilder.sh script? You need the latest version ...

**Comment by thundergreen** [comment]
I comletely started from scratch for updating to latest valetudo.. Two times it failed.. where could i see debig logs or something helpful?


before it reset to previous woring valetudo version now to factory reset

**Comment by thundergreen** [comment]
EDIT: Now I am confused: I connected the robo with the app somehow to the wifi. And I saw that valetudo 0.3.0 is installed and running well. BUT i have the chinese language. Is it possible to change the language without flashing the device again? I took the language file english but somehow it doesn't take it into account. Anyway. The vacuum is still rooted and valetudo is running well.

**Comment by CrazYoshi** [comment]
> EDIT: Now I am confused: I connected the robo with the app somehow to the wifi. And I saw that valetudo 0.3.0 is installed and running well. BUT i have the chinese language. Is it possible to change the language without flashing the device again? I took the language file english but somehow it doesn't take it into account. Anyway. The vacuum is still rooted and valetudo is running well.

Same issue here. Flashed twice but robot speak chinese every time

**Comment by fvollmer** [comment]
It might be related to the image builder: https://github.com/dgiese/dustcloud/issues/208

**Comment by cryptomilk** [comment]
See the FAQ how to install a differnt language https://github.com/Hypfer/Valetudo/wiki/FAQ

This will also survive a new flash ...

**Comment by Hypfer** [comment]
I've also experienced a rollback of the firmware to 0.2.3

But.. why?
