### ISSUE TITLE
Enhancement: MQTT "set" topic should be published by default

### ISSUE THREAD

**Issue by systemofapwne** [Hypfer/Valetudo#1564]
## Describe the bug
Automatically publish the "set" topic for "$settable = true" topics

### Screenshots

This is, how the structure looks by default in the broker
![image](https://user-images.githubusercontent.com/30482165/186658990-0c243b03-7858-4500-8c73-91aa9a6df420.png)
And this is the structure, that I would like to see
![image](https://user-images.githubusercontent.com/30482165/186658925-72527492-21c2-4d3a-834c-e6e305828133.png)

### Valetudo Version
2022.08.0 Nightly

## Additional context
There are basically two reasons, why I would like to see this enhancement.
1. It makes it clearer, how the MQTT structure works by just looking at it. It took me some time to find this out, by reading the manual. With the "set" topic published by default, it would have been more clearer (even without reading the manual).
2. Interoperability with other systems becomes better. For example, I have valetudo connected to Mosquitto and I also have IoBroker (IOB) listening on Mosquitto. If I now want to set an MQTT state via IOB, the internal data representation within IOB needs to have the "set" topic be present. However that is not the case by default and needs this topic be created manually (either on the MQTT broker or in ioBroker). Programatically setting this topic is not easily possible in IOB (that is by design). If Valetudo just publishs the "set" topic, it would automatically be present on the MQTT broker and IOB.

**Comment by Hypfer** [comment]
I don't think that having a different opinion on an architectural decision could be classified as a "bug" in the software.
