### ISSUE TITLE
[Enhancement] Fan speed selection for scheduled cleanups

### ISSUE THREAD

**Issue by SHA-NDY** [Hypfer/Valetudo#1602]
On creating a new timer one can choose between full or section cleanup. It would be nice to have an option for the used fan speed for that specific timer. So I could do a "light" cleanup every second day very easy without having to switch to low fan speed manually before cleanup starts.

**Comment by Hypfer** [comment]
The timers are very basic on purpose as it is recommended to use a proper home automation software for advanced tasks

**Comment by SHA-NDY** [comment]
So sad. Home automation for that task is an overkill for me.
