### ISSUE TITLE
CombinedVirtualRestrictionsCapability endpoint returns mixed coordinates

### ISSUE THREAD

**Issue by DmytroMelnyk** [Hypfer/Valetudo#1604]
## Describe the bug

`/api/v2/robot/capabilities/CombinedVirtualRestrictionsCapability` endpoint returns wrong (x and y coordinates are mixed) coordinates.

### Vacuum Model

Dreame D9 Pro

### Valetudo Version

2022.09.0
## Expected behavior

I expect virtual restrictions doesn't change

**Comment by Hypfer** [comment]
Please elaborate further
