### ISSUE TITLE
Inverted modes on Dreame L10 Pro

### ISSUE THREAD

**Issue by andreagdipaolo** [Hypfer/Valetudo#1614]
## Describe the bug

Vacuum and Vacuum&Mop modes inverted on Dreame L10 Pro

## To Reproduce

1. Go to Mode
2. Select Vacuum&Mop
3. Start cleaning
4. Won't release water
5. Change mode to Vacuum only
6. Starts releasing water

### Screenshots

![image](https://user-images.githubusercontent.com/49479876/195998679-505743f9-d840-445b-a594-595a745ca100.png)

### Vacuum Model

Dreame L10 Pro

### Valetudo Version

2022.09.0 38fb6e43eff6b158b1d18e09259910d2341758b0

## Expected behavior

Selecting Vacuum it should only vacuum. Selecting Vacuum&Mop it should vacuum and mop.

## Additional context

Happens both in full and segment cleaning.

When cleaning is started from the physical button, it will start as vacuum only even if water tank is attached, but it will mop because modes are inverted so it behaves correctly but showing the wrong mode on web GUI.

**Comment by Hypfer** [comment]
Finally, a bug report that is actually a bug 🙏

Thank you for reporting and also testing the latest commits!
Fixed in 8b6643c978b979aaddfa5806ac5cfba130f441e8
