### ISSUE TITLE
CombinedVirtualRestrictionsCapability endpoint returns mixed coordinates

### ISSUE THREAD

**Issue by DmytroMelnyk** [Hypfer/Valetudo#1622]
## To Reproduce

1.  ``` curl -X 'PUT'   'http://$VACUUM_API/api/v2/robot/capabilities/CombinedVirtualRestrictionsCapability' -H 'Content-Type: application/json'   -d $(curl -X 'GET'   'http://$VACUUM_API/api/v2/robot/capabilities/CombinedVirtualRestrictionsCapability') ```
2. You'll see that restrictedZones has been changed

$VACUUM_API - is the IP address of the robot

### Screenshots
1. https://prnt.sc/1AI9uQTPpFEy
2. After aformentioned command execution: https://prnt.sc/O3uy4GtCf-DI

### Vacuum Model
Dreame D9 Pro

### Valetudo Version
2022.10.0

## Expected behavior
Restricted zone must be without changes

**Comment by Hypfer** [comment]
Oh! Indeed

Fixed with
c4d5df8f78421d7254dd0a55ea610825552612e8
