### ISSUE TITLE
Updating is impossible because there's not enough space

### ISSUE THREAD

**Issue by FarFarFromH0me** [Hypfer/Valetudo#1623]
## Describe the bug
Just enter the tab to updater and check for updates

## To Reproduce
1. Go to tab Updater
2. Hit button "check for updates"

### Screenshots
![grafik](https://user-images.githubusercontent.com/89612397/198683195-f0dfe434-1856-467c-b6d9-7db134c2e00e.png)

### Vacuum Model
Roborock S7

### Valetudo Version
2022.09.0

## Expected behavior
Update should be small enough to install it

## Additional context
Dont know if its only me or why that happend, always worked in the past

**Comment by Hypfer** [comment]
It is unclear to me how a very specific error message reporting not enough disk space could be considered a bug by anyone.

**Comment by Hypfer** [comment]
Btw, the inbuilt help feature also informs the user about this very issue on some unsupported(!!!!!) robots

![image](https://user-images.githubusercontent.com/974410/198700727-7351f750-30d7-4fe5-a740-3d864fb47b0a.png)

Why are you S7 owners like this
