### ISSUE TITLE
Split map failed

### ISSUE THREAD

**Issue by T-Bone90** [Hypfer/Valetudo#1631]
## Describe the bug
If I want to split rooms I get the error:
"An error occurred while sending command to MapSegmentEditCapability: Split map failed."

### Vacuum Model
Roborock S5

### Valetudo Version
2022.11.0

### Log
2022-11-01T14:07:39.905Z
Info
Miio error response { id: 719, error: { code: -10000, message: 'Split map failed' } }
2022-11-01T14:07:39.909Z
Warn
MapSegmentEditCapabilityRouter: Received error from robot while handling route "/" {
  body: {
    action: 'split_segment',
    segment_id: '16',
    pA: { x: 2355, y: 2250 },
    pB: { x: 2435, y: 2250 }
  },
  message: 'Split map failed'
}

**Comment by Hypfer** [comment]
That message is directly forwarded from and sent by the robots' firmware.


Valetudo can do nothing about that. Try splitting differently
