### ISSUE TITLE
Recommended  Firmware & change of IP

### ISSUE THREAD

**Issue by rassaei** [Hypfer/Valetudo#164]
Is there any documentation of why which firmware version is recommended and which ones are not? I'm asking as dustcloud wiki and valetudo wiki recommend different FWs for the s50.

Also: is the IP of the vacuum set in the images? Why is it in another subnet? (192.168.178.0 vs 192.168.8.0) Is it not set via DHCP?

**Comment by Hypfer** [comment]
192.168.8.1 is the IP of the robot when it's in AP mode. If it's connected to your wifi it picks up an address via DHCP.

Regarding firmwares: I have absolutely no idea. I'm using 1748 on my Gen2 if that helps you.

**Comment by rassaei** [comment]
Thx for the IP info, I was very confused. A lot changed in the last couple of weeks :D

For the firmwares: Also very confusing. I tried to make some sense by checking the wiki diffs but the numbers just change (sometimes they get higher, sometimes lower) without any explanation :D Thx anyway. Maybe someone else can help. @cryptomilk maybe? He did some of the changes.

**Comment by onovy** [comment]
I'm using 1768 and it is just newer bugfix release after 1748. Works fine with Valetudo.
![53431884_3053980667956787_8363077885463887872_n](https://user-images.githubusercontent.com/1649603/56851053-dc697900-690a-11e9-9fef-d80523ff579c.jpg)
![55637084_3084614318226755_6745576949634039808_n](https://user-images.githubusercontent.com/1649603/56851054-dc697900-690a-11e9-8f03-6d96cd76530e.jpg)

**Comment by Hypfer** [comment]
@onovy Can we access those changelogs somehow without using the app?

**Comment by onovy** [comment]
@Hypfer I don't think so. These screenshots are from Facebook roborock group.

**Comment by Hypfer** [comment]
Can you share them somewhere or just add the changelogs to the dustcloud wiki?
