### ISSUE TITLE
Scheduled times based in UTC? Unaffected by Daylight Savings Time, so time jumps forward and back once a year. 

### ISSUE THREAD

**Issue by GarnetSunset** [Hypfer/Valetudo#1646]
## Describe the bug
When daylight savings hits the timer on valetudo doesn't update to 12:30 after daylight savings, and instead says "11:30" which is a bit off of what i wanted, given the timezone is America/New_York

## To Reproduce
Wait for daylight savings time, and the robot goes off an hour early in November, and then back at a normal time in march. 

### Screenshots
![image](https://user-images.githubusercontent.com/13430434/201547006-f2633b16-c6ff-4ddd-b22e-6af4b49b79a7.png)

### Vacuum Model
Roborock S4 Max

### Valetudo Version
2022.10.0

## Expected behavior
When daylight savings hits, it should update with the times

**Comment by Hypfer** [comment]
![image](https://user-images.githubusercontent.com/974410/201548090-8101bcbe-1a6a-4e63-9289-8cfb6a598a58.png)
