### ISSUE TITLE
Unable to enter slashes in MQTT topic prefix

### ISSUE THREAD

**Issue by hessijames79** [Hypfer/Valetudo#1648]
## Describe the bug
Entering slashes in the MQTT topic prefix seems to be blocked.

## To Reproduce
Connectivity -> MQTT -> Field "MQTT topic prefix" -> Enter a topic containing a slash, e. g. 'house/general'
=> All entered characters are accepted except for the slash.

### Vacuum Model
Dreame L10 pro

### Valetudo Version
2022.11.0

## Expected behavior
Slashes are accepted as in previous versions.

**Comment by Hypfer** [comment]
1f06b862 Sören Beye <github@hypfer.de> on 17/11/2022 at 18:26
