### ISSUE TITLE
AutoEmptyDock Control not available on Roborock S7

### ISSUE THREAD

**Issue by mrflo97** [Hypfer/Valetudo#1659]
## Describe the bug

I recently purchased the Auto Empty Dock for my Valetudo S7.
Everything works and has been set up Hardware-Wise, the robot succesfully auto-empties itself.
However, I don't see the option in Valutudo to trigger the auto emptying manually.

Furthermore, trying to trigger the auto empty via MQTT or REST doesn't do anything.
### Screenshots

-
### Vacuum Model

Roborock S7
### Valetudo Version

2022.11
## Expected behavior

The auto emptying is being started

**Comment by Hypfer** [comment]
What made you believe that it would be supported?

![image](https://user-images.githubusercontent.com/974410/204993206-948419dd-8e5d-4428-b11a-bf7c7635b6c2.png)

=> Not a bug
