### ISSUE TITLE
Dreame D9 sensor communication loss

### ISSUE THREAD

**Issue by MonsterEnergy-wtf** [Hypfer/Valetudo#1666]
## Describe the bug
On my Dreame D9 the dust bin was full but Valetudo doesn't recognizes it.
Also the consumables were not marked as used after a couple of runs.
Sound is still there even if I set volume to zero in UI.
Basically it seems that Valetudo cannot get or set settings to my Dreame D9 correctly. Maybe I did something wrong with rooting?!

### Screenshots
![IMG_8148](https://user-images.githubusercontent.com/61805098/206927870-e557c5d6-8a33-4d58-bf2c-4131a5dc36f3.jpg)
![IMG_8149](https://user-images.githubusercontent.com/61805098/206927873-ca91cb2b-3cb4-4b86-bd1b-1f07754c2c6e.jpg)

### Vacuum Model
Dreame D9

### Valetudo Version
2022.11.0

## Expected behavior
Related to dust bin: a warning as I already get them with my two other Roborock S50
Related to consumables: a reduction of lifetime of each consumable after a couple of runs.

## Additional context
All logs from Valetudo are green and no issue was visible there.

**Comment by Hypfer** [comment]
This information is not reported by the Dreame D9 firmware.
