### ISSUE TITLE
map tab js error with basic auth from proxy or web server

### ISSUE THREAD

**Issue by Nebukad93** [Hypfer/Valetudo#169]
When accessing Valetudo outside lan network with a reverse proxy using basic autentication the js map module gets a `HTTP/1.1 401 Authorization Required` code. Possible solution is in this post : 

https://stackoverflow.com/questions/44720004/javascript-es6-modules-not-passing-along-htaccess-basic-authentication/48101267#48101267

To solve this issue, You can add `crossorigin` attribute to the script tag:

```
<script type="module" crossorigin src="./js/mymodule.js"></script>
<script type="module">
    import * as mymodule from "./js/mymodule.js";
    mymodule.runme();
</script>
```

This will inform the browser to make "credentialed" request (request which aware of HTTP cookies and HTTP Authentication information).

**Comment by vene4ka** [comment]
same for `<link rel="manifest" href="/manifest.json">`
