### ISSUE TITLE
No IP address (dhcp) after connecting to network via web UI on the robot' AP

### ISSUE THREAD

**Issue by erichgoldman** [Hypfer/Valetudo#1706]
## Describe the bug

After successfully installing Valetudo, I went to the setup web interface and connected to my wifi network. I got a success message on screen and my robot vacuum (Dreame L10) played the sound for successful connection. However, it never showed up connected to the router for the wifi network selected. When I use the console access and run `ip a` there is no IP address for `wlan0` or `wlan1`.

I tried purposefully making up a fake network and trying to the real network with a purposefully wrong password. In both of those cases, it provides a message that the connection failed. It therefore seems to be successfully connecting to the AP but runs into some problem actually then getting an IP address or something else. I am not sure what to do troubleshoot in this case.

I also tried using both 5ghz and 2.4ghz wifi networks, no difference.

I also tried using the companion app vs web interface, also did not work.

Would like to figure out how to troubleshoot and actually connect to Valetudo from my network.

## To Reproduce

1. Complete Valetudo setup using [guide for dreame robots](https://valetudo.cloud/pages/installation/dreame.html#uart)
2. Connect to AP on the robot 
3. Go to web interface (e.g., http://192.168.5.1/)
4. Sometimes it shows list of APs, sometimes it doesn't
5. Use the manual network and password entry at the bottom of the page.
6. Connect and receive confirmation in web UI and also hear robot play the audio file for successful connection.
7. Attempt to find the robot vaccuum via the router management and fail to see it
8. Check local settings-->
9.  `ip a` <-- no ip address, only showing IPv6 - shows a `wlan0` an `wlan1`
10. Try to get a dhcp address by running commands like: `udhcpc -i wlan0`
11. Review log, `cat c` notice items that may be issue, see below
12. See a log saying `Valetudo can be reached via: valetudo-distantfavorabletiger.local`, but this never worked

Other commands tried:
`/usr/bin/wifi_connect [ssid] [password]` <-- reports `{"ret":"ok"}` even if I purposefully type wrong password

`cat`ed `/data/config/miio/wifi.conf` and it shows the correct SSID, etc.

### Screenshots
Dump of `cat /data/log/wifi.log`
```shell
Thu Jan 1 00:14:50 UTC 1970 finish wlan0 AP ssid=dreame-vacuum-p2029_miapXXXX
Thu Jan 1 00:14:50 UTC 1970 set empty to /data/config/ava/iot.flag
Thu Jan 1 00:16:43 UTC 1970 start station mode
Thu Jan 1 00:16:43 UTC 1970 start wlan0 STATION mode
Thu Jan 1 00:16:45 UTC 1970 finish wlan0 STATION mode
Thu Jan 1 00:16:53 UTC 1970 config net success
Thu Jan 1 00:18:42 UTC 1970 start wlan0 AP mode
Thu Jan 1 00:18:45 UTC 1970 finish wlan0 AP ssid=dreame-vacuum-p2029_miapXXXX
Thu Jan 1 00:18:45 UTC 1970 set empty to /data/config/ava/iot.flag
Thu Jan 1 00:19:17 UTC 1970 add device(XXXXXX) mac:XXXXX ip:192.168.5.100
Thu Jan 1 00:19:42 UTC 1970 start station mode
Thu Jan 1 00:19:42 UTC 1970 start wlan0 STATION mode
Thu Jan 1 00:19:44 UTC 1970 finish wlan0 STATION mode
Thu Jan 1 00:19:52 UTC 1970 config net success
Thu Jan 1 00:22:02 UTC 1970 restart wifi application
Thu Jan 1 00:23:06 UTC 1970 config net by router
Thu Jan 1 00:07:01 UTC 1970 start wlan0 AP mode
Thu Jan 1 00:07:04 UTC 1970 finish wlan0 AP ssid=dreame-vacuum-p2029_miapXXXX
Thu Jan 1 00:07:04 UTC 1970 set empty to /data/config/ava/iot.flag
Thu Jan 1 00:07:30 UTC 1970 add device(XXXXXXX) mac:XXXXXXX ip:192.168.5.100
Thu Jan 1 00:08:10 UTC 1970 ssid="" bssid="" password is wrong
Thu Jan 1 00:08:10 UTC 1970 config net failed, restart ap
Thu Jan 1 00:08:12 UTC 1970 start wlan0 AP mode
Thu Jan 1 00:08:14 UTC 1970 finish wlan0 AP ssid=dreame-vacuum-p2029_miapXXXX
Thu Jan 1 00:08:14 UTC 1970 set empty to /data/config/ava/iot.flag
Thu Jan 1 00:08:42 UTC 1970 start station mode
Thu Jan 1 00:08:42 UTC 1970 start wlan0 STATION mode
Thu Jan 1 00:08:44 UTC 1970 finish wlan0 STATION mode
Thu Jan 1 00:08:52 UTC 1970 config net success
Thu Jan 1 00:19:02 UTC 1970 restart wifi application
Thu Jan 1 00:25:02 UTC 1970 start wlan0 failed
Thu Jan 1 00:25:02 UTC 1970 restart wifi driver
```

### Vacuum Model

Dreame L10

`DreameL10ProValetudoRobot`

### Valetudo Version

2023.01.0

`Commit ID: 3d6ef60758077fc0623474721031c7493e3 `               

`Firmware Version: 1138`    

## Expected behavior

After successfully connecting to the wifi network, it should grab an IP address via DHCP and then I should be able to login to the interface and use it.

**Comment by Hypfer** [comment]
I think what happend here is that you got a bit misled by the voice clip of the robot telling you that it was connected successfully.
As far as I understand it, this check tries to reach the cloud and returns successfully if that's possible. However, in our case, the cloud is on the robot itself, meaning that the check can *always* reach the cloud even if actually no network connection was established.


Dreames are known for not playing well with some routers running OpenWRT and/or Legacy rates being either enabled or disabled. If you have such a toggle in your Wi-Fi AP, try changing it.

Also, make sure that you can see your SSID in the Wi-Fi Scan results when provisioning using the Webinterface.

If that doesn't solve the issue, as a last resort, try a different Wi-Fi AP

**Comment by erichgoldman** [comment]
> As far as I understand it, this check tries to reach the cloud and returns successfully if that's possible. However, in our case, the cloud is on the robot itself, meaning that the check can always reach the cloud even if actually no network connection was established.

If I type in the wrong password and it doesn't connect to the network, the robot plays recording:

`Unable to connect to the wifi network, please check wifi password and try again later.`

If I type it in correctly, then it does connect and gives the positive message. It would seem that is is successfully interacting with the router. Also, it turns off the robot's AP. This check is actually based upon hitting the server and nothing to do with the wifi network?

> Also, make sure that you can see your SSID in the Wi-Fi Scan results when provisioning using the Webinterface.

I reran it. I did not see the 5ghz network, but it did list the 2.4ghz network. It did connect successfully, but same issue.

>  Legacy rates being either enabled or disabled.

Can you help me understand what type of settings I am looking for? I am using vendor firmware on a netgear router.

**Comment by erichgoldman** [comment]
Follow up: After repeating this a few times it did finally get an IP address on 2.4ghz network. Unsure what happened the first few times.

**Comment by Hypfer** [comment]
Huh, strange. Happy to hear that it works now at least :)

Which model of netgear router is it?
Just so that we have that information in case it might be helpful in the future

**Comment by Unreeling8562** [comment]
Hi, I have the same problem, how can I enable the AP from the robot again so I can try to reconnect to the WiFi?

OPNSense router with VLAN IoT network without internet access.

**Comment by stefanmd023** [comment]
> Hi, I have the same problem, how can I enable the AP from the robot again so I can try to reconnect to the WiFi?
> 
> OPNSense router with VLAN IoT network without internet access.

https://www.google.com/search?q=reset+wifi+vacuum+robot+YOURROBOTVENDOR+YOURROBOTMODEL
