### ISSUE TITLE
oddly rotated map

### ISSUE THREAD

**Issue by Technikte** [Hypfer/Valetudo#171]
Hi,
like you see in the first screenshot the map is somewhat oddly slightly rotated after I done 
`echo -n "1" > /mnt/data/rockrobo/lab.cfg` and manually turn off/on the robot to reboot it

Roborock Gen2
Firmeware: 3.3.9
Firmware build: 001768
Valetudo: 0.3.0

![Unbenannt](https://user-images.githubusercontent.com/49494924/55903960-06aefd00-5bcf-11e9-8d5a-bd20c3aa6a58.PNG)

![schema](https://user-images.githubusercontent.com/49494924/55904503-4c1ffa00-5bd0-11e9-8444-a3b6921aee78.png)

I would not even mind if the map is 180 rotated but like this I cant really save zones.
Is there anything that I can do to reset the map or just to correct the angle ?

**Comment by cryptomilk** [comment]
It should fix the rotation on the next run, if not you can reset the map with:

`mirobo raw-command reset_map`

**Comment by Technikte** [comment]
> 
> 
> It should fix the rotation on the next run, if not you can reset the map with:
> 
> `mirobo raw-command reset_map`

Wow, that was a quick answer..can I trigger the map reset somehow directly on the robot itself via ssh ?

**Comment by cryptomilk** [comment]
I'm sure you can if you install python3-miio :-)

**Comment by Technikte** [comment]
It seems like a rerun has purged the map and now a map at correct angle got generated.
Fixed, I will close the issue.
