### ISSUE TITLE
Problem with mapfunction

### ISSUE THREAD

**Issue by marooram** [Hypfer/Valetudo#172]
I followed your wiki and installed valetudo onto the roborock (2nd gen with your recommended FW 1748). Currently I never get a map (all other functions work well), also tested "cleaning" and "restart robot" as said in the wiki. I only see the big robot.. what could be the problem and how could I solve it?

**Comment by reaper7** [comment]
I noticed something like that yesterday
but after _sudo reboot_ the map came back

**Comment by CrazYoshi** [comment]
> I followed your wiki and installed valetudo onto the roborock (2nd gen with your recommended FW 1748). Currently I never get a map (all other functions work well), also tested "cleaning" and "restart robot" as said in the wiki. I only see the big robot.. what could be the problem and how could I solve it?

I have the same issue with my gen1 rockrobo. In the previous version of Valetudo it works correctly but after the update to 3.0 map is always empty.

**Comment by tmrealive** [comment]
I have the same problem when upgrading to 0.3.0, gen1

**Comment by hyperbit00** [comment]
same problem here, works like a charm with V0.2.0, with 0.3.0 only a big robot

Try'd it with compiling v0.3.0 by my self and with installing rooted firmware with integrated Valetudo (wiki instructions)

**Comment by vevsvevs** [comment]
Guys, check your `/etc/hosts` and `/etc/rc.local` files, they must contain strings from this [deployment examples](https://github.com/Hypfer/Valetudo/tree/master/deployment/etc). Also remove `mapSettings` entries from `valetudo.conf`.

**Comment by hyperbit00** [comment]
> Guys, check your `/etc/hosts` and `/etc/rc.local` files, they must contain strings from this [deployment examples](https://github.com/Hypfer/Valetudo/tree/master/deployment/etc). Also remove `mapSettings` entries from `valetudo.conf`. And don't forget to reboot your vacuum after all ;)

that was the solution

**Comment by marooram** [comment]
> > Guys, check your `/etc/hosts` and `/etc/rc.local` files, they must contain strings from this [deployment examples](https://github.com/Hypfer/Valetudo/tree/master/deployment/etc). Also remove `mapSettings` entries from `valetudo.conf`. And don't forget to reboot your vacuum after all ;)
> 
> that was the solution
> any solution to integrate it to IOBROKER? (maybe iframe?)

Mayybat following could help you:
https://github.com/MeisterTR/ioB-scripts.git

**Comment by marooram** [comment]
> Guys, check your `/etc/hosts` and `/etc/rc.local` files, they must contain strings from these [deployment examples](https://github.com/Hypfer/Valetudo/tree/master/deployment/etc). Also remove `mapSettings` entries from `valetudo.conf`. And don't forget to reboot your vacuum after all ;)

Worked for me too, thank you!

**Comment by roflcoopter** [comment]
> > Guys, check your `/etc/hosts` and `/etc/rc.local` files, they must contain strings from these [deployment examples](https://github.com/Hypfer/Valetudo/tree/master/deployment/etc). Also remove `mapSettings` entries from `valetudo.conf`. And don't forget to reboot your vacuum after all ;)
> 
> Worked for me too, thank you!

Where is the valetudo.conf located? Or do you mean config.json?

**Comment by reaper7** [comment]
/etc/init

**Comment by vevsvevs** [comment]
> Where is the valetudo.conf located? Or do you mean config.json?
Oh, of course i meant `/mnt/data/valetudo/config.json`, sorry :) Post corrected.
