### ISSUE TITLE
Network Advertisement config page shows "Error loading Network Advertisement configuration"

### ISSUE THREAD

**Issue by ejohb** [Hypfer/Valetudo#1720]
## Network Advertisement config page shows "Error loading Network Advertisement configuration"
Network Advertisement config page shows "Error loading Network Advertisement configuration"

## To Reproduce
Visit http://[robot-host]/#/options/connectivity/networkadvertisement

### Screenshots

![image](https://user-images.githubusercontent.com/30390944/221235627-1bfc5340-dcac-4cab-9b28-07142cf6f780.png)

### Vacuum Model
This is happening on 2 different S5 Maxes

### Valetudo Version
Both robots running 2023.02.0 

## Expected behavior
Settings page should load

**Comment by Hypfer** [comment]
Please check the browser devtools console and network tab for any error messages.
Refreshing the page also often helps

**Comment by ejohb** [comment]
The logs implied the request was blocked by something. I disabled my Ad Blocker (Ad Blocker Ultimate) and it started work.

Sorry for the false alarm.

**Comment by Hypfer** [comment]
Sounds like the "advertisement" in the url might've triggered it.

OT, but I can recommend ublock origin as the only trustworthy adblocker
https://github.com/gorhill/uBlock
