### ISSUE TITLE
Map lost after reboot

### ISSUE THREAD

**Issue by xoxys** [Hypfer/Valetudo#182]
The map is completely lost in UI after every reboot of the device. Is this expected?

Using v0.3.0

**Comment by cryptomilk** [comment]
Yes, `mirobo raw-command set_lab_status 1` needs to be run to tell the robot to not remove maps after a restart. I think we should add an option to Valetudo to enable it. Like Settings -> Maps to enable/disable lab mode or reset the map.

**Comment by xoxys** [comment]
Thanks. That helps a lot. What about adding this to an FAQ in the meantime?

**Comment by cryptomilk** [comment]
Feel free to do so, ask @Hypfer for edit rights.

**Comment by Hypfer** [comment]
The Wiki is open 👍

**Comment by xoxys** [comment]
Great!

**Comment by xoxys** [comment]
Done

**Comment by xoxys** [comment]
@cryptomilk @Hypfer 
Sadly `mirobo` commands does not work anymore. I've tried with `mirobo discover` and `mirobo raw-command` with no luck:

```
$ mirobo -d discover
INFO:miio.vacuum_cli:Debug mode active
INFO:miio.discovery:Discovering devices with mDNS, press any key to quit...
WARNING:zeroconf:Exception occurred:
Traceback (most recent call last):
  File "/home/srvmaster/roborock/lib64/python3.6/site-packages/zeroconf.py", line 2101, in send
    bytes_sent = s.sendto(packet, 0, (addr, port))
PermissionError: [Errno 1] Operation not permitted
```

**Comment by cryptomilk** [comment]
You need to specify the ip and token! See `mirobo --help`

**Comment by xoxys** [comment]
I've done this by ENV variables. Tried also with CLI options with the same result.

**Comment by cryptomilk** [comment]
Works fine for me.

```
  krikkit  asn  (e) venv  ~  workspace  rockrobo  miio  mirobo status
State: Charging
Battery: 100 %
Fanspeed: 60 %
Cleaning since: 0:05:15
Cleaned area: 3.3375 m²
```

**Comment by xoxys** [comment]
Strange... which firmware you are using?

**Comment by xoxys** [comment]
And you are not in AP mode right?

**Comment by cryptomilk** [comment]
v1748. However I don't think that matters, if you can ping the robot then probably the token is wrong. My robot is connected to my wifi network.

**Comment by cryptomilk** [comment]
If you can understand `strace` output or wireshark those are you're friends :-)

**Comment by xoxys** [comment]
I've used the token displayed in Valetudo UI. Robot is pingable and controllable through Valetudo UI

**Comment by jowlo** [comment]
Just to chip in here, have you tried running your `mirobo` command as root?

The python error you pasted is an error in the zeroconf send function. I do not see why this should give an error, but i do not think this is in any way related to anything running on the robot.

**Comment by xoxys** [comment]
@jowlo same

**Comment by cryptomilk** [comment]
Your firewall might also block something ...

**Comment by xoxys** [comment]
Yeah I've checked this too... Firewall is set to IPv4* any any...

**Comment by xoxys** [comment]
no idea whats wrong...

**Comment by jowlo** [comment]
Well, let's find out if your packet actually gets send:

 * Open terminal and run `tcpdump` on port `5353` (mDNS) and keep open:
```
sudo tcpdump -n port 5353
```
* Open a second terminal and execute your mirobo commands (as `root` to tackle one problem at a time).
```
sudo mirobo -d discover
```

`tcpdump` should show your packages originating from your IP to the IP of the robot - and possibly other mDNS traffic in your network.

**Comment by xoxys** [comment]
@jowlo Hell.... it's some multicast fuckup with pfsense/unif switches and multiple vlans....

**Comment by xoxys** [comment]
It is temporary working now.... Multicast is a piece of shit.

**Comment by xoxys** [comment]
@jowlo Anyway, thanks for pointing me in this direction

**Comment by xoxys** [comment]
I think I finally got it working. Last bastion was local iptables:

# allow mdns 
iptables -I INPUT -p udp --dport mdns -d 224.0.0.251 -j ACCEPT
iptables -I OUTPUT -p udp --dport mdns -d 224.0.0.251 -j ACCEPT

# allow other necessary port
sudo iptables -I OUTPUT -p udp --dport 54321 -j ACCEPT

Now connections with `mirobo` works again.
