### ISSUE TITLE
Map partially drawn (valetudo 0.3.1)

### ISSUE THREAD

**Issue by OhSoGood** [Hypfer/Valetudo#184]
In the same room where valetudo is partially or not cleaning (see issue #183 ), I've run the robot while I was in the room observing it. I was surprised to see that the map drawn on the web interface, already convoluted (compared to how the robot usually runs), only partially shows all the twists and turns made by the robot. Notably, it turned at least 7 or 8 times around the obstacle highlighted in red, while the map does not show it. Similarly, in the green rectangle, the map shows only two passes while the robot has passed at least 4 or 5 times. Here is the valetudo map: https://imgur.com/a/NbEOQVk

Any idea?

My S50 is running 3.3.9_1748, with valetudo 0.3.1
The room is a bedroom, with a central bed (20 cm from the floor, plenty of place for the robot to go under) and a table, so nothing extraordinary.

**Comment by Hypfer** [comment]
Honestly I doubt that this is related to the draw logic
