### ISSUE TITLE
Can't connect to MQTT with DNS CNAME record

### ISSUE THREAD

**Issue by scolby33** [Hypfer/Valetudo#1858]
## Describe the bug

When configuring the MQTT host to a domain name that has a CNAME record, Valetudo cannot connect to MQTT.

## To Reproduce

1. Configure DNS records like so:
    - `foo.example.net A 192.168.1.1`
    - `mqtt.example.net CNAME foo.example.net`
2. Configure Valetudo to connect to the MQTT broker at `mqtt.example.net`

### Screenshots

N/A

### Vacuum Model

Dreame Z10 Pro

### Valetudo Version

2023.03.0

## Expected behavior

The MQTT client should follow the CNAME chain and connect to 192.168.1.1

**Comment by Hypfer** [comment]
Can't reproduce
