### ISSUE TITLE
Map remains empty (valetudo 0.3.1 v11_001768.fullos.pkg/v11_001720.fullos.pkg)

### ISSUE THREAD

**Issue by tx00** [Hypfer/Valetudo#186]
**System**
fw: 3.3.9
Valetudo: 0.3.1

**Tested with:**
fwb: 001768 (v11_001768.fullos.pkg)
fwb: 001720 (v11_001720.fullos.pkg)

Data seems generated/collected as expected in `/mnt/data/rockrobo/rrlog` wifi mode: client as indicated by the FAQ, works as expected.
No map displayed. 
Could be related to #184

**Comment by cryptomilk** [comment]
Did you follow the guide in the wiki to build the image?

**Comment by cryptomilk** [comment]
https://github.com/Hypfer/Valetudo/wiki/FAQ

**Comment by tx00** [comment]
Rebuilding the image fixed the problem.

**Comment by Hypfer** [comment]
This needs to stop.
