### ISSUE TITLE
Custom Icons for Valetudo Capabilities and functionality

### ISSUE THREAD

**Issue by Hypfer** [Hypfer/Valetudo#1862]
At the moment, Valetudo uses the Icons included in the MUI framework for everything. While they are great, they are also generic Icons that don't always really fit the application.

Take for example the controls on the home page:

<img src="https://github.com/Hypfer/Valetudo/assets/974410/dd13b8a8-1c8b-4f7b-9ed8-d6d3dfa9cf3a" height=500></img>

Out of all these icons, only the fan one actually fits the purpose. All other icons range from "kinda maybe fitting" for Auto-Empty and Water Grade to "essentially random" for the operation mode.

It's a similar story in the options menu:

![image](https://github.com/Hypfer/Valetudo/assets/974410/020c2241-28ab-4c47-acaa-7c42020b5197)

Obstacle avoidance kinda makes sense but what are those carpet sensor waves about?

Unfortunately, designing nice looking icons for all the capabilities that also fit with the overall style of MUI is beyond my skillset.

Thus, help by a pro would be greatly appreciated :)

**Comment by xuefer** [comment]
and icons for different obstacle types
