### ISSUE TITLE
"/api/current_status" does not show "human_error" anymore

### ISSUE THREAD

**Issue by TheMicroDevil** [Hypfer/Valetudo#187]
Was wondering why my tools do not show error messages anymore and just realized that "human_error" is now missing in v0.3.1
`{"msg_ver":8,"state":12,"battery":100,"clean_time":40,"clean_area":705000,"error_code":9,"map_present":1,"in_cleaning":1,"fan_power":38,"dnd_enabled":0,"human_state":"Error"}`

**Comment by Hypfer** [comment]
https://github.com/Hypfer/Valetudo/blame/3594a712eebc12be5d33d760d22f373269825b3b/lib/miio/Vacuum.js#L441

Yep. Thats just stupid

Will be fixed in the next release. Thanks for reporting
