### ISSUE TITLE
MQTT changes in home assistant

### ISSUE THREAD

**Issue by Hacki1111** [Hypfer/Valetudo#1877]
## Describe the bug

In fact this is not a bug but the Home Assistant 2023.8 update introduced a breaking change related to the naming of mqtt devices. This change produces some warning messanges in home assistant like:

> MQTT device name is equal to entity name in your config

> MQTT entity name starts with the device name in your config

> Please correct your configuration. The entity name will be set to `null`

## To Reproduce

Use MQTT and an updated version auf Home Assistant
### Vacuum Model

Roborock S5 but other models as well
### Valetudo Version

2023.8

**Comment by Hypfer** [comment]
Duplicate of https://github.com/Hypfer/Valetudo/issues/1847
