### ISSUE TITLE
WiFi names displayed incorrectly when SSID contains unicode

### ISSUE THREAD

**Issue by kiler129** [Hypfer/Valetudo#1923]
## Describe the bug
When setting up the robot initially, a list of WiFi networks is displayed. That list breaks/doesn't display names decoded when unicode characters are present in SSID.

## To Reproduce
1. Setup wifi name containing unicode, e.g. `🏠WiFi`
2. Install fresh Valetudo instance
3. Open web interface
4. The interface will display list of WiFi networks; click refresh as needed

### Screenshots
This is a real network I own:
![photo_2023-11-11 00 36 59](https://github.com/Hypfer/Valetudo/assets/1227834/9ec7c801-8c7e-433a-9ddc-fb4e3bebfb40)

This one appeared on the list, but it seems to only have nullbytes (hidden WiFi?):
![photo_2023-11-11 00 36 56](https://github.com/Hypfer/Valetudo/assets/1227834/1ffed499-2485-4eca-b27f-417ad2ef4189)

### Vacuum
Dreame L10S Ultra

### Valetudo Version
2023.10.0 (fea89f690396727c33460297211e7732270bbd9e)

## Expected behavior
Network names should display proper unicode characters.

**Comment by Hypfer** [comment]
![image](https://github.com/Hypfer/Valetudo/assets/974410/62c93bd1-c1a1-4b6d-82c5-de02ed7fbba7)

I think this sums up everything there is to say about the issue.
My enterprise-grade Wi-Fi APs don't even allow for an SSID with an Emoji in it. And why would they? It's just asking for trouble.

I'm sure one could go down this rabbit hole trying to figure out where exactly which piece of software breaks in what way and what could be done about it, but.. why would you do that?

The failure mode is a safe one.
It still works; it just looks a bit weird.
And if you're unhappy with that, just don't use non-ascii SSIDs.

I'm also quite sure that whatever would come out of that investigation would complicate the code greatly.
