### ISSUE TITLE
Latest working firmware version? (latest seems to be v11_001834)

### ISSUE THREAD

**Issue by HA-TB303** [Hypfer/Valetudo#196]
Hi,

There is a version v11_001834.fullos.pkg now. Does anyone know what is the latest and greatest working version number?

**Comment by BenRoe** [comment]
https://github.com/dgiese/dustcloud/wiki/Xiaomi-Vacuum-Firmware#tested-firmware

**Comment by HA-TB303** [comment]
Thanks, but those last 3 additions on the dustcloud documentation came from me ;)

I wasn't planning on being the testing guinea pig al the time :)

**Comment by rand256** [comment]
For now 1834 is latest of available firmwares as far as I see. However it writes way too many debug logs and wastes a lot of CPU for it. The same is true for 1832, 1830 and (a bit less for) 1826. The latest (by date) firmware without insane debugging is 1820.

**Comment by cryptomilk** [comment]
v18xx is beta software! It has never been rolled out officially. The latest available firmware seems to be v1768.

**Comment by rand256** [comment]
So beta firmware is not a firmware?

**Comment by cryptomilk** [comment]
Well you can run it but don't expect it to be bug free ...

**Comment by rand256** [comment]
I don't expect officially rolled out firmware being bug free too, obviously.

The question of this topic didn't mention beta or release channel of distribution, though, it was asked only which firmware is the latest, already referring to 1834.

**Comment by HA-TB303** [comment]
Well, I wanted to know what is the latest WORKING version ;)

**Comment by rand256** [comment]
Even 1834 is WORKING, though probably worse than it could.

I personally use 1820 for the last few weeks. Latest official release 1768 should also be fine.

**Comment by HA-TB303** [comment]
Thx, I’ll stick to 1820 then.
