### ISSUE TITLE
Vacuum not moving on map

### ISSUE THREAD

**Issue by cnrd** [Hypfer/Valetudo#215]
Hi

Valetudo 0.3.1
Chrome and iOS Safari (iOS 12.2)

The vacuum is not moving on the map while cleaning, the line is still being drawn. (The vacuum drawing is turning on the spot at the dock).

![Screenshot 2019-05-07 at 12 17 20](https://user-images.githubusercontent.com/5996053/57292489-1b918a00-70c2-11e9-9acc-0ae9e332536c.png)

**Comment by Hypfer** [comment]
Is this still happening?

**Comment by VirtualGit** [comment]
Hi, I don't know if it is related, but I experiment the same issue through an apache proxy. 
Here is my conf :

I have a public dns pointing my public IP. An apache server is serving the robot web UI through a simple proxy configuration :

```
ProxyPass /robot http://192.168.xxx.xxx
ProxyPassReverse /robot http://192.168.xxx.xxx
```
(192.168.xxx.xxx si the robot IP)
I access the robot UI through : http://mydns.net/robot

The UI seems globally ok, except the realtime map update.

I guess the issue may comes from a websocket trying to connect to the root server path, in vacuum-map.js :
`ws = new WebSocket(`${protocol}://${window.location.host}/`);`

Here is two screenshots of firefox.
From http://192.168.xxx.xxx/ (no problem, mas is updated in real-time) :
![valetudo1](https://user-images.githubusercontent.com/14853220/63921554-4d4ca900-ca43-11e9-9a64-bdfb5f45bc5f.png)
From http://mydns.net/robot/ (problem, map is not updated) :
![valetudo2](https://user-images.githubusercontent.com/14853220/63921578-59d10180-ca43-11e9-86c2-273ffcfd6174.png)

Switching screen to home, and back to map, update the map (lines) but the robot still don't move. 

Valetudo 0.4.0

**Comment by acht** [comment]
I have the same issue with Valetudo 0.4.0 whenever the network latency increases. In the local network it works fine from remote the map update stops after some seconds or do not update at all.

**Comment by Hypfer** [comment]
Closing this because it's very old.

If it is still happening please open a new issue
