### ISSUE TITLE
Map generation issue/question

### ISSUE THREAD

**Issue by cherokee93** [Hypfer/Valetudo#216]
![image](https://user-images.githubusercontent.com/12370126/57296233-c9099b00-70cc-11e9-901a-bd50967ba387.png)
Hello!
I'm new, I have the robot since yesterday and don't really know where to find the answer.

The above is my map, any idea why it is not generating? Robot is cleaning right now, but no map is being generated. On Xiaomi App I can see the map (no hosts entries) and everything.
Maybe something related to the map png feature that got removed?
I'm sorry if it's not an issue

Thanks for this software, love Valetudo ❤️

**Comment by Hypfer** [comment]
**(no hosts entries)**

**Comment by cherokee93** [comment]
🤦‍♂ I removed host entries because I couldn't use Valetudo, it loaded and loaded and loaded. 

Ok, i'll re-add hosts entries and retry then.  🤣 
Sorry for bothering. Thanks

**Comment by cherokee93** [comment]
Ok now Valetudo  works perfectly ✔️ 
But (rightfully) Xiaomi app is not working. Is there any way to make it work? Or is something I need to give up?

**Comment by rand256** [comment]
Yes, you need to choose whether you use Valetudo OR Xiaomi app, not both.
