### ISSUE TITLE
Select multiple zones

### ISSUE THREAD

**Issue by Luftloch80** [Hypfer/Valetudo#220]

**Comment by Luftloch80** [comment]
Is it possible to select multiple Zones for cleaning within the webinterface?
I have Single Zones for kitchen living room and so on. 
I Want to clean several Zones from the Web Ui without creating Zones for each possible configuration 
Thx

**Comment by BenRoe** [comment]
You can check multiple zones in the zone tab and then press the clean zone button.

**Comment by rand256** [comment]
As far as I see, there's no way to "check" zones in the zone tab, you can only edit them from there, one by one.

**Comment by hal295** [comment]
Hi, from Valetudo version 0.4.0 isnt possible to select multiple zones from zones tab like in prev version.
Please can somebody make this feature again? I am cleaning often several rooms/zones at time. Thanks!

**Comment by ppisljar** [comment]
i'll probably take a look at this

**Comment by Markus-** [comment]
Anything new?

**Comment by rand256** [comment]
<details>
  <summary>This is how it looks in Valetudo RE</summary>

![qscr](https://user-images.githubusercontent.com/30267719/67139299-585bd280-f257-11e9-8688-7d684d90a3d5.png)

</details>
