### ISSUE TITLE
zoned cleaning state not sent to mqtt

### ISSUE THREAD

**Issue by dlashua** [Hypfer/Valetudo#224]
When performing a zoned cleaning, mqtt data at /valetudo/rockrobo/state.cleaning remains "false".

**Comment by Technikte** [comment]
Same here, also the while its returning home its says Stopped as Status. I am think this pr would fix it https://github.com/Hypfer/Valetudo/pull/178 but I am not quite sure.

**Comment by pszafer** [comment]
Yes. New PR will support all states same way as original vacuum software.

**Comment by dlashua** [comment]
This seems to be fixed.
