### ISSUE TITLE
Impossible to run self compiled version

### ISSUE THREAD

**Issue by StevenWas** [Hypfer/Valetudo#232]
When using any recent Ubuntu Version to compile Valetudo the binary will not run as the robot's GLIBC Version is too old:

`./valetudo: relocation error: ./valetudo: symbol _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference`

**Comment by matthiasharrer** [comment]
Is there anything we can do about this?

**Comment by leonardpitzu** [comment]
yes - force pkg ver 4.3.6 in the package

"pkg": "^4.3.6" -> "pkg": "4.3.6"
