### ISSUE TITLE
Zone Cleanup is Vertically Flipped

### ISSUE THREAD

**Issue by dlashua** [Hypfer/Valetudo#237]
When using zoned cleanup via MQTT:

/valetudo/rockrobo/custom_command
{
  "command": "zoned_cleanup",
  "zone_ids": [
    "kitchen"
  ]
}

Occasionally the area to be cleaned will be vertically flipped on an axis with the dock. In other words, if there is an area of my house below (on the map) the dock, the zoned cleanup will send the vacuum to an area the same shape and horizontal location as intended, but above the dock instead.

This doesn't seem to happen if I use the Zone selector from within Valetudo and pick the zone. Additionally, I can stop the zoned_cleanup activity and then restart it using MQTT and it will then pick the correct area.

Firmware 3.3.9
Build 001748
Valetudo 0.3.1 (built from latest git repo)
Gen 2 Roborock S5

**Comment by matthiasharrer** [comment]
@aprosvetova This is still the known issue with the mutable config or should this be fixed?

**Comment by aprosvetova** [comment]
@matthiasharrer it's known but still not fixed. @Hypfer wanted to refactor Vacuum.js code so it makes up a new object with coords instead of using config object directly.

**Comment by dlashua** [comment]
Since this commit ( https://github.com/Hypfer/Valetudo/commit/de0a28db98d577746ca7bcc185083035dafbdeb1 ) I have not seen zones vertically flipped any more. It's only been a few days and I've not used the feature much (since the vertically flipped clean up doesn't really do what it's supposed to). But I'll be ramping up my usage of this feature again to see if this resolves the issue.

**Comment by dlashua** [comment]
I was overly hopeful. This is still an issue.

**Comment by Hypfer** [comment]
Are you sure about that? Do the zones in the configuration file change?

**Comment by dlashua** [comment]
The zones in the configuration file don't seem to change... but... here's what I did...

Yesterday, downloaded new Valetudo source from git, built, and installed on vacuum.
Added 3 zones for testing.
Tested and they worked fine multiple times.

Today, did nothing but go to "Zones" and choose my zone. The zone was vertically flipped resulting in my vacuum attempting to clean an area that is not even accessible and is outside of my house.

**Comment by Hypfer** [comment]
So there was a restart between those cleanups?

**Comment by Hypfer** [comment]
Can't reproduce. :/

Also, I don't see anything in the code that could still be causing this issue.

**Comment by dlashua** [comment]
I don't remember a restart, but it's possible. Does a restart have the potential of changing coordinates?

**Comment by Hypfer** [comment]
Is this still happening? I wasn't able to reproduce it
