### ISSUE TITLE
no Mapupdate by using Reverseproxy (Valetudo 0.3.1)

### ISSUE THREAD

**Issue by gary822** [Hypfer/Valetudo#240]
when you are using an Apache2 ProxyPass with HTTPS there are no live map update.
I'm using the following config:

`<VirtualHost *:80>
ServerAdmin webmaster@localhost
DocumentRoot /var/www/

#HTTP zu HTPPS umschreiben
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

#staubi
ProxyPass "/staubi" "http://192.168.1.6"
ProxyPassReverse "/staubi" "http://192.168.1.6"`

I do not know if the problem is the HTTPS or the proxy.

**Comment by r1sim** [comment]
Map updates are send to the web interface using websockets.
Your apache2 configuration only handles http/https requests. To get the map working you also need to handle ws/wss requests.
I have never done this with apache2 but this might work for you: https://stackoverflow.com/a/43592531

There is also an example configuration for nginx in the FAQs (without ssl but that shouldn't matter):
https://github.com/Hypfer/Valetudo/wiki/FAQ#how-can-i-add-password-authentication
