### ISSUE TITLE
How can I download a binary?

### ISSUE THREAD

**Issue by Wolf6660** [Hypfer/Valetudo#249]
Hello,

I do not understand how can I download this file?

Quote:
Download the latest valetudo binary from https://github.com/Hypfer/Valetudo/releases

Can you give me a example?

thanks

**Comment by fvollmer** [comment]
![grafik](https://user-images.githubusercontent.com/16699443/58809516-639dc100-861c-11e9-96e7-3aec6edb5cbf.png)

**Comment by rand256** [comment]
The only issue it's quiet old version.  You can build yourself, see [deployment](https://github.com/Hypfer/Valetudo/tree/master/deployment).
It requires you to have a linux shell, though. But nowadays even in windows-10 you can install linux subsystem.
