### ISSUE TITLE
Start Manual Control immediately terminates on first start

### ISSUE THREAD

**Issue by Yky** [Hypfer/Valetudo#26]
Precondition: 
The v2 robot is in the dock

Problem description:
If I start manual control, the button stop manual control becomes active only for a split second, then the start manual control button becomes active again. 

The robot says "using remote controls" followed by "finished using remote controls" right afterwards. 

If I repeat this process a few times at some point the robot starts the fans and does not "finish using remote controls" immediately, such that manual control is possible. 

Expected behavior:
Keep manual controls running after starting them until "stop manual control" is clicked

**Comment by FelixUster** [comment]
I can confirm this bug for Gen 1

**Comment by Hypfer** [comment]
#192
