### ISSUE TITLE
Feature Request: Report dustbin removed/inserted through mqtt.

### ISSUE THREAD

**Issue by cnrd** [Hypfer/Valetudo#264]
Hi

So the vacuum (at least S50) has the voice saying dustbin removed / inserted and refuse to start unless there is a dustbin.

That got me thinking that we should probably be able to pull that information from the robot?

One use case would be to nag me to empty it, or even make it go to the trashcan wait for me to remove and insert the dustbin and then automagically go back to the dock with no other commands.

I have been looking for somewhere to pull that information but I haven't found it, maybe there are someone more knowledgeable about the inner workings that can implement this?

**Comment by Hypfer** [comment]
https://github.com/Hypfer/Valetudo/issues/133
