### ISSUE TITLE
How to build on docker?

### ISSUE THREAD

**Issue by bruvv** [Hypfer/Valetudo#266]
I have a macbook but it doesn't understand pkg. So I wanted to run docker but where to begin?

Or perhaps have travis upload to github with pre release or beta attached :) ?
https://docs.travis-ci.com/user/deployment/releases/

**Comment by Skeletorjus** [comment]
Hi!

I just made a Dockerfile that does this:

```
FROM ubuntu:14.04

# Build:
# docker build -t valetudo-compiler .

# Copy binary to current directory:
# docker run --rm -it -v $(pwd):/host valetudo-compiler bash -c "cp /Valetudo/valetudo /host && chown $(id -u):$(id -g) /host/valetudo"

RUN apt-get update \
; apt-get -y --force-yes install wget git nodejs npm nodejs-legacy \
; npm config set strict-ssl false \
; npm install -g n \
; n latest \
; git clone http://github.com/hypfer/Valetudo \
; cd Valetudo \
; /usr/local/bin/npm install \
```
Save the quoted text in a file named Dockerfile
Run `docker build -t valetudo-compiler .`
Wait
run `docker run --rm -it -v $(pwd):/host valetudo-compiler bash -c "cp /Valetudo/valetudo /host && chown $(id -u):$(id -g) /host/valetudo"`

You should end up with a new build of valetudo in your current directory.

SSH to your vacuum, stop the valetudo service (`service valetudo stop`), replace /usr/local/bin/valetudo with your new binary and restart valetudo (`service valetudo start`).

**Comment by florian-asche** [comment]
Whould be great, to have this in the repo.

**Comment by bruvv** [comment]
@Skeletorjus great work! 
@Hypfer please add this so we can help you test new builds :)

**Comment by bruvv** [comment]
It does work when you run it manually but it should be able to run on any machine when you upload it to hub.docker.com. Only thing is I cannot get it to work :(

**Comment by MatttiH** [comment]
Hello,

it seems that the Dockerfile is missiong the
`/usr/local/bin/npm build `
at the end

**Comment by Skeletorjus** [comment]
@MatttiH You are right, managed to mess it up when I copied my Dockerfile. Edited the post.

**Comment by bruvv** [comment]
Thanks for the PR ! i changed it around a bit to make it much much smaller will do a new PR for it and close this.

**Comment by bruvv** [comment]
PR made: https://github.com/Hypfer/Valetudo/pull/277
Docker: https://hub.docker.com/r/bruvv/valetudo
