### ISSUE TITLE
Stuck robot with no errors

### ISSUE THREAD

**Issue by olekenneth** [Hypfer/Valetudo#271]
I get this in Home Assistant

![A4CB430F-96EA-48A2-B1F2-C4C2863F76F2](https://user-images.githubusercontent.com/544388/59782008-53910d00-92bd-11e9-8b99-42c0611f6d7c.png)

The robot has been stuck for a few hours. 

Valetudo has this state:
![985EADAA-F081-42AA-939D-58C92AE89319](https://user-images.githubusercontent.com/544388/59782123-92bf5e00-92bd-11e9-91b7-8b5ee955e4e1.png)

**Comment by dh-harald** [comment]
same for me 2times in the last 3 days

**Comment by olekenneth** [comment]
Same thing happened again. I'm running 0.3.1, which seems to be the newest

**Comment by Technikte** [comment]
Please update to newest version (0.4) and if you using the homeassistant auto-config mqtt then restart ha after the succesfull update.

**Comment by Hypfer** [comment]
stale issue
