### ISSUE TITLE
How to recognize Gen1 and Gen2 devices?

### ISSUE THREAD

**Issue by stevenroose** [Hypfer/Valetudo#280]
I bought a new device supposedly a "new" one, as in updated. I have no idea how to know if it's a gen1 or gen2 device as its not explained anywhere. Please add a photo guide or preferably a mapping from the commercial name to the GenX name. This is my device:
![IMG_20190701_181641](https://user-images.githubusercontent.com/853468/60454908-0140dc00-9c2d-11e9-82c3-cbe450db06da.jpg)

I'm asking since I can't find a `/mnt/default/roborock.conf` file on my device. This is my device's `/mnt/default` directory:

```
$ ls -al /mnt/default
total 40
drwxr-xr-x 3 root root  1024 Jul  1 17:30 .
drwxr-xr-x 6 root root  1024 Jul  1 15:19 ..
-rw-rw-rw- 1 root root    10 Sep 30  2017 adb.conf
-rw-rw-rw- 1 root root    98 Dec 29  2018 device.conf
-rw-rw-rw- 1 root root 22568 Dec 29  2018 librrafm.so
drwx------ 2 root root 12288 Jan  1  1970 lost+found
-rw-rw-rw- 1 root root    16 Dec 29  2018 vinda
```

**Comment by hhovde** [comment]
As far as I can tell, that's a Gen2

When I did some research on the Roborock recently, I found the following distinct features:

Gen1: Xiaomi Mi Robot Vacuum Cleaner
====
LIDAR offset to the edge, two buttons; Home and Power.
![xiaomi_roborock_g1_mrk](https://user-images.githubusercontent.com/1035690/60535430-60255480-9d04-11e9-8116-37c25529cb07.jpg)

Gen2: Roborock S5 Series
====
LIDAR much closer to the center, three buttons; Home, Power and Spot
![xiaomi_roborock_g2_mrk](https://user-images.githubusercontent.com/1035690/60535898-68ca5a80-9d05-11e9-926d-7b9812dadce2.jpg)

Gen3: Roborock S6 Series
====
LIDAR close to the center (like the S5), the three buttons are still present, but are now merged together;
![xiaomi_roborock_g3_mrk](https://user-images.githubusercontent.com/1035690/60536313-3ff69500-9d06-11e9-87ad-ff7e9fcd60b0.jpg)


There might be something of interest for you here:
https://en.roborock.com/pages/robot-vacuum-cleaner
