### ISSUE TITLE
Question: Map parsing in MapDTO? / Unterstanding

### ISSUE THREAD

**Issue by balu-** [Hypfer/Valetudo#282]
Not a issue just a question.

I was browsing though the files and trying to understand the working of Valetudo.
So i came to the map & map-parsing parts (so about the  Valetudo/lib/RRMapParser.js and  Valetudo/lib/dtos/MapDTO.js files). 
The question that came up was, shouldn't the map parsing logic reside in the MapDTO? 
As i understand it:
The robo software transports map data via http call to the valetudo software, 
which parses this data an holds it in the MapDTO. 
-> In my mind the Data Transport object should not only hold the data but also the capability to "pack" & "unpack" it  (as packing is not needed only "unpack" as in parse)

Or is there anything wrong with my logic/ am i missing something?

**Comment by Hypfer** [comment]
Sounds reasonable 🤔
In its current state, the DTO actually doesn't make much sense at all.

I'd say go for it
