### ISSUE TITLE
Support for S6

### ISSUE THREAD

**Issue by maci2100** [Hypfer/Valetudo#283]
Is it possible to support the new s6 version?

**Comment by dugite-code** [comment]
Rooting discussions should be done over in the [dustcloud](https://github.com/dgiese/dustcloud/) repo

See the issue thread regarding the T6 https://github.com/dgiese/dustcloud/issues/213

> Rockrobo changed the encryption of the Firmware+Soundfiles and some of the update process. As I don't have a T6, I cannot really help. So its at the moment not rootable.
