### ISSUE TITLE
Unknown method on persistent maps commands , Gen 1

### ISSUE THREAD

**Issue by Alpoy** [Hypfer/Valetudo#290]
I'm not sure if this is a Valetudo problem or python-miio issue, but the commands to set_lab_status or save map doesn't seem to work. I get a "unknown method" ...

**mirobo raw-command set_lab_status 1**
_Sending cmd set_lab_status with params 1
unknown_method_

**mirobo raw-command save_map**
_Sending cmd save_map with params []
unknown_method_

![image](https://user-images.githubusercontent.com/11949996/61187513-78855f80-a672-11e9-8b24-e7c5e6870cbd.png)
Python-miio: 0.4.5
Roborock Gen 1

**Comment by Hypfer** [comment]
Gen1 doesn't support persistent maps. It's a limitation of the roborock firmware.

We can't do anything about that :(
