### ISSUE TITLE
Map Not Loading at all on Safari in MacOS or any browser on iOS

### ISSUE THREAD

**Issue by SpecialK1417** [Hypfer/Valetudo#295]
Maps will not load on iOS devices tested using safari, firefox, and chrome. Maps load correctly using firefox and chrome on both Win10 and MacOS via local and remote access using nginx reverse proxy. Proxy config was pulled straight from the wiki. All other tabs seem to work correctly on iOS as well.

**To Reproduce:**

1. Navigate to site on iOS device.
2. Map tab will just sit and continuously load.
3. Private tabs = same result.

**Expected behavior**

**Screenshots**
iOS Screenshot: 
![20190723_213509000_iOS](https://user-images.githubusercontent.com/27182447/61750291-fc2a0500-ad72-11e9-9fa6-80412fe67cc9.jpg)

Working Computer Screenshot: 
![2019-07-23 (2)](https://user-images.githubusercontent.com/27182447/61750306-064c0380-ad73-11e9-999e-e528f7371d1c.png)

**Vacuum Model:** Gen2/S5 Firmware Build: 001782 (2 identical vacuums / same issue)

**Valetudo Version:** 0.4.0 

**User-Agent**:
Non-Working: AppleWebKit/Safari
Working Correctly: Firefox/Chrome (Win10 & MacOS)

**Additional context**

**Comment by leonardpitzu** [comment]
clear the safari cache on your ios device - i have 2 iphones (ios 12 and ios 13 beta) and one mac (mojave) and on all of them everything is ok on safari.

**Comment by SpecialK1417** [comment]
This did not fix the issue. iOS 12.1.2 and mac (high sierra). I've since integrated the Valetudo PNG companion app into home assistant and no longer need to access the site directly from my phone. Thanks!
