### ISSUE TITLE
Can't start zone cleanup

### ISSUE THREAD

**Issue by Schattenruf** [Hypfer/Valetudo#296]
Hey :)

I have a problem with my robo S50.
I flashed the package 1782 with the rrlog-patch option and valetudo 0.4.0. But I cannot get my robby to clean just the defined zones. It only states me: There was an error: 500
![image](https://user-images.githubusercontent.com/12720317/62006099-6e686400-b13c-11e9-8933-062ae3f830fa.png)

Here is what I stated (token anonymized):
![image](https://user-images.githubusercontent.com/12720317/62006198-bb006f00-b13d-11e9-8049-8577e267095a.png)

After the building -> flashing:
`(venv) root@iobroker:/roborock# mirobo --ip 192.168.1.176 --token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx update-firmware image/output/v11_001782.fullos.pkg
Going to update from image/output/v11_001782.fullos.pkg
INFO:miio.updater:Serving on 0.0.0.0:42801, timeout 10
INFO:miio.updater:Using local image/output/v11_001782.fullos.pkg (md5: fb264ae45777b01712b3f3196429236c)
Hosting file at http://192.168.1.204:42801/v11_001782.fullos.pkg
Update started!
  0%|                                                                                    | 0/100 [00:00<?, ?it/s]192.168.1.176 - - [28/Jul/2019 13:20:16] "GET /v11_001782.fullos.pkg HTTP/1.1" 200 -
Downloading:  95%|██████████████████████████████████████████████████████████▉   | 95/100 [00:56<00:02,  1.80it/s]INFO:miio.updater:Got a request, should be downloading now.
Downloading:  95%|██████████████████████████████████████████████████████████▉   | 95/100 [00:57<00:02,  1.80it/s]Installation started, please wait until the vacuum reboots
`

I searched the issues but just found the rrlog-patcher thingy. I tried it manually but no chance either.

Can you help me please?

Thank you!

**Comment by vincegio** [comment]
Might be a stupid question, but did you reboot the robot manually? 

Flashed Valetudo myself yesterday and it was not working until I rebooted, think it said this in the installation steps or faq.

**Comment by Schattenruf** [comment]
yep I did. Valetudo works, just the zone cleanup does not.

**Comment by Hypfer** [comment]
To see the error message, open the browser devtools using f12 and take a look at the console.

Does your zone consist of more than 5 zones? The firmware only supports cleaning of up to 5 zones simultaneously.
It's currently possible to create Zones with more than 5 Zones in the GUI. They just won't work.
