### ISSUE TITLE
valetudo: unrecognized service

### ISSUE THREAD

**Issue by Trrw** [Hypfer/Valetudo#299]
Hallo ich habe die neue 0.4.0 installiert. Valetudo startet nicht automatisch. So habe ich gelesen:

"For reasons yet to be discovered, the Valetudo service might not be started on a newly flashed robot. You may need to connect via SSH and rum service valetudo start"

Bei mir kommt jedoch:

sudo service valetudo start
valetudo: unrecognized service

Was kann ich tun?

**Comment by martinwiegand** [comment]
Why is this issue labeled with invalid? I have the same issue.

**Comment by eskorte** [comment]
I had the same issue with an image created by the DustBuilder. Until I realized that I forgot to check the box "Preinstall valetudo 0.4.x". Now it works ;-)
