### ISSUE TITLE
Question: Direct link to map

### ISSUE THREAD

**Issue by Hunv** [Hypfer/Valetudo#301]
Hi,
I like to integrate the Map into a Dashboard of my OpenHab implementation. Is there a possibility to have a direct link to the map to implement it i.e. as an iframe in the Dashboard?
Regards,
Kristian

**Comment by Hunv** [comment]
Would be nice to know what I have to change to get an answer...?

**Comment by Hypfer** [comment]
This is an Issue tracker. Please direct your support requests somewhere else
