### ISSUE TITLE
Home Assistant Zone Cleaning Example did not work

### ISSUE THREAD

**Issue by murmelbahn** [Hypfer/Valetudo#309]
Hi,

I've tried to get the example for the zone cleaning via Home Assistant working but when I execute my script nothing happend. Can someone give me a hint?

~~~yaml
  vacuum_ash_kitchen:
     alias: "Küche reinigen"
     sequence:
       - service: vacuum.send_command
         data:
           entity_id: 'vacuum.xiaomi_vacuum_cleaner'
           command: 'zoned_cleanup'
           params:
             'zone_ids': ['Kitchen']
~~~

**Comment by murmelbahn** [comment]
I found the issue. I was using the Vacuum Component not MQTT.

**Comment by herrwusel** [comment]
Can you edit the wiki with a working example then? Thanks!

**Comment by murmelbahn** [comment]
The example in the wiki is correct.
