### ISSUE TITLE
Hard map limit/boundary issue

### ISSUE THREAD

**Issue by talondnb** [Hypfer/Valetudo#313]
I have a rather weird issue that I've faced in Mi Home and Flolevac apps before rooting and now also in Valetudo, so this might be a limitation within the software itself but I thought I'd post it in case others have had this issue.

I have a long home (10m x 34m) and I have the roborock dock at one end of the house to have it out of the way and in a convenient location. Mapping in all software is generated as a horizontal view as per below. The issue; the map seems to hit a hard limit or boundary before the end of the house in our last bedroom. I've performed full cleans multiple times (had the S55 for around 3 days now) and each time, it hits this limit.

When this limit is reached and the map is generated, I've also attempted a zone clean outside of this boundary but the zone is unable to be dragged past this limit.

Images:

Flolevac - Green indicates dock and the far left is where the limit is hit.
![Screen Shot 2019-08-25 at 07 58 21](https://user-images.githubusercontent.com/3942363/63649815-1fcadb80-c775-11e9-98b3-af917520b03d.png)

Attempting to drag a zone hits this boundary and will not allow it to go further (left).
![Screen Shot 2019-08-25 at 08 02 05](https://user-images.githubusercontent.com/3942363/63649822-2bb69d80-c775-11e9-9ee8-8fe757f7d33c.png)

Mi Home - full clean only cleans less than half of the room, most probably again due to this boundary limit.
![Screen Shot 2019-08-25 at 12 42 39](https://user-images.githubusercontent.com/3942363/63649825-40933100-c775-11e9-91f7-05ccd5f20740.png)

Valetudo - same issue occurs.
![Screen Shot 2019-08-25 at 20 06 30](https://user-images.githubusercontent.com/3942363/63649841-691b2b00-c775-11e9-8c33-9932aebcb235.png)

I've tried moving the dock to an adjacent wall in the hopes of having the map generate vertically rather than horizontally but this doesn't seem to occur. I've not yet tried to place the dock more centered in my home due to locations being less than ideal (10m width means I can't have clutter around the living area).

Any suggestions or guidance as to how I can either overcome the boundary limit or approach this would be much appreciated!

I've also raised a ticket with Roborock support but they actually admitted to not having tested the limit of the distance between the robot and the dock before. The hard limitation of not being able to drag a zone area past this seems to imply that there is indeed a distance limit? Is there any way to choose an orientation of the map or perhaps remove this limitation?

Thanks in advance.

**Comment by Hypfer** [comment]
Sadly, valetudo can't do anything about that... yet.

In the future, Valetudo might become more than just a privacy shim, but that's out of scope for now
