### ISSUE TITLE
Live map frozen when roborock roams between APs

### ISSUE THREAD

**Issue by talondnb** [Hypfer/Valetudo#314]
I have a long floorplan and because of this I'm running an extra wireless access point for wifi coverage, connected via cable to the main router. This shares the same SSID and identical security settings and works fine although roaming can sometimes take a little time.

Because of this, I believe my roborock is causing the following issue. This is the map in valetudo after a complete clean and re-dock. As you can see, it has frozen at the far end of the house where the vac would have had to associate to the second access point.

The issue now is it will retain this map indefinitely until a persistent data wipe and a reboot. Is there any way to avoid this?

**Screenshots**

![image](https://user-images.githubusercontent.com/3942363/63765376-7530f500-c8fb-11e9-90ea-332fa59669ce.png)

**Vacuum Model: Gen2/S55** 

**Valetudo Version: 0.4.0** 

**User-Agent: Chrome/75.0.3770.142**

**Comment by Hypfer** [comment]
At first I expected that this would be a visual issue but 
>The issue now is it will retain this map indefinitely until a persistent data wipe and a reboot. 
this sounds like something else.

What's the current status?
