### ISSUE TITLE
Vakuum not working anymore without warning

### ISSUE THREAD

**Issue by schattenkrieger** [Hypfer/Valetudo#318]
Hello everyone,

today i realised that my vakuum is not working anymore.
i had valetudo installed some months ago and it was working flawless. Since i only run the vacuum when the house is empty i did not realise something was wrong till recently. i noticed that the floor is not clean anymore when i came home and the robot was supposed to have cleaned. also the webgui was not reacable anymore. when trying to start the robot via the buttons it works, but responds in chinese again. the vacuum also has again its own wifi as if it is brand new. dont know what happend there. no one besides me is accessing the robot or doing anything with it. so i just decidet to flash the valetudo firmware again but when i try the "firmware-update" command all i get is a rather long chinese sentance from the vacuum and this error in the console:

Going to update from v11_003468.pkg
INFO:miio.updater:Serving on 0.0.0.0:33589, timeout 10
INFO:miio.updater:Using local v11_003468.pkg (md5: 894e6bca8f3f1bbae4f0638068f7b460)
Hosting file at http://192.168.8.85:33589/v11_003468.pkg
Update started!
  0%|                                                                   | 0/100 [00:00<?, ?it/s]
ERROR:miio.updater:No request was made..

anyone has any idea what happend here and how to fix it?

**Comment by svenburkard** [comment]
hi,
for your described firmware reset problem there is already a open bug ticket with interesting informations: https://github.com/Hypfer/Valetudo/issues/206
