### ISSUE TITLE
Check for firmware update

### ISSUE THREAD

**Issue by chbndrhnns** [Hypfer/Valetudo#32]
I would love to see a notification if the currently used firmware is out-of-date. This way I only need the Mi app to update the firmware (as I assume this might be difficult to achieve using Valetudo?).

**Comment by Hypfer** [comment]
Since new firmware updates will remove valetudo as well as possibly lock the robots firmware I don't think that this is a good idea.

**Comment by chbndrhnns** [comment]
Ok, I was not aware. This would mean updating is generally discouraged until it is clear that the firmware does not break anything...

**Comment by Hypfer** [comment]
Yes.

Afaik, the latest firmware tries to prevent downgrades. 🤔 Not 100% sure if it locks you out yet, though

**Comment by akeilox** [comment]
on this topic how do you check new firmware for locking? Is there a particular source you follow for such notices?

**Comment by Hypfer** [comment]
Dennis Giese mentioned something about that in the official dustcloud telegram group.

**Comment by akeilox** [comment]
Thanks for your reply. I didnt check dustcloud telegram in ages (muted), guess its about time to catch up if xiaomi introducing locking
