### ISSUE TITLE
Feature request: mopping no-go zones

### ISSUE THREAD

**Issue by hugodejong** [Hypfer/Valetudo#321]
My Roborock S50 does a good job vacuuming my carpets. In mopping mode, however, I would like it to skip the carpets. It would be great to be able to define no-go areas specifically for the mopping mode so that the robot would only mop the hard floors.

**Comment by towerhand** [comment]
This would be awesome.

**Comment by Markus-** [comment]
This would be nice.
So at the moment the only way to achieve this behavior is to create zones and let out the carpet-zones, correct? And this just would work if those carpet-zones are not in direct line on the way to a non-carpet-zone.

**Comment by Hypfer** [comment]
As of now, this is Out-of-scope for the project
