### ISSUE TITLE
Map flips from horizontal to vertical

### ISSUE THREAD

**Issue by patsch9** [Hypfer/Valetudo#325]
The Maps flips from time to time from horizontal to vertical and next time back to horizontal.
When you start a zone cleaning and the map flips, than the zone can't be found

**To Reproduce**
start cleaning, build the map and start cleaning again.

**Expected behavior**
the map is allways horizontal or vertical

**Vacuum Model:** 
Gen1

**Valetudo Version: ** 
0.4.0

**User-Agent** 
Chrome or Firefox

Attachment 1 shows the wrong and 2 the correct

![1](https://user-images.githubusercontent.com/47031716/64962413-ad42ac80-d897-11e9-96af-157098d51dad.png)
![2](https://user-images.githubusercontent.com/47031716/64962424-b0d63380-d897-11e9-89ca-8fe3dea4dd1a.png)

The pictures are for illustrative purposes only. I changed the picture manually

**Comment by Hypfer** [comment]
Yeah that's the roborock software doing that. We can't do anything about that, sadly :(
