### ISSUE TITLE
Carpet mode parameters

### ISSUE THREAD

**Issue by ctandi** [Hypfer/Valetudo#326]
Can anyone enlighten me on the carpet mode parameters? I can't seem to find any documentation on them. My issue is that I have a black carpet in my bedroom that triggers the cliff sensors, hence the robot avoids the area. I'm wondering if there is a way to solve this by adjusting the parameters. I already tried to tape the sensors, but the robot starts complaining about dirty sensors after a while or the tape gets ripped off by the side brush.

Thanks in advance

**Comment by rumpeltux** [comment]
This doesn’t sound like a bug in Valetudo. You can potentially ask for help on www.roboter-forum.com.
