### ISSUE TITLE
Hassio no vacuum.valetudo over mqtt

### ISSUE THREAD

**Issue by dennis071nl** [Hypfer/Valetudo#337]
Is there a way to manually trigger the connect message??

I cannot operate the vacuum through HomeAssistant (Hassio 0.99.3)

I followed the installation guide, succesfully. I get the frontend, can start/stop cycles etc etc. I ssh-ed into the rockrobo, entered my MQTT details and rebooted. In the log says MQTT server connected, only thing is that the integration doesn't work . There is no vacuum.rockrobo in my entities. 

**To Reproduce**

**Expected behavior**

**Screenshots**

Logfile in Valetudo says  "
Robot connected
Robot connected
Robot connected
Robot connected
Loading configuration file: /mnt/data/valetudo/config.json
Dummycloud is spoofing 203.0.113.1:8053 on 127.0.0.1:8053
Webserver running on port 80
Connected successfully to mqtt server
Robot connected
Robot connected

In Home Assistant the log of the MQTT addon says:

INFO] found mqtt on Home Assistant
1570460454: New client connected from 192.168.2.21 as mqttjs_22bbbc61 (p2, c1, k60, u'mqtt').

**Vacuum Model:** 
Gen 1
**Valetudo Version: ** 
0.4.0
**User-Agent** 

**Additional context**

**Comment by oechslein** [comment]
Do you have an entry in your logfile with
ERROR (MainThread) [homeassistant.components.mqtt.vacuum] Exception in async_discover when dispatching 'mqtt_discovery_new_vacuum_mqtt': ({'name': 'rockrobo', 'schema': 'state', 'supported_features': ['start', 'pause', 'stop', 'return_to_base', 'battery', 'status', 'locate', 'clean_spot', 'fan_speed', 'send_command'], 'command_topic': 'valetudo/rockrobo/command', 'state_topic': 'valetudo/rockrobo/state', 'set_fan_speed_topic': 'valetudo/rockrobo/set_fan_speed', 'fan_speed_list': ['whisper', 'min', 'medium', 'high', 'max', 'mop'], 'send_command_topic': 'valetudo/rockrobo/custom_command', 'json_attributes_topic': 'valetudo/rockrobo/attributes', 'platform': 'mqtt'},)
?

I supect there is currently a mismatch between the autoconfig message what valetudo sends ([after this change](https://github.com/Hypfer/Valetudo/commit/92d7285b2a3bf76096ce86fb5a7f823f133960b8)) and what home assistant expects (v0.100.2).
Difference is "return_home" versus "return_to_base" in the supported_features list.
Maybe @TheRealMoeder can comment on this?

**Comment by dennis071nl** [comment]
where can i find the logfile??

**Comment by oechslein** [comment]
Sorry I meant the home assistant logfile "home-assistant.log".

**Comment by oechslein** [comment]
And try replacing in lib/MqttClient.js line 106 the "return_to_base" back to "return_home" an see if that helps like it helped myself.

**Comment by dennis071nl** [comment]
on the vacuum, i log in over ssh, in the /lib directory there is no
MqttClient.js....??

Op vr 18 okt. 2019 om 09:22 schreef oechslein <notifications@github.com>:

**Comment by oechslein** [comment]
> on the vacuum, i log in over ssh, in the /lib directory there is no MqttClient.js....?? 
> Or should i compile it after adapting the file...? 
Yes you would need to recompile it.
Have you looked into your home assistant log? If you have the same output like above, I can create a change to fix this issue.

**Comment by dennis071nl** [comment]
got it! apparently my mistake that i activated both mqtt addon and embedded
broker. vacuum.roborock is alive! :-)

Op vr 18 okt. 2019 om 11:00 schreef oechslein <notifications@github.com>:

**Comment by bonze4** [comment]
@dennis071nl Did you rename the MqttClient.js file? I have the same problem. My robot connects well to the broker but i can not see the vacuum in HA. The discover feature does not work for now.

**Comment by dennis071nl** [comment]
Tim, which mqtt broker do you use?? I used both the addon as weas the em
edded broker.. Just use the addon, worked for me...

Op ma 21 okt. 2019 20:14 schreef Tim <notifications@github.com>:

**Comment by bonze4** [comment]
@dennis071nl I don’t use the embedded broker. I checked my configuration.yaml and there is no entry for the embedded one. I’ve installed the mosquito addon. The broker works fine and already discovered some Tasmota devices. So basically everything works fine. I don’t no why it’s not possible for HA to discover the vacuum.

**Comment by dennis071nl** [comment]
Tim, with the addon enabled, there is no need for any reference to mqtt in
configuration.yaml...

That did the trick for me...

Op di 22 okt. 2019 08:43 schreef Tim <notifications@github.com>:

**Comment by oechslein** [comment]
@bonze4 Did you compile valetudo yourself (from lastest master)?
Search for "ERROR (MainThread) [homeassistant.components.mqtt.vacuum]" in the homeassistant.log (in your home assistant config folder).

**Comment by bonze4** [comment]
@oechslein I don't compiled Valetudo by myself. I'm still running 0.4.0 because i thought that @dennis071nl may have an idea how to fix the problem.

I have no log-entry related to "ERROR (MainThread) [homeassistant.components.mqtt.vacuum]". Before I have checked the logs I restarted the server and the vacuum.

My MQTT Addon says:
```
1571861785: New connection from 192.168.XXX.XX on port 1883.
[INFO] found valetudo on local database
1571861786: New client connected from 192.168.XXX.XX as mqttjs_88c98dbc (p2, c1, k60, u'valetudo').
```

**Comment by dennis071nl** [comment]
Do you have a mqtt entry in your co figuration.yaml?? If so: remove it!

Op wo 23 okt. 2019 22:25 schreef Tim <notifications@github.com>:

**Comment by bonze4** [comment]
@dennis071nl I don't have an Mqtt entry in my configuration.yaml

**Comment by MitschiBoy** [comment]
@bonze4 Try publishing a retained message to the topic
`homeassistant/vacuum/valetudo_rockrobo/config`
with the following payload
`{
  "name": "rockrobo",
  "unique_id": "rockrobo",
  "schema": "state",
  "supported_features": [
    "start",
    "pause",
    "stop",
    "return_home",
    "battery",
    "status",
    "locate",
    "clean_spot",
    "fan_speed",
    "send_command"
  ],
  "command_topic": "valetudo/rockrobo/command",
  "state_topic": "valetudo/rockrobo/state",
  "set_fan_speed_topic": "valetudo/rockrobo/set_fan_speed",
  "fan_speed_list": [
    "min",
    "medium",
    "high",
    "max",
    "mop"
  ],
  "send_command_topic": "valetudo/rockrobo/custom_command",
  "json_attributes_topic": "valetudo/rockrobo/attributes"
}`
After that restart Home Assistant
Adding unique_id should to the trick

**Comment by gargomoma** [comment]
Hey guys, same problem here, and I cannot guess what is making HA not finding my vacuum.

I'm running:
HA 0.100.1 under docker.
Mosqqitto under docker as well.
And Valetudo 0.4.0 (from DustBuilder)

I'm on the same situation as @bonze4, mqtt is already working (zigbee2mqtt & tasmota) , and cannot see anything on the logs.

Thanks =)

**Comment by MitschiBoy** [comment]
MQTT auto-discovery ist not working at the moment because of missing unique_id.
Add the following to your configuration.yaml
```
vacuum:
  - platform: mqtt
    name: "rockrobo"
    schema: state
    supported_features:
      - start
      - pause
      - stop
      - return_home
      - battery
      - status
      - locate
      - clean_spot
      - fan_speed
      - send_command
    command_topic: "valetudo/rockrobo/command"
    state_topic: "valetudo/rockrobo/state"
    set_fan_speed_topic: "valetudo/rockrobo/set_fan_speed"
    fan_speed_list:
      - min
      - medium
      - high
      - max
      - mop
    send_command_topic: "valetudo/rockrobo/custom_command"
    json_attributes_topic: "valetudo/rockrobo/attributes"
```

**Comment by gargomoma** [comment]
It's pretty weird, but I couldn't see my vacuum until y removed any mqtt parameters from my configuration.yaml

[Like they explain in HA forum](https://community.home-assistant.io/t/valetudo-xiaomi-vacuum-dustcloud-alternative-live-maps/66277/111)

After doing that, I sent the mqtt payload, and I started to see my vacuum. =)

Thanks!

**Comment by Hypfer** [comment]
> MQTT auto-discovery ist not working at the moment because of missing unique_id.

Is there some place where this requirement is mentioned? As far as I can tell it is optional?

**Comment by MitschiBoy** [comment]
I just did a test. Auto-discovery is working without unique_id if the mqtt-integration is set up in the configuration.yaml. It does not work if the mqtt-integration is set up via the user interface by config flow.
I think it's mentioned here https://github.com/home-assistant/home-assistant/pull/16943 that unique_id is necessary.

**Comment by Hypfer** [comment]
` It does not work if the mqtt-integration is set up via the user interface by config flow.`

Okay that explains why I didn't notice it. Thanks for testing that!

**Comment by Hypfer** [comment]
Should be fixed
