### ISSUE TITLE
Support for Xiaomi Mi Robot 1s?

### ISSUE THREAD

**Issue by taucher4000** [Hypfer/Valetudo#343]
Hi,

I just bought a Xiaomi Mi Robot 1s which is the latest model of xiaomi robots and I'm wonder if Valetudo also supports this model already or if there is any plan to support this model in the future?

Thanks,
Taucher

**Comment by rand256** [comment]
You'd better wonder whether you robot could be hacked to get filesystem access to it at the first place. Hint: no.

Unless this changes, there will be no support for anything in those latest models.

**Comment by tenkaibr** [comment]
Is the roborock s50 gen1 or gen2?

**Comment by argonym** [comment]
Related: https://github.com/dgiese/dustcloud/issues/252

**Comment by Hypfer** [comment]
It _should_ work with 0.5.3

I haven't tested it though. Also, you need to of course acquire root which is hard on these things
