### ISSUE TITLE
Discovering

### ISSUE THREAD

**Issue by sukoshi1507** [Hypfer/Valetudo#345]
Hello,

I just discovered the project but as I see the warning regarding the 'do not upgrade to 4004' I also realize that my two gen2 were upgraded.

I'm not able to find a reason. Changes in the firmware which makes them unrootable ?

Details would be appreciated for newcomers like me :)

**Comment by rand256** [comment]
Changes in the firmware make it impossible to locally flash another firmware image when you'll decide to upgrade from that one. Now flashing procedure allows downloading images only from remote xiaomi servers.

**Comment by sukoshi1507** [comment]
So i'm totally screwed now.

Thanks :)

**Comment by rand256** [comment]
You can simply do factory reset to return to the upgradable initial firmware.

Also I think it should be possible to initiate firmware upgrade process by sending needed commands from the cloud interface, which valetudo emulates since 0.3.0. Just nobody implemented that yet.

**Comment by sukoshi1507** [comment]
I'll be the guinea pig if needed :-)
