### ISSUE TITLE
Can't create Forbidden markers There was an error: 501

### ISSUE THREAD

**Issue by userosos** [Hypfer/Valetudo#346]
Can't create Forbidden markers.

1. Go to web face
2. Click on Zones
3. Configure forbidden zones
4. Select the zone or virtual wall on the map
5. Click on Save
6. There was an error: 501

Xiaomi Mi Robot Vacuum gen 1

![изображение](https://user-images.githubusercontent.com/22872748/66865371-c5ddd980-ef9f-11e9-83de-83c44338b033.png)

Valetudo Version:  0.4.0 
It not work from RoboRock Control Center also
![изображение](https://user-images.githubusercontent.com/22872748/66865466-f6be0e80-ef9f-11e9-93e2-3e77948c3855.png)
I used it from chromium and firefox.

**Comment by rand256** [comment]
gen1 firmware doesn't support it.
