### ISSUE TITLE
Cant reach webserver to enter wifi credentials

### ISSUE THREAD

**Issue by wAuner** [Hypfer/Valetudo#347]
I have the roborock second generation. I've reset the wifi settings and followed the instructions from the tutorial and I've built my image with dustbuilder. Everythig worked fine but when I finally want to connect to the webserver on `192.168.8.1` while I'm connected to the robots wifi, nothing happens, the site can't be reached. I'm able to connect via ssh though.

Any ideas what went wrong? Thanks!

**Comment by Jackfritt** [comment]
Same problem here :)

**Comment by nagel86** [comment]
This might help:
For reasons yet to be discovered, the Valetudo service might not be started on a newly flashed robot. You may need to connect via SSH and run `service valetudo start`

**Comment by Jackfritt** [comment]
Ok found my problem. I didnt compile  Valetudo from git
git clone https://github.com/Hypfer/Valetudo.git
cd Valetudo/
npm install
npm run build

This was the difference from the Installation Instructions. There you should 
download the bin file from Valetudo. I wanted the latest ang greatest stuff :)

Thx for the hints.
