### ISSUE TITLE
Standby / Shutdown bug

### ISSUE THREAD

**Issue by megusta-01** [Hypfer/Valetudo#349]
Hey,
i've a bug, with gen1 FW v11_003468 and Valetudo 0.4.0

With original Firmware my vacuum shuts down after some time without electricity/ charging. 
Now it doesn't happend. Is it a bug of Firmware or Valetudo?

**Comment by tenkaibr** [comment]
Is it possible to remote shutdown?

**Comment by megusta-01** [comment]
You mean in console "shutdown -h now" ? I don't know, I've now factory firmware

**Comment by Hypfer** [comment]
Firmware. Not Valetudo related
