### ISSUE TITLE
Binary asset links of beta 0.4.0 release still link to version 0.3.1

### ISSUE THREAD

**Issue by ElePhontitis** [Hypfer/Valetudo#350]
I recently updated the firmware and the valetudo server of my S50.

firmware: v11_001748.fullos
valetudo: Beta 0.4.0 binary from release assets

After the update the announced features like the reworked zoning UI or the Access Control Settings are not there. 

Here is my valetudo settings/info screen:
![image](https://user-images.githubusercontent.com/8995003/67513771-d414af80-f69b-11e9-8ad0-01671cf2c6f3.png)

It is odd that it still shows valetudo 0.3.1 even though I downloaded it via this link:
https://github.com/Hypfer/Valetudo/releases/download/0.4.0/valetudo

Also, the package.json in https://github.com/Hypfer/Valetudo/archive/0.4.0.zip still says
```
 {
      ...,
      "version": "0.3.1",
      ....
 }

```

When I build Valetudo from source, the version correctly shows 0.4.0

**Comment by alexkn** [comment]
0.5.0 release looks ok
