### ISSUE TITLE
Wiki: Installation Instructions reverted?

### ISSUE THREAD

**Issue by bbarbisch** [Hypfer/Valetudo#351]
Hi,

Is there a specific reason why the installation instructions (the wiki site) was reverted to a previous state? (like: incompatible firmware, invalid installation steps,...)

It seems like a log of useful information was removed by this change if you're looking at the diff.

**Comment by Hypfer** [comment]
Thank you for pointing that out!
The reason was, that I trusted the community. That was wrong

I've locked the wiki. Sorry all
