### ISSUE TITLE
return_to_base

### ISSUE THREAD

**Issue by dlashua** [Hypfer/Valetudo#354]
**Describe the bug**
PR #336 changed "return_home" to "return_to_base". However, in Home Assistant version 0.100.3, "return_home" is the valid feature name and "return_to_base" causes the Vacuum Entity to not import/load/

**To Reproduce**

**Expected behavior**

**Screenshots**

**Vacuum Model:** 
S5

**Valetudo Version: ** 
0.4.0

**User-Agent** 

**Additional context**

**Comment by Hypfer** [comment]
https://github.com/Hypfer/Valetudo/pull/355

PR reverted
