### ISSUE TITLE
Unable to update information in Settings/App Locale

### ISSUE THREAD

**Issue by x10an14** [Hypfer/Valetudo#359]
**Describe the bug**
Unable to edit the information shown in `Valetudo Webview`->`Settings`->`App Locale`.

**To Reproduce**

- Edit `/etc/timezone` to a timezone of your choosing (e.g. `Europe/Oslo`).
- Or add the following to `/mnt/data/valetudo/config.json`;

  ```
    "allowSSHKeyUpload": true,
    "map_upload_host": "http://127.0.0.1",
  + "timezone": "Europe/Oslo",
  + "location": "no"
  }
  ```

**Expected behavior**

 `Valetudo Webview`->`Settings`->`App Locale` should reflect these settings instead of continuing to show what's hard-coded as default into the `/usr/local/bin/valetudo` binary. 

**Screenshots**

https://github.com/x10an14/Valetudo/blob/add_screenshot/Screenshot%20from%202019-11-01%2022-52-54.png

<details>
<summary><code>/mnt/data/valetudo/config.json</code></summary>

```json
{
  "spots": [],
  "areas": [
    <snip>
  ],
  "mqtt": {
    "enabled": false,
    "identifier": "rockrobo",
    "topicPrefix": "valetudo",
    "autoconfPrefix": "homeassistant",
    "broker_url": "mqtt://user:pass@foobar.example",
    "provideMapData": true,
    "caPath": ""
  },
  "dummycloud": {
    "spoofedIP": "203.0.113.1",
    "bindIP": "127.0.0.1"
  },
  "httpAuth": {
    "enabled": true,
    "username": "valetudo",
    "password": "<snip>"
  },
  "allowSSHKeyUpload": true,
  "map_upload_host": "http://127.0.0.1",
  "timezone": "Europe/Oslo",
  "location": "no"
}
```
</details>

**Vacuum Model:**

Xiaomi Roborock S55 (Gen2?)

**Valetudo Version**

0.4.0

**User-Agent**

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36`

**Additional context**
N/A.

**Comment by Hypfer** [comment]
This endpoint actually just calls the `app_get_locale` miio command and returns its response.

Editing `/etc/timezone` doesn't do anything at all since the roborock software doesn't care about it because that's nothing that might happen without root.

You're looking for the `set_timezone` command which is available via the Timers menu
