### ISSUE TITLE
Implement way to read current coordinates

### ISSUE THREAD

**Issue by bendews** [Hypfer/Valetudo#36]
Not sure how feasible this is, but it would make it much easier to set up zones if we were able to see where the vacuum currently is in the vacuum coordinates format 😄Then we could use manual control to drive it to corners of rooms etc.

**Comment by fenio** [comment]
Where exactly can we use "co-ordinate click functionality" in 0.3.1 release? I don't see anything like that.

**Comment by Hypfer** [comment]
stale
