### ISSUE TITLE
mqtt - password with colons fails

### ISSUE THREAD

**Issue by Export33** [Hypfer/Valetudo#361]
i tried for hours yesterday until i realized that mqtt was not working because of a colon in my password.

separate entries for username/password would be nice. but i guess a entry in the wiki would be sufficient.

example:
`"broker_url": "mqtt://username:pass:word@192.168.1.22",`

**Comment by rimrul** [comment]
Does `mqtt://username:pass%3Aword@192.168.1.22` work?

**Comment by Hypfer** [comment]
Don't use passwords with colons. They're ambiguous
