### ISSUE TITLE
Feature Request: WPA2 Enterprise WIFI

### ISSUE THREAD

**Issue by onkelandy** [Hypfer/Valetudo#363]
Hi!

I was successfully connecting my Roborock S5 to my Wifi using a RADIUS server by changing the content of the file /opt/rockrobo/wlan/wifi_start.sh. I've added these lines in wifi_sta_mode:
```
        echo 'network={' >> $WPA_CONF
        echo ' ssid="SSID"' >> $WPA_CONF
        echo ' scan_ssid=1' >> $WPA_CONF
        echo ' key_mgmt=WPA-EAP' >> $WPA_CONF
        echo ' #pairwise=CCMP TKIP' >> $WPA_CONF
        echo ' #group=CCMP TKIP' >> $WPA_CONF
        echo ' eap=TLS' >> $WPA_CONF
        echo ' identity="roborock@whatever.com"' >> $WPA_CONF
        echo ' ca_cert="/root/ca.pem"' >> $WPA_CONF
        echo ' client_cert="/root/Roborock.pem"' >> $WPA_CONF
        echo ' private_key="/root/Roborock.key"' >> $WPA_CONF
        echo ' private_key_passwd="SECRET"' >> $WPA_CONF
        echo ' priority=1' >> $WPA_CONF
        echo ' }' >> $WPA_CONF
```

However I had the big problem this part gets overwritten after some days. Any hints how I can make this change permanent? Of course implementing it in the web interface would be better. The location of the certificates might also be an issue though it looked like the files didn't get deleted from the root and opt folder.

Thanks for helping.

**Comment by rumpeltux** [comment]
This doesn’t sound like a bug in Valetudo. You can potentially ask for help on www.roboter-forum.com.
