### ISSUE TITLE
Problem with Roborock

### ISSUE THREAD

**Issue by xMrVizzy** [Hypfer/Valetudo#366]
After some time, the vacuum cleaner stopped opening the web interface and began to speak a different language, after resetting the Wifi settings it is not possible to connect via ssh and through the Web interface, what could be the problem?

**Comment by xMrVizzy** [comment]
Roborock S50

**Comment by xMrVizzy** [comment]
Solved

**Comment by pickeld** [comment]
how?
same issue here

**Comment by rickardrockard** [comment]
See #206
