### ISSUE TITLE
automatic factory reset

### ISSUE THREAD

**Issue by Wolf6660** [Hypfer/Valetudo#367]
Hi,
My two Xiaomi vacuum cleaners have returned to factory condition. I had to re-train him and flash it again with the Valetudo firmware.
Why did this happen?

thanks
Daniel

**Comment by rickardrockard** [comment]
See #206

**Comment by megusta-01** [comment]
same problem, reflashed two times. yesterday again factory settings.

**Comment by stormtroopa** [comment]
I got my robot yesterday and flashed it right away with v11_001886. Everything worked fine, also cleaning. This morning the roborock started talking out of nothing: "...root failure...restoring the initial version...". 
After restoring the initial version I flashed Valetudo again. Only 10 min. later the s55 restores its initial software again.
What can I do?

**Comment by rickardrockard** [comment]
Keep the discussion in #206
