### ISSUE TITLE
[Feature Request] Dark Theme

### ISSUE THREAD

**Issue by silviob72** [Hypfer/Valetudo#368]
Dark Theme for WebUI. Also with time for turn on/off automatically and with sunrise sunset, or via mqtt command.

**Comment by pax2011** [comment]
It would be nice!!

**Comment by rimrul** [comment]
I've done rough quick dark theme toggle with browser developer tools and the dark css that already ship with valetudo:

![dark home](https://user-images.githubusercontent.com/6178234/68958906-52f99580-07cd-11ea-9917-a25e2cfd44bf.png)
![dark settings](https://user-images.githubusercontent.com/6178234/68958921-5db42a80-07cd-11ea-9fdd-9e04f49c3bab.png)

There's still some improvements to be made...

**Comment by silviob72** [comment]
Cool! 👍

**Comment by pax2011** [comment]
On chrome I use [https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh](url) but only on pc
![val](https://user-images.githubusercontent.com/56022493/68964143-ebe1de00-07d8-11ea-94f5-5e6c32cc899c.PNG)

**Comment by notz** [comment]
It would be cool the to load own css theme per browser. So we can override the some styles if you embed valetudo in home assistant as iframe.

**Comment by erkexzcx** [comment]
Someone was doing God's work by bringing dark theme.

**Comment by rimrul** [comment]
New and improved state of #374 :

![grafik](https://user-images.githubusercontent.com/6178234/69370593-88572500-0c9e-11ea-9079-4fc0f7fea99f.png)
![grafik](https://user-images.githubusercontent.com/6178234/69370653-a755b700-0c9e-11ea-92a1-ac28e5beef2b.png)

**Comment by Hypfer** [comment]
PR is already merged to master. Thanks @rimrul
