### ISSUE TITLE
Zoned_cleanup limit via MQTT

### ISSUE THREAD

**Issue by darkkatarsis** [Hypfer/Valetudo#372]
## Describe the bug
When publish payload for example:
`{ "command": "zoned_cleanup", "zone_ids": ["Bathroom", "Living room"] }` 
Everything works as it should. It cleans two zones

This one work also:
`{ "command": "zoned_cleanup", "zone_ids": ["Bathroom", "Living room", "Bedroom"] }`

This not:
`{ "command": "zoned_cleanup", "zone_ids": ["Bathroom", "Living room", "Bedroom", "Library"] }`

This case works again:
`{ "command": "zoned_cleanup", "zone_ids": ["Bathroom", "Living room", "Library"] }`

### Vacuum Model

Roborock S5

### Valetudo Version

 0.4.0

### User-Agent

Version 78.0.3904.97 (Official Build) (64-bit)

## Expected behavior

All multiple cases of zones should work
## Additional context

Is there any limitation for multi zone payloads?

**Comment by rimrul** [comment]
Zones consist of rectangular areas. Zoned cleanup is limited to 5 of those areas since d8c38176 (part of version 0.3.1)

**Comment by darkkatarsis** [comment]
In my example which doesn't work I used less than 5 zones. The zones are rather correct because each individual works very well, in some variations of many zones as well

My zones list
```
"Living room"
['21070', '24948', '26688', '29561']
"Bedroom"
['23879', '29597', '27833', '33029'], ['24396', '33029', '27057', '33459']
"Office"
['23768', '33530', '28129', '35747'], ['26355', '33137', '28092', '33530']
"Bathroom" 
['22142', '33923', '23805', '35747']
"Library"
['21218', '30562', '22770', '32171']
"Hallway"
['22955', '32279', '24507', '33888'], ['21624', '32600', '22918', '34102'], ['22622', '29597', '24064', '32279'], ['21292', '29561', '22622', '30169']
```

**Comment by darkkatarsis** [comment]
Unless, if a given zone consists of small zones, they also count towards the limit of 5?

**Comment by rimrul** [comment]
Yes, that's what I meant. Up to 5 rectangles. I.e. your hallway is already close to the limit.

**Comment by darkkatarsis** [comment]
Ok, now everything is clear. Thank you

**Comment by rimrul** [comment]
@Hypfer how plausible is it to do the following in startCleaningZoneByCoords instead of erroring out on larger arrays:

* split the array into chunks of 5
* start cleanup for the first 5 areas
* wait for those to finish cleaning
* rinse and repeat for the next 5

**Comment by Hypfer** [comment]
Getting `wait for those to finish cleaning` to work reliably will be hard I think.
