### ISSUE TITLE
[Enhancement] - Change Timezone UI

### ISSUE THREAD

**Issue by MrReSc** [Hypfer/Valetudo#378]
## Enhancement
The time zone can be set under `Settings -> Timers` via the gear icon. Unfortunately this is not very intuitive because the icon is very small. It would be better to have a gear icon under `Settings -> Info` next to the time zone.

### Screenshots
![TZ](https://user-images.githubusercontent.com/24952268/69252050-b3fce100-0bb2-11ea-92fd-e7cbac7b57b4.png)

### Valetudo Version
0.4.0

**Comment by pejotigrek** [comment]
just a quick question - you wrote:

> The time zone can be set under Settings -> Timezone via the gear icon. Unfortunately this is not very intuitive because the icon is very small

how can I set this timezone? I am on valetudo 0.4.0, and can't se an option [is it really THAT SMALL? ;)]. I can go to Settings->Info to see the timezone, but it can't be set

**Comment by MrReSc** [comment]
The time zone can be set under `Settings -> Timers` in the top right corner.
Sorry i mean `Timers` not `Timezone` as in OP.

**Comment by pejotigrek** [comment]
@MrReSc thanks for clarification! :)

**Comment by Hypfer** [comment]
Sounds reasonable. I'll await your PR
