### ISSUE TITLE
no such file or directory, open '/dev/shm/navmapfirst.ppm'

### ISSUE THREAD

**Issue by stefanct** [Hypfer/Valetudo#38]
Found this in the log. No idea when this happened or why; and everything's fine again but maybe it should be handled more directly than just passing the exception up the stack if it can actually happen (I certainly did not do anything too unusual... just some wlan configuration, system updates via `apt-get` etc. - nothing directly related to valetudo (apart from interacting with its website)).

	Webserver running on port 80
	fs.js:145
		throw err;
		^

	Error: ENOENT: no such file or directory, open '/dev/shm/navmapfirst.ppm'
		at Object.fs.openSync (fs.js:579:3)
		at Object.fs.openSync (pkg/prelude/bootstrap.js:483:32)
		at Object.fs.readFileSync (fs.js:485:33)
		at Object.fs.readFileSync (pkg/prelude/bootstrap.js:679:36)
		at /snapshot/Valetudo/webserver/WebServer.js:808:58
		at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:3)

**Comment by petabyteboy** [comment]
I also ran into this bug. It still happens with Valetudo 0.2.0.
