### ISSUE TITLE
Nginx with paths different from "/"

### ISSUE THREAD

**Issue by silviob72** [Hypfer/Valetudo#381]
I have tried to configure my roborock trough nginx to a path different from "/" and I have had some problems with  map update. So I have find a possible problem in vacuum-map.js at line 36:
 ```ws = new WebSocket(`${protocol}://${window.location.host}/`);```
 I have temporary fixed with: 
```ws = new WebSocket(`${protocol}://${window.location.host + window.location.pathname}`);```
Is that the right way or can be fix in some other ways?
Thanks

**Comment by Hypfer** [comment]
Is this still an issue?

**Comment by Hypfer** [comment]
Should work now since we've swiched to SSE
