### ISSUE TITLE
[Feature Request] Switch WiFi off by pressing a button

### ISSUE THREAD

**Issue by MalteFlender** [Hypfer/Valetudo#387]
Is it possible to add a function to the software that reassign one of the physical buttons on the vacuum cleaner to switch its WiFi on/off? After I programmed the robot and it works fine on a day-to-day basis there is no need for it to constantly be in the WiFi anymore, unless I want to reprogram it. Having a way to switch WiFi on and off would be really great. It would save some battery life and lessens the overall electromagnetic radiation.

**Comment by rimrul** [comment]
That seems quite a bit outside the scope of Valetudo.

**Comment by MalteFlender** [comment]
What do you think would be a better place to implement such a feature?

**Comment by rimrul** [comment]
I'd say log in via ssh, create a script like this one https://askubuntu.com/a/240516, but without the `notify-send` part (maybe play some sound there that informs you wether wifi is on or off) and figure out how to call that on button press instead of say starting zoned cleanup.
