### ISSUE TITLE
Memory leak in Valetudo?

### ISSUE THREAD

**Issue by dugite-code** [Hypfer/Valetudo#39]
I discovered a small issue when using Home-Assistant to Poll the Map too often (every 10 seconds to get a sort of Live map). The `/tmp` directory filled and the vacuum locked up. A re-boot fixes the issue obviously.

I had done other things on the vacuum in the past so I might have had less space available than normal.

A quick work-around was to throw this into cron
`*/1 * * * * cd /tmp/maps && ls -t /tmp/maps | tail -n +2 | xargs rm --`

**Comment by dugite-code** [comment]
Actually after further looking into the matter it looks like it might be a low memory issue rather than the `/tmp` partition filling up. I'v added a swap file on `/mnt/data` to see if that solves my issues

As you can see Valetudo is taking up 76% of the memory:
![image](https://user-images.githubusercontent.com/12742064/47972887-ae357a00-e0db-11e8-8ad3-486beeadf9c6.png)

**Comment by Hypfer** [comment]
After looking at the [code ](https://github.com/Hypfer/Valetudo/blob/master/webserver/WebServer.js#L403) for 20 minutes, I still have no idea what could be responsible for the memory leak.

However, I've noticed that on every request the robot + charger images are read from flash for no reason so I guess the whole part will be rewritten at some point.
Could you provide a specification for this interface? What endpoints are there? What does Home-Assistant expect? 
I'm not using those home automation frameworks nor did I write said code so I don't have the slightest Idea. 🙃

**Comment by dugite-code** [comment]
Essentially all HA is doing is calling `YOUR.VACUUM.ROBOT.IP/api/remote/map` and then pulling the image using the mapsrc from the json response using a GET request (using the python requests library).

The only real difference between HA and using curl is the speed of the requests, normally HA will do this every 30 seconds I tuned it up to every 10 seconds, I wouldn't think that would cause an issue.

setting  drawRobot and drawCharger to false by calling `YOUR.VACUUM.ROBOT.IP/api/remote/map?drawRobot=false&drawCharger=false&scale=5&border=3&doCropping=true&drawPath=true` looks like it might fix the issue. When drawing the robot and charger at 3min run time it was rising above 25% memory, when not drawing the robot and charger it's bouncing between 16% and 20% at 5min run time.

I'll run this for a while without restarting and let you know if the memory usage stays at ~20% mark

As a side note: Having a further look into the HA settings I've enabled `limit_refetch_to_url_change: True`, This should reduce the fetching of the map image a little.

**Comment by dugite-code** [comment]
After further looking into it, it's strange I am seeing the issue after all the upstart script has an oom score of 1000 so it should in theory handle itself. I am using an older firmware `v11_003194` so perhaps that is the issue.

**Comment by Hypfer** [comment]
Is this still happening? Did you try remote debugging and taking a heap dump?

**Comment by dugite-code** [comment]
I am still seeing the issue. I'll try to look into the heap dump soon.

I'll also look into updating the firmware as I'm using an older one

**Comment by axel-kah** [comment]
I just rooted my rockrobo v1 with latest firmwarebuilder (FW v11_003194, --disable-xiaomi), dummycloud_0.1 and Valetudo 0.9 via rrcc. I really like the newly gained power over my vacuum but observed the same behaviour as @dugite-code. Basically every map related call increases the memory footprint of Valetudo process.

I did some measurements in a notebook to stress Valetudo by doing the same api call 1000 times in a row. requests was used to interact with Valetudo API and output of ps via paramiko for the process info. The memory footprint steadily increases to up to 60% before the process terminates when triggering a new map with ``api/remote/map`` and requesting the png.
![measurements_trigger_and_read_n_times_2018_12_29_144840](https://user-images.githubusercontent.com/46245032/50539562-b9100680-0b82-11e9-8e3f-c6e3ba46385d.png)

Simply fetching the same png for 1000 times also steadily increases footprint but only by 0.5% points.
![measurements_trigger_once_read_n_times_2018_12_29_145514](https://user-images.githubusercontent.com/46245032/50539566-d5ac3e80-0b82-11e9-9002-d6dbd24cbe83.png)

Doing the same for ``api/map/latest`` does also increase footprint somewhat.
![measurements_fetch_latest_n_times_2018_12_29_155024](https://user-images.githubusercontent.com/46245032/50539572-e9f03b80-0b82-11e9-96bf-6a4cad6de1d5.png)

I don't have any experience with node.js apps but I'll try to use the techniques described here to get a clue why the garbage collection fails: https://www.nearform.com/blog/how-to-self-detect-a-memory-leak-in-node/

**Comment by Hypfer** [comment]
Thanks for looking into that and providing this graphs @axel-kah!
Sadly, I can't help much with that. I'd still love to just drop local map generation altogether which should definitely fix this issue as well :^)

This depends on #66

**Comment by Hypfer** [comment]
I guess this should be fixed with https://github.com/Hypfer/Valetudo/releases/tag/0.2.2

**Comment by Hypfer** [comment]
Nope. Still an issue.

Although it seems like Valetudo is not the only software experiencing it
https://github.com/oliver-moran/jimp/issues/153

**Comment by Hypfer** [comment]
Doesn't happen with Node 8 it seems.

**Comment by Hypfer** [comment]
Testing Node 11.12 shows no signs of the leak so I guess https://github.com/nodejs/node/issues/23862 this is the culprit.

Fixed in Node 11.10
https://github.com/nodejs/node/pull/25993

**Comment by dugite-code** [comment]
Awesome, with the map via MQTT it looks like it's now working as expected.

**Comment by lance36** [comment]
Great work!
