### ISSUE TITLE
No Webinterface

### ISSUE THREAD

**Issue by piscator83** [Hypfer/Valetudo#393]
## Describe the bug
After rockrobo resetted himself I flashed firmware like I always do but after rockrobo tells me that the Flash was successful the webinterface is unreachable.

**Comment by xrolfex** [comment]
You may have to reboot again, or ssh in and start the Valetudo service manually the first time.

**Comment by Hypfer** [comment]
Since there a a _lot_ of working installations, there must be something wrong with your setup.

**Comment by dbeltman** [comment]
If you've been here and ran into a "dead end" like me, it might have to do with the way the firmware was built. 
If you used https://builder.dontvacuum.me/ , double check that you selected the "Preinstall Valetudo" option. After this, Valetudo's interface should show up this time.

**Comment by Export33** [comment]
hi, i had the same problem.
i used `https://dustbuilder.xvm.mit.edu/pkg/s5/v11_001886.fullos.pkg` build the firmware after the robot had reset itself. the flash was successful but i couldn´t connect via the webinterface nor ssh.

using a prebuild firmware without building it myself as stated by @dbeltman worked.
