### ISSUE TITLE
Use robot to build wifi heatmap

### ISSUE THREAD

**Issue by homefefeld** [Hypfer/Valetudo#395]
This is to suggest an enhancement (I didn't know where to post the requirement). 
Please let me know if you would be able to work on it.
I was wondering if we could use the robot to capture/gather wifi information (RSSI, noise, RX/TX rate) while hoovering and build a map with wifi information.
We could then push this data over MQTT and build a very accurate wifi heat map.
This would be very good to have to place the access points in the right location.

<img width="630" alt="image" src="https://user-images.githubusercontent.com/3512839/71321256-12212a80-24b7-11ea-85b9-034eb4d128f5.png">

**Comment by rimrul** [comment]
For some discussion on this topic see rand256/valetudo#44

**Comment by Hypfer** [comment]
Sounds reasonable. I'll await your PR

**Comment by Hypfer** [comment]
This is out-of-scope for the project
