### ISSUE TITLE
How to start a new map? Maps get mixed up.

### ISSUE THREAD

**Issue by bl4k1st** [Hypfer/Valetudo#396]
When using my bot I have to carry it to other rooms, because stairs. How can I start a new map, I notice the maps get mixed up frequently, the next room is put ontop of the current map resulting in a mess.

**Comment by rimrul** [comment]
I can see 2 scenarios where this could happen: 

1. Pausing cleanup, carying the robot and then resuming.

2. Peristent map data is enabled.

In both cases the answer is to avoid that.

**Comment by bl4k1st** [comment]
So you suggest switching off persistent map data?
If so, what is persistent map data good for?

**Comment by rimrul** [comment]
For exactly the thing you don't want in your use case: Making the robot remember the old map and basing navigation partially on that.
