### ISSUE TITLE
[feature request] Option to exclude map from HA autodiscovery

### ISSUE THREAD

**Issue by Dinth** [Hypfer/Valetudo#398]
It would be nice to have an option to exclude map from HA autodiscovery. I still want to use MQTT map with Icantbeliveitsnotvaletudo, but the map is so huge that it crashes HA. Im also struggling to disable it on HA side, as for some reason its not showing up in Entities page, while opening States page with map entity crashes my browser.

**Comment by Hypfer** [comment]
Sounds reasonable. I'll await your PR

**Comment by Hypfer** [comment]
It's not part of the valetudo autodiscovery

https://github.com/Hypfer/Valetudo/blob/4f7ff43bf3ef211f5bf0ea6f41be369bd454c117/lib/MqttClient.js#L213
