### ISSUE TITLE
Device is restarting and boot failure.

### ISSUE THREAD

**Issue by mahirgul** [Hypfer/Valetudo#401]
the device is restarting and saying "boot failure initial version loading please patient" again and again.

How can i access this device and install valetudo or original software.

**Comment by NNMavy** [comment]
This sounds related to #206, sadly I don't think there is a way to access the device as long as it keeps rebooting.

**Comment by lipigab** [comment]
I'm still on original FW and one of my S50 started doing that. I came here to see if installing a custom FW would fix the problem, but I guess it's hardware related :(
I can still reset mine and works fine for a few days but then it goes into this loop.
