### ISSUE TITLE
Wifi LED keeps blinking

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [Hypfer/Valetudo#403]
## Describe the bug
The WiFi led keeps blinking after I connected the vacuum to my WiFi.

## To Reproduce
Just boot the vacuum.
Imagebuilder flags or reboots do not seem to change a thing.

### Vacuum Model
S50 Gen 2

### Valetudo Version
0.4.0

## Expected behavior
Dummycloud changelog says it’s fixed.

## Additional context
I tried using dummycloud, but the imagebuilder says it’s not compatible with valetudo anymore, as valetudo adopted the features of dummycloud.

**Comment by Hypfer** [comment]
Since there a a _lot_ of working installations, there must be something wrong with your setup.
