### ISSUE TITLE
[Feature Request] allow to setup a custom fan speed by MQTT

### ISSUE THREAD

**Issue by Hypnos3** [Hypfer/Valetudo#408]
Currently it seems that only Fan speeds "max", "min",... are supported by MQTT.

Other software (e. g. FloleVac) allows custom fan speed. In the UI these custom Fan speed is visible, and can be changed to the standard. For simplicity this is ok.

The request is that over MQTT the custom fan speed is visible and a custom fan speed can be set.

Thank you!

**Comment by Hypfer** [comment]
Sounds reasonable. I'll await your PR

**Comment by Hypnos3** [comment]
It has now been implemented in Valetudo RE.  Excuse me for taking your time.
