### ISSUE TITLE
Wifi problem

### ISSUE THREAD

**Issue by ricruz** [Hypfer/Valetudo#409]
After rooting the Gen 1 can't connect to any wifi.
Any help?

**Comment by homefefeld** [comment]
did you configure your wifi ? is that your first install ?

reset the wifi (normal procedure), connect with a computer to the roborock wifi, then with a browser connect to 192.168.8.1 , then cha ge the wifi in the setting.

G/

**Comment by ricruz** [comment]
Already done that and can't connect

**Comment by ricruz** [comment]
> did you configure your wifi ? is that your first install ?
> 
> reset the wifi (normal procedure), connect with a computer to the roborock wifi, then with a browser connect to 192.168.8.1 , then cha ge the wifi in the setting.
> 
> G/

Already done that and can't connect

**Comment by MrReSc** [comment]
The robot only supports 2.4GHz Wifi networks. Maybe this is your problem.

**Comment by rumpeltux** [comment]
Doesn’t seem like a bug in Valetudo. You can try to get help on roboter-forum.com.
