### ISSUE TITLE
Installation guide is sligthly borked

### ISSUE THREAD

**Issue by 15goudreau** [Hypfer/Valetudo#410]
## Describe the bug

wget of the latest binary doesn't work well as the instructions aren't clear. If you gitclone the repo, it creates a folder structure with Valetudo in a capital V. The imagebuilder will complain about it and you need to rename to valetudo with lowercase V.

## To Reproduce

git clone the valetudo repo in the valetudo folder and then try running the firmware builder script it will say that ../valetudo doesn't exist

### Vacuum Model
All 

### Valetudo Version
All

## Expected behavior

update instructions to just use git clone and then rename the valetudo with a lowercase V so it doesn't throw an error

**Comment by 15goudreau** [comment]
Second issue I encountered when building the firmware is that it just will straight up ignore the ../valetudo directory when building the firmware. When it is installed valetudo isn't actually installed. I had to install valetudo with the roborock control center app instead.

**Comment by Hypfer** [comment]
Which guide do you mean? There is no git clone of this repo in https://github.com/Hypfer/Valetudo/wiki/Installation-Instructions

**Comment by 15goudreau** [comment]
Hi, I understand there is no git clone command in that guide. However the instructions (for someone who doesn't know linux super well) aren't clear as to how to wget the latest valetudo binary. It just says to use the url with /latest, but if you wget that link it pulls nothing but a like 50 kb file called latest. I think an example url would be more useful than 

```

Download the latest valetudo binary from https://github.com/Hypfer/Valetudo/releases/latest

wget https://github ...
```

Hence why I used git clone to pull the lastest binary, but then the naming convention complained.

**Comment by herrwusel** [comment]
`https://github.com/Hypfer/Valetudo/releases/latest/download/valetudo` should fix the issue of not downloading the actual binary.

**Comment by Hypfer** [comment]
Fixed. Thanks @herrwusel
