### ISSUE TITLE
FW for Roborock S5 max ?

### ISSUE THREAD

**Issue by 1kohm** [Hypfer/Valetudo#412]
Hi, 
i have Roborock S5 max but can't find any information about supported firmware
What FW should I use for  Roborock S5 max device?

**Comment by rimrul** [comment]
The S5 Max is (like the S6 and S4) Gen3. There is no root for Gen3 yet. That means no Valetudo for the S5 Max.

**Comment by 1kohm** [comment]
Thanks for fast and clear answer. What I like the most is "yet" :)
