### ISSUE TITLE
Firefox memory leak in Map View when Robo looses Wifi

### ISSUE THREAD

**Issue by fzinken** [Hypfer/Valetudo#417]
When I am in Map View (using firefox, haven't tested other browser) and the robot looses/switches wifi (drives into an area with different AP) firefox memory usage increases continuously till system OOM.

1. Start a cleanup
2. Open roborock webinterface and chose "Map"
3. Wait till the robot looses/switches wifi connection
4. Watch Memory usage

Vacuum Model: Gen1
Valetudo Version: 0.4.0
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0

Expected behavior: Show a error message and not create OOM

**Comment by Hypfer** [comment]
Since pretty much the whole codebase changed recently, please re-check if this is still an issue in [the latest beta](https://github.com/Hypfer/Valetudo/releases/tag/2021.01.1) and if yes open a new issue.

Thank you!
