### ISSUE TITLE
[viomi branch] Cloud messages aren't handled by Vacuum implementation

### ISSUE THREAD

**Issue by Hypfer** [Hypfer/Valetudo#436]
I've noticed that the map polling speed didn't increase while the robot was working.
This happens, because the code to handle `event.status` messages is in Roborock.js, however the cloud messages arrive in Dummycloud.js, which currently does almost nothing.

What's the plan here, @rumpeltux ?

Do we remove Dummycloud.js and integrate that into the vacuum implementations or do we inject the concrete vacuum implementation's `onMessage` method into it?

**Comment by rumpeltux** [comment]
Dummycloud should already forward the message to the MiioVacuum message handler.
