### ISSUE TITLE
Different firmware wordings - Confused

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [Hypfer/Valetudo#449]
The manual under https://github.com/Hypfer/Valetudo/wiki/Installation-Instructions is talking about different versions of firmware.

I do not know I am having the right one or a wrong one.

Starting with this
"PSA: DO NOT UPDATE YOUR GEN2 TO **1910** & GEN1 TO **4004**"
and then
"Roborock Vacuum Gen2 S50/S51/S55: FW **v11_001886**"

I had a **roborock.vacuum.s5** with the firmware **3.3.9_001768**

Can somebody help me and can we update the wiki?

**Comment by rimrul** [comment]
The important part is the number in the back.

**Comment by rimrul** [comment]
The important part is the number in the back.

**Comment by sorryusernameisalreadytaken** [comment]
> 
> 
> The important part is the number in the back.

okay, THX.
So: **3.3.9 **==** 11**
