### ISSUE TITLE
Firmware Installation fails

### ISSUE THREAD

**Issue by Riseryn** [Hypfer/Valetudo#450]
## Describe the bug
actual factory firmware 3.3.9_003452

Hello I have followed the installation instruction,made a factory reset, but when i want to upgrade the firmware i got this
```
 mirobo --ip 192.168.8.1 --token  68534b4339786276467936d35534a4d73 update-firmware --ip 192.168.1.12 firmware/output/mirobo --ip 192.168.8.1 --token  774c7a35656e52544234465161776f75 update-firmware --ip 192.168.1.12 firmware/output/v11_003468.fullos.pkg
Going to update from firmware/output/mirobo --ip 192.168.8.1 --token  774c7a35656e52544234465161776f75 update-firmware --ip 192.168.1.12 firmware/output/v11_003468.fullos.pkg
INFO:miio.updater:Serving on 0.0.0.0:34161, timeout 10
INFO:miio.updater:Using local firmware/output/mirobo --ip 192.168.8.1 --token  774c7a35656e52544234465161776f75 update-firmware --ip 192.168.1.12 firmware/output/v11_003468.fullos.pkg(md5: 41a584c7f65277d3a055255ecc3151b3)
Hosting file at http://192.168.1.12:34161/mirobo --ip 192.168.8.1 --token  774c7a35656e52544234465161776f75 update-firmware --ip 192.168.1.12 firmware/output/v11_003468.fullos.pkg
Update started!
  0%|                                                                                                | 0/100 [00:05<?, ?it/s]
ERROR:miio.updater:No request was made..

```
vacuum say try updating after the vacuum is at least 20% charged.

but it is fully charged

### Vacuum Model
rockrobo gen 1

**Comment by ASdeWekker** [comment]
Hi, I'm also having this issue while trying to flash the firmware. I'm currently on version 3.3.9_001886.
What did you do to resolve this?

**Comment by ualex73** [comment]
Unless you are a network export, the following is really wrong:
mirobo --ip 192.168.8.1 --token  774c7a35656e52544234465161776f75 update-firmware --ip 192.168.1.12 firmware/output/v11_003468.fullos.pkg

The roborock is using 192.168.8.1 which is a DIFFERENT subnet then 192.168.1.1.12.

The roborock can *NEVER* reach the 192.168.1.12 IP address, there is no default gateway on the roborock. The URL for the firmware *needs* to be in the 192.168.8.XXX range.
