### ISSUE TITLE
Update Guides/Wiki/Documentation

### ISSUE THREAD

**Issue by Hypfer** [Hypfer/Valetudo#482]
* Check existing state and update to current knowledge, goals etc.
* How to build and flash 2008+ firmwares
* How to viomi (probably)
* Anything else?

**Comment by alexkn** [comment]
If someone wants to try, I have used this firmware builder to build firmware 2008:
https://github.com/zvldz/vacuum
With this comandline:
```
./builder_vacuum.sh     --run-custom-script=ALL \
                        --timezone=Europe/Berlin \
                        --ntpserver=pool.ntp.org \
                        --public-key=/root/.ssh/id_rsa.pub \
                        --enable-greeting \
                        --disable-logs \
                        --replace-adbd \
                        --valetudo-path=../Valetudo \
                        --replace-miio \
                        --enable-dns-catcher \
                        -f path_to_firmware_2008.pkg
```

I'm currently not quite sure which parameters should be set.

Flashed as usual with mirobo.
