### ISSUE TITLE
Marking beta versions as pre-release

### ISSUE THREAD

**Issue by boesing** [Hypfer/Valetudo#491]
Hey there,

even if I am not using valetudo (yet), I'd like to encourage you to mark beta versions as `pre-release`. There is a feature for exactly this aswell as a proper semver notation `0.5.0-beta.1` (for example).

This will make it much more clear that 0.5.0 is not the final version but a beta.

Just a suggestion tho. Thanks for your efforts on this!

**Comment by Hypfer** [comment]
The `beta` is just added to it to keep expectations low 😄

It's a full release as full as it can get.

However it might indeed be time to drop that. 0.5.0 should be indication enough that this is not `1.0` finished project.

Ive removed it. Thank you for your feedback!
