### ISSUE TITLE
Home Assistant device info is "unknown"

### ISSUE THREAD

**Issue by definitio** [Hypfer/Valetudo#498]
## Describe the bug
Home Assistant device info is missing.

### Screenshots
![Screenshot_20200430_124248](https://user-images.githubusercontent.com/37266727/80690793-603ae000-8ae0-11ea-9289-86671fff9e4f.png)

### Vacuum Model
Gen1

### Valetudo Version
0.5.0

**Comment by Hypfer** [comment]
What's the value of the `model` key inside either `/mnt/default/device.conf` or `/etc/miio/device.conf`?

**Comment by definitio** [comment]
/mnt/default/device.conf:
`model=rockrobo.vacuum.v1`

**Comment by Hypfer** [comment]
Oh I see.
The S5 reports as `roborock.vacuum.s5`

I didn't notice that they were using `rockrobo` for gen1
