### ISSUE TITLE
Power mode is undefined after 0.5.0 update

### ISSUE THREAD

**Issue by definitio** [Hypfer/Valetudo#499]
### Screenshots
![Screenshot_20200430_141111](https://user-images.githubusercontent.com/37266727/80699422-fbd24d80-8aec-11ea-9a13-f6f927099690.png)

### Vacuum Model
Gen1

### Valetudo Version
0.5.0

**Comment by Hypfer** [comment]
This is probably caused by the slightly different presets on Gen 1.

If you try setting it to your prefered speed again, this should vanish

**Comment by definitio** [comment]
I have tried. It doesn't work.

**Comment by pkishino** [comment]
seeing same issue here, gen1

**Comment by Hypfer** [comment]
What base firmware are you guys on?

I should probably add that to the bug issue template

**Comment by pkishino** [comment]
FW version 3.5.4
FW build 004007

**Comment by Hypfer** [comment]
The raw response to the `get_status` miio command would be very helpful.

There are multiple ways to get that. [python-miio](https://python-miio.readthedocs.io/en/latest/vacuum.html#raw-commands) is one of them

**Comment by pkishino** [comment]
Sending cmd get_status with params []
[{'msg_ver': 8, 'msg_seq': 477, 'state': 8, 'battery': 100, 'clean_time':
0, 'clean_area': 0, 'error_code': 0, 'map_present': 1, 'in_cleaning': 0,
'fan_power': 75, 'dnd_enabled': 1}]

**Comment by Hypfer** [comment]
`'msg_ver': 8`

`if (msg_ver >= 3) {`
https://github.com/Hypfer/Valetudo/blob/04e1720f3c5e4d1061c61781451d9dcd0bfd6fd3/lib/devices/Roborock.js#L375

Okay that's the issue here. But how many msg_ver are there? And why does Gen1 has such a high number

**Comment by pkishino** [comment]
Can this be be manually updated on the robot? Couldn’t find the file :/

**Comment by pkishino** [comment]
For me it seems to have fixed itself..I see the normal power modes now but it’s a bit slow to switch from HA. But it works :)
