### ISSUE TITLE
Add "Mop" to the "Cleanup mode" (fan speed)

### ISSUE THREAD

**Issue by jorsmm** [Hypfer/Valetudo#5]
Apart from "**Quiet**", "**Balanced**", "**Turbo**" and "**MAX**" there is a "**Mop**" Cleanup mode. 
/api/current_status shows `"fan_power":105` in this mode.

Could you please add this option (Mop) to the "Select fan speed" list?

Thanks!!

**Comment by Hypfer** [comment]
After stopping the cleaning process and starting a new one, the robot defaults to a non-mop fanspeed.

However the robots response to `get_status` still incorrectly states `fan_power: 105` 🤔

**Comment by leonardpitzu** [comment]
the fallback to the non-mop fanspeed is what happens also with the xiaomi cloud/original app. if you start a new cleaning process though it is not mopping any more so there might be a bug on ciaomi's side.

**Comment by timbru31** [comment]
Is the 

> After stopping the cleaning process and starting a new one, the robot defaults to a non-mop fanspeed.
However the robots response to get_status still incorrectly states fan_power: 105 🤔

The blocking issue here? Since the 105 has some effect I always have to manually toggle the mop mode.

**Comment by timbru31** [comment]
Added via #213  - can you close this issue @Hypfer ?
