### ISSUE TITLE
MQTT password visible in WebUI

### ISSUE THREAD

**Issue by xoxys** [Hypfer/Valetudo#509]
## Describe the bug
After upgrading to the latest valetudo release we are able to configure mqtt from the UI. While this is pretty cool in general, I'm not really sure if it is a good idea to show the connection credentials/password in clear text to everyone who could access the web frontend... Would be good to have the ability to disable web editing of the mqtt part completely and/or split out the connection URL into different fields without displaying the current password (as it is done for the wifi config site).

### Valetudo Version
0.5.1

**Comment by rumpeltux** [comment]
@TheLastProject FYI in case you want to tackle this too.

**Comment by TheLastProject** [comment]
I mean, to be fair, anyone who can access the vacuum can just call `/api/get_config` which will also show the password in plain text, so it's not like this information wasn't exposed before, but it couldn't hurt to split it up yeah.

To do it properly though, in a way that would make it hideable in the API too, the broker_url config variable would need to be split into multiple values: https://github.com/Hypfer/Valetudo/blob/master/lib/MqttClient.js#L113

Or it should be possible to password-protect the API too?

I'm not opposed to fixing this, but I feel fixing this only in the web UI would give a false sense of security as this is still exposed over the API.

**Comment by xoxys** [comment]
Good point... Was not aware of the API endpoint.
