### ISSUE TITLE
Map is flipped

### ISSUE THREAD

**Issue by metronidazole** [Hypfer/Valetudo#51]
Is anyone else's map flipped, making it difficult to interpret? If I manually flip it (over either axis - vertical preferred though) it looks fine.

I noticed #46 mentioned the issue but I don't see a resolution to this issue there

**Comment by metronidazole** [comment]
Confirmed it's working.

**Comment by d1slact0r** [comment]
I can confirm that my map is flipped again on 3.0 ;) @fcktrmp

**Comment by Hypfer** [comment]
This is the correct orientation which is also displayed in the mihome app.

**Comment by d1slact0r** [comment]
It is not, in mihome it is flipped or rather yet in valetudo it is flipped ;) my 2e room in the mihome app is right (like my actually floor plan) and in Valetudo it is left

**Comment by Hypfer** [comment]
`I am watching it on my 5K Imac though 27 inch`

Thats.. great?
Hm. If it's a gen1 Vacuum maybe the map flipping is different. iirc I heard something like that before

**Comment by d1slact0r** [comment]
> `I am watching it on my 5K Imac though 27 inch`
> 
> Thats.. great?
> Hm. If it's a gen1 Vacuum maybe the map flipping is different. iirc I heard something like that before

I meant more that the resolution is pretty big and maybe that is why it is not working like it is supposed to be? Using chrome btw and a gen2 ;)

**Comment by Hypfer** [comment]
So it's horizontally flipped?

**Comment by d1slact0r** [comment]
> So it's horizontally flipped?

yep that is correct :) sorry still working on rooting it and including it in mqtt so I do not have an example as of now, but it is horizontally flipped yes.
