### ISSUE TITLE
Wiki should include upgrade instructions

### ISSUE THREAD

**Issue by Wolf6660** [Hypfer/Valetudo#512]
how can I update form Valetudo 0.4 to 0.5.1?

thanks

Daniel

**Comment by Hypfer** [comment]
![image](https://user-images.githubusercontent.com/974410/81428347-6ffb9980-915c-11ea-97a9-e89163b8d4ba.png)
![image](https://user-images.githubusercontent.com/974410/81428351-712cc680-915c-11ea-9dc7-1d8d8fb7fc32.png)


Why won't anyone read that. I just don't understand

**Comment by rumpeltux** [comment]
Rephrased it as a bug ;-)

**Comment by bmansvk** [comment]
I have the same question. There is no info how to upgrade to the new version of Valetudo. I think that building vacuum image from the scratch is not required, because of already working SSH access. 

Is is sufficient to replace "valetudo" binary from the new release in a vacuum?

**Comment by alexkn** [comment]
Yes, it is sufficient to replace the binary, as long as you not want to update the firmware anyway.

Just stop valetudo before.
Depending on firmware:
`/etc/init/S11valetudo stop`
or
`service valetudo stop`

**Comment by Hypfer** [comment]
Depending on your setup, it may or may not be necessary to reflash completely.

Since there might be new changes/fixes in the image builders, it is however recommended to so

**Comment by Hypfer** [comment]
https://hypfer.github.io/Valetudo/pages/general/upgrading.html
