### ISSUE TITLE
Iphone X Support

### ISSUE THREAD

**Issue by leonardpitzu** [Hypfer/Valetudo#53]
please add

<meta name="viewport" content="width=device-width, height=device-height, viewport-fit=cover, initial-scale=1.0"> -> makes it look good on the iphone x (otherwise the bottom bar is covered by the ios control bar)

<link rel="apple-touch-icon" href="icon.png"> -> adds an icon to the web app on the ios launcher

**Comment by Hypfer** [comment]
The icon should be fixed in 0.0.8

**Comment by leonardpitzu** [comment]
this should fix the iPhone X portrait aspect/touch areas without creating problems on other devices.

if (ons.platform.isIPhoneX()) {
  document.documentElement.setAttribute('onsflag-iphonex-portrait', '');
}

**Comment by Hypfer** [comment]
Fixed with 0.2.0
