### ISSUE TITLE
Map changes despite lab mode being turned on

### ISSUE THREAD

**Issue by BarrettLowe** [Hypfer/Valetudo#533]
## Describe the bug

I have turned persistent data on, reset the map, and did a full clean so that my robot could get the layout of the house. That map may last a couple of (zoned cleanup) runs but then rotates and seems to get deleted. Rooms are missing, zones are wrong etc.

### Vacuum Model

S5

### Valetudo Version

0.5.2

### Firmware Version

001886

## Expected behavior

The map gets saved and does not rotate so that zones are consistent and repeatable

## Additional context

I'm happy to provide debug output but am unsure of where to get it or what's helpful

**Comment by Hypfer** [comment]
This is not an issue with valetudo but rather with the roborock software itself.
Since Valetudo is merely an app/cloud replacement, we can't do anything about that nor give any support in this issue tracker
