### ISSUE TITLE
Gen 1 support

### ISSUE THREAD

**Issue by LemarinelNet** [Hypfer/Valetudo#54]
Hi

This project is awesome !
I did not tried yet, since I have a gen 1 robot.
As I can read, it is only for Gen 2 robots ? Which limitations are leading to this ?
Can I help porting to gen 1 ?

**Comment by Hypfer** [comment]
It does work with Gen1 robots, I just don't know the last Gen1 firmware revision which uses the old map format.

I guess I should update the readme to be more clear

**Comment by LemarinelNet** [comment]
I could get the map from my V1 rooted robot, then converted it on my PC.
Do you think it will suffice to make it work ?

**Comment by Hypfer** [comment]
Just install a supported Gen1 Firmware and everything should be fine
