### ISSUE TITLE
Building valetudo for viomi fails with pkg@4.4.8 and pgk-fetch@2.6

### ISSUE THREAD

**Issue by jeste76** [Hypfer/Valetudo#541]
I tried to build valetudo with ``npm run build_viomi`` as stated in the installation manual. However, npm installed pkg@4.4.8 and pgk-fetch@2.6. I guess these are used for the normal ``npm run build`` command for the non-viomi devices. 

I was able to build valetudo for viomi after downgrading to pkg@4.3.7 and pgk-fetch@2.5.

**Comment by Hypfer** [comment]
You should be able to use the regular valetudo binary since the node version is now statically linked.

The documentation needs to be updated
