### ISSUE TITLE
Roborock: Add "Indicator Light" LED disable feature

### ISSUE THREAD

**Issue by Hypfer** [Hypfer/Valetudo#553]
Controlled by miio command `set_led_status` and fetched with `get_led_status`, a value of `0` means that the indicator LEDs will be disabled if the robot is docked and fully charged.

This is represented by roborock feature flag `119`

Official App screenshot:
![image](https://user-images.githubusercontent.com/974410/86536811-d0078580-beea-11ea-8776-8b0e70282a36.png)

**Comment by ccoors** [comment]
Which capability would this be? The `LEDControlCapability` does not seem to be the right one (at least in its current state). Maybe adding flags to it? Or inventing a new `IndicatorLightControlCapability`?

**Comment by Hypfer** [comment]
Indeed the `LEDControlCapability` doesn't really make sense how it is now and can probably be removed.

This feature is more like the simple carpet mode toggle and unsurprisingly can also be found right above that in the official app
![image](https://user-images.githubusercontent.com/974410/112116023-23754d00-8bba-11eb-9785-56a5619f2f2c.png)


We could probably refactor both to a common base class `BooleanSettingsControlCapability`, however given that there is basically no code in all of them, that hierarchy almost feels like a university java project
