### ISSUE TITLE
Zones go missing when adding new zones from scratch

### ISSUE THREAD

**Issue by fxeller** [Hypfer/Valetudo#557]
Steps to reproduce:

- Just pull the latest master-build
- fire it up with no initial data (no zones that is)
- add two zones, but don't edit them!!!
- switch to home and back to zones

Result:

Only the second zones is shown, the first one is gone.

Cause for problem:

The new zoneId is set to null when no zones are present on the system.

Additional info:
If you add the first zone, go to zone map and back, then add the second zone, got to zone map and back, the zones stay where they are.

**Comment by Hypfer** [comment]
Should work in the latest master. At least somewhat
