### ISSUE TITLE
Mouseover Button description

### ISSUE THREAD

**Issue by wbuh123** [Hypfer/Valetudo#561]
Just as suggestion to improve first time user experience:
I think it would be very helpful, to add mouse over descriptions to the GUI Buttons.
It's not self-explaining to first time users, what the function of these buttons is
![grafik](https://user-images.githubusercontent.com/48272763/87770242-0f08d580-c81f-11ea-872c-dd2f8e822758.png)

**Comment by lukyjay** [comment]
The current UI framework doesn't seem to allow it: https://onsen.io/v2/api/js/ons-fab.html

You could update the icons with text on them but it won't look very good.

This issue a year old, can it be closed?
