### ISSUE TITLE
'Paused' state reported incorrectly

### ISSUE THREAD

**Issue by definitio** [Hypfer/Valetudo#571]
## Describe the bug

Valetudo 0.6.0 sends to state topic "paused resumable" when pause is enabled. It's [not supported in Home Assistant](https://www.home-assistant.io/integrations/vacuum.mqtt/#state-mqtt-protocol). Correct state is `paused`.

### Vacuum Model

Gen 1

### Valetudo Version

 0.6.0

### Firmware Version

4018

### User-Agent

Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0

## Expected behavior

Entity state in Home Assistant should change to `paused`.

**Comment by Hypfer** [comment]
https://github.com/Hypfer/Valetudo/blob/039b7411325b74c2b4abbe58a91134fd1d1b9982/lib/MqttClient.js#L308-L310

I have absolutely no idea _why_ I did that. It doesn't even remotely make sense.

Thank you for reporting
