### ISSUE TITLE
Feature request: Support Dreame F9 vacuum

### ISSUE THREAD

**Issue by urbatecte** [Hypfer/Valetudo#587]
Dreame F9 vacuum get lauched beginning of this year.
Could be nice to be supported in Valetudo ;o)

Miio ID is **dreame.vacuum.p2008**

If you need other data, as far as I can do it, I'll be happy to help.

**Comment by Hypfer** [comment]
Why is it so hard for people to use the issue templates properly? I just don't understand.

**Comment by urbatecte** [comment]
You may laught at me if I tell you that I carrefully read the template and was a bit confused regarding my request.
Sorry for that.

**Comment by Hypfer** [comment]
Looks like they've changed a lot for the F9 so it won't be possible to simply take the 1C implementation and be done with it

**Comment by urbatecte** [comment]
Ok, should I keep the PR open just in case ?
Otherwise I'll close it.
Thanks for your work !

**Comment by rumpeltux** [comment]
Can you link the PR here? I didn’t see it.

**Comment by urbatecte** [comment]
Sorry my bad, due to proffessionnal habit (problem report) I mean do you want me to let the issue open ?

**Comment by rumpeltux** [comment]
We’ll need a developer owning such a device to implement the core functionality and open a respective Pull Request.
Closing until then.

**Comment by bigdx** [comment]
Is there any progress? As Dennis website states rooting is possible and a firmware (valetudo support) avialable... but, I cant find any files or further informations :-/

**Comment by Hypfer** [comment]
As of now, there's no public root available and neither has any work happend on supporting the F9 in Valetudo.

What has been done however is work to make it easier to support new Vacuums so when that is finished, it should also be much easier to add support for the F9.

There aren't any ETAs for either though

**Comment by bigdx** [comment]
> As of now, there's no public root available and neither has any work happend on supporting the F9 in Valetudo.
> 
> What has been done however is work to make it easier to support new Vacuums so when that is finished, it should also be much easier to add support for the F9.
> 
> There aren't any ETAs for either though

Ah ok ... Maybe I was a little to enthusiastic after I have read "yes" next to rootable and valetudo ;-)
I guess the same applies to the S5 Max, right?

**Comment by Hypfer** [comment]
Yes

**Comment by bigdx** [comment]
Ahm, and Xiaomi MiJia 1C too? Cant find files or installation- or rooting-instructions ...

**Comment by Hypfer** [comment]
Yes. And that's definitely nothing that belongs in this issue
Honestly, you could've deduced that by thinking about the previous two questions.

**Comment by Hypfer** [comment]
The miot spec looks pretty much identical to the D9, for which support was added by me very recently.

_If_ the map format behaves the same as on the D9, this could be a very easy addition maybe very soon

**Comment by Hypfer** [comment]
The map format _is_ the same as on the D9 (and the 1C for that matter).

It's basically the same robot without Lidar

**Comment by Hypfer** [comment]
4fe0ff7fd952533a073cd51432626f99aeadd856

Untested, but we'll find out soon

**Comment by maluueu** [comment]
Anything new ?
