### ISSUE TITLE
Feature request: Bring back generated maps back

### ISSUE THREAD

**Issue by Dinth** [Hypfer/Valetudo#588]
Hi. About a year ago, generated maps were replaced by mqtt maps which contain a textual description of the map and can be used to generate one. 
This being said, while mqtt maps are great for some of the use cases - like live view generated in Home Assistant, there are some cases - for example a notification of last job completed with a map, where a simple png of last job would be perfect, but mqtt map adds a lot of hassle and steps where things can go wrong. It would be great to have both features at the same time.

**Comment by Hypfer** [comment]
Map generation has been moved to a seperate application because it required too many resources on the vacuum.

Newer vacuums feature even worse hw specs so there's really no point in re-adding it, I'm afraid.
