### ISSUE TITLE
Zone names not found

### ISSUE THREAD

**Issue by Schattenruf** [Hypfer/Valetudo#589]
Hi,

I don't know if it is a bug or just a misunderstanding from me.
I added different zones:

![image](https://user-images.githubusercontent.com/12720317/91214519-79ad0b00-e713-11ea-82ee-da9046940ad2.png)

And edited them where they are.
If I select one and want my robby to clean there it just says:
![image](https://user-images.githubusercontent.com/12720317/91214575-8e899e80-e713-11ea-892e-c6fae7fde398.png)

If I delete all these zones and just have one there it also states this error so I think it does not depend on how many I have created...

How can I fix this?
My robby is a Roborock S50 vith Firmware 1886 and Valetudo 0.6.1

Thanks :)

**Comment by rumpeltux** [comment]
How did you edit their location? What’s the contents of your `valetudo.conf`?

**Comment by Schattenruf** [comment]
Well nothing special. I added one simple room and clicked on the "+" and saved. I could always open it up and it has been saved correctly.
But the starting did not work.

**Comment by Hypfer** [comment]
Should be fixed now 🤔
