### ISSUE TITLE
Root Password S50 FW 2008

### ISSUE THREAD

**Issue by Schattenruf** [Hypfer/Valetudo#590]
Hey guys just a quick question,

before FW 2008 (with 1886 to be exact) I could log in with my ssh-certificate and my password.
Now he always states "Permission denied" but I gave it in correctly.

The firmwarepackage was from dontvacuum.me/

Is there any new root password for FW 2008, that I do not know?

Thanks in advance :)

**Comment by Hypfer** [comment]
Newer firmwares feature an sshd which doesn't support the ed25519 keypairs used previously.

Also, this issue tracker is not for support requests. Please direct them elsewhere.

**Comment by Schattenruf** [comment]
@Hypfer Danke trotzdem :) Wusste das nicht
