### ISSUE TITLE
Home-Button in Webinterface not working

### ISSUE THREAD

**Issue by Surfer2010** [Hypfer/Valetudo#593]
## Describe the bug
clicking on the "Home" button on the main screen in the web interface nothing happens. No reaction of the vacuum at all. (no stopping, no voice output, no going home or scanning for the station)

### Vacuum Model
Gen1 Roborock Xiaomi

### Valetudo Version
0.6.1

### User-Agent
Chrome

## Expected behavior
clicking on the "Home" button on the main screen in the web interface i would expect the vacuum to go back to the docking/charging station

**Comment by rumpeltux** [comment]
To help debug this further. Please set logging to `trace` in `valetudo.conf` and attach the output. Also enable developer console in chrome and paste any errors you may see there.
