### ISSUE TITLE
RFE - disable physical buttons on S5

### ISSUE THREAD

**Issue by rvdblink** [Hypfer/Valetudo#597]
To start, no idea if this is Valetudo or the Roborock software itself, but giving it a shot

Scenario: 
Sometimes - and with two little kids always in our household - the Roborock S5 is paused by using the physical buttons, while this is wanted. 

Feature request:
A setting to disable the physical buttons. Preferably with a 10 second (hard) press to reboot / shutdown still possible.

**Comment by Hypfer** [comment]
This is pretty much impossible without patching the roborock software and definitely out of scope for valetudo.

As a hardware solution, you could try taping a piece of cardboard or similar over the buttons so that they cannot be pressed 🤔
