### ISSUE TITLE
Hosting Valetudo on a standalone web server

### ISSUE THREAD

**Issue by nuc134r** [Hypfer/Valetudo#60]
Readme says this tool is supposed to be hosted on a vacuum itself. And also that Valetudo only guaranteed to run properly with certain rooted firmware versions. 

The question is: How hard will it be to make it run on a standalone server, not a vacuum? 

I don't want to downgrade firmware and root my robo. Should I start developing my own Web interface to control it? Or there is a chance this already developed and maintenaned tool can be patched to be used with stock device? Is Valetudo tied with some functionality that only can be reached locally on vacuum?

**Comment by Hypfer** [comment]
This use case is not supported and will not be supported.

Valetudo uses functionality apart from the miio protocol. (All the map stuff, all the version stuff, etc.)
