### ISSUE TITLE
Reconnecting to MQTT broker takes hours after connection lost

### ISSUE THREAD

**Issue by definitio** [Hypfer/Valetudo#605]
## Describe the bug

Valetudo needs hours to reconnect to MQTT broker after connection lost. Web interface also doesn't work.
## To Reproduce
1. Stop MQTT broker
2. Wait a few minutes (it may not be necessary)
3. Wait until Valetudo will connect to broker again

### Screenshots

![Screenshot_20200925_183207](https://user-images.githubusercontent.com/37266727/94280319-4eaa1700-ff5e-11ea-94c5-a65337ee3630.png)

### Vacuum Model

Gen1

### Valetudo Version

0.6.1

### Firmware Version

4018

## Expected behavior

It should take seconds or minutes.

## Additional context
`netstat -tulpn`
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:5037          0.0.0.0:*               LISTEN      417/adbd
tcp        0      0 127.0.0.1:54322         0.0.0.0:*               LISTEN      31022/miio_client
tcp        0      0 127.0.0.1:54323         0.0.0.0:*               LISTEN      31022/miio_client
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1480/sshd
tcp        0      0 0.0.0.0:7777            0.0.0.0:*               LISTEN      1168/perl
tcp        0      0 0.0.0.0:55553           0.0.0.0:*               LISTEN      460/xdnsmasq
tcp        0      0 0.0.0.0:199             0.0.0.0:*               LISTEN      397/snmpd
tcp        0      0 0.0.0.0:6665            0.0.0.0:*               LISTEN      854/player
tcp6       0      0 :::22                   :::*                    LISTEN      1480/sshd
tcp6       0      0 :::55553                :::*                    LISTEN      460/xdnsmasq
udp        0      0 0.0.0.0:161             0.0.0.0:*                           397/snmpd
udp        0      0 0.0.0.0:55553           0.0.0.0:*                           460/xdnsmasq
udp        0      0 0.0.0.0:6665            0.0.0.0:*                           854/player
udp        0      0 0.0.0.0:29732           0.0.0.0:*                           1669/dhclient
udp        0      0 0.0.0.0:54321           0.0.0.0:*                           31022/miio_client
udp        0      0 0.0.0.0:68              0.0.0.0:*                           1669/dhclient
udp6       0      0 :::2127                 :::*                                1669/dhclient
udp6       0      0 :::55553                :::*                                460/xdnsmasq
```
`/var/log/upstart/valetudo.log`
```
[2020-09-25T07:18:07.403Z] [INFO] Starting Valetudo for Vacuum Model rockrobo.vacuum.v1
[2020-09-25T07:18:07.404Z] [INFO] DeviceId 259770451
[2020-09-25T07:18:07.405Z] [INFO] IP 127.0.0.1
[2020-09-25T07:18:07.406Z] [INFO] CloudSecret <...>
[2020-09-25T07:18:07.410Z] [INFO] LocalSecret <...>
[2020-09-25T07:18:07.410Z] [INFO] JS Runtime Version v14.4.0
[2020-09-25T07:18:07.412Z] [INFO] Max Heap Size: 33.5 MiB
[2020-09-25T07:18:08.014Z] [INFO] Dummycloud is spoofing 203.0.113.1:8053 on 127.0.0.1:8053
[2020-09-25T07:18:08.018Z] [INFO] Webserver running on port 80
[2020-09-25T07:18:08.159Z] [INFO] Cloud connected
```

**Comment by Hypfer** [comment]
When was the firmware built?

**Comment by definitio** [comment]
28.07.2020

**Comment by Hypfer** [comment]
This behaviour was caused by an invalid valetudo start script.

Commits to fix this were added on the 10.6.2020
https://github.com/zvldz/vacuum/commit/298a0c35d797c58476a3ed8b8e2b1b8640ce94f9#diff-97ec49e0e3b6e41ecb330776387add14

Depending on whether or not you've pulled the latest image builder, you may not have those.


So basically what happened there is that the script killed valetudo hard with no way to properly shutdown and the old mqtt connection timed out _after_ the new one was established, which caused the availability topic to receive the last will of the old connection, overwriting the new "online" status.

Please check your `/etc/init/S11valetudo` for a `-9` flag for the `killall` command

**Comment by Hypfer** [comment]
![image](https://user-images.githubusercontent.com/974410/94313916-e2400f80-ff7f-11ea-8255-7156b20c29ad.png)

I can restart my mqtt broker multiple times and it always reconnects properly

**Comment by definitio** [comment]
I can restart broker too and it will reconnect, but if I disable broker for 5 minutes it will never connect again.

**Comment by Hypfer** [comment]
Since pretty much the whole codebase changed recently, please re-check if this is still an issue in [the latest beta](https://github.com/Hypfer/Valetudo/releases/tag/2021.01.0b0) and if yes open a new issue.

Thank you!
