### ISSUE TITLE
[Viomi V8] there is no possibility to resume cleaning after pause from Valetudo level

### ISSUE THREAD

**Issue by petec999** [Hypfer/Valetudo#617]
After pressing 'pause', vacuum is in 'pause' in valetudo. However if I resume it - pressing 'start' in valetudo or on vacuum, it always starts full cleaning.

**Comment by petec999** [comment]
duplicate of https://github.com/Hypfer/Valetudo/issues/594

**Comment by Hypfer** [comment]
https://github.com/Hypfer/Valetudo/issues/594

Please check the issue tracker for existing issues before opening a new one.

Also, don't simply delete the issue template. You need to fill out all provided fields.

Failure to do so will result in a ban. This will be the only warning
