### ISSUE TITLE
[viomi v8] 'Find' is not working

### ISSUE THREAD

**Issue by petec999** [Hypfer/Valetudo#618]
## Describe the bug
Pressing 'Find' in UI doesn't work.

## To Reproduce

Go to Main Menu in UI, press 'Find'
You should here sound 'I am here' from vacuum

### Vacuum Model
Viomi V8

### Valetudo Version
0.6.1

### Firmware Version
3.5.3_0017

### User-Agent

To here sound 'I am here' from vacuum

## Additional context
not urgent in any way, rather only a feature, but exists.

**Comment by Hypfer** [comment]
It's mentioned in the docs so its not a bug

https://valetudo.cloud/pages/installation/viomi.html
