### ISSUE TITLE
Error decription is missing in state payload

### ISSUE THREAD

**Issue by definitio** [Hypfer/Valetudo#622]
## Describe the bug

"Error" key is missing in state payload. It contained error description few months ago.

### Vacuum Model

Gen 1

### Valetudo Version

0.6.1

### Firmware Version

4018

## Expected behavior

I want to get error description and send notification with it via Home Assistant. It's worked for me before.

**Comment by Hypfer** [comment]
Since pretty much the whole codebase changed recently, please re-check if this is still an issue in [the latest beta](https://github.com/Hypfer/Valetudo/releases/tag/2021.01.0b0) and if yes open a new issue.

Thank you!
