### ISSUE TITLE
If you enter the wrong MQTT address, Valetudo GUI does not restart 

### ISSUE THREAD

**Issue by fallenruby** [Hypfer/Valetudo#629]
## Describe the bug
As the title, if you enter the wrong MQTT address, Valetudo service does not restart:
`[2020-11-20T22:14:05.201Z] [INFO] Webserver running on port 80
[2020-11-20T22:14:05.219Z] [ERROR] MQTT error: Error: getaddrinfo ENOTFOUND 192..168.2.115`

In my case, I've inserted 2 dots in my address:  **192..168.2.115**

so I had to SSH into the vacuum, edit `/mnt/data/valetudo/config.json`, insert the correct address, and restart the service `root@rockrobo:/etc# valetudo`

## To Reproduce
1. Go to 'Settings' in the GUI
2. Compile 'MQTT' settings, save, but entered a wrong address by mistake
3. Reboot the robot by pressing the Home button for 5 sec.
4. Can't access the GUI and I've forced to SSH and restart the service

### Vacuum Model
rockrobo.vacuum.v1

### Valetudo Version
0.6.1

### Firmware Version
3.5.8_004018

## Expected behavior
The GUI should have some controls on the address field, and be able to flash a 'Wrong address' error

**Comment by Hypfer** [comment]
Since pretty much the whole codebase changed recently, please re-check if this is still an issue in [the latest beta](https://github.com/Hypfer/Valetudo/releases/tag/2021.01.0b0) and if yes open a new issue.

Thank you!
