### ISSUE TITLE
MiioTimeoutError viomi does not always respond to MQTT commands

### ISSUE THREAD

**Issue by Ramsei** [Hypfer/Valetudo#632]
## Describe the bug
I get MiioTimeoutError in the Valetudo web interface, for the same reason, commands are sent via MQTT after 5 or 8 attempts.

## To Reproduce
The error appears immediately after logging into the valetudo web interface. If you reload the page several times, the error disappears and then reappears.

This error appeared from the very beginning of installing valetudo on my viomi v.7
I tried hard resetting the robot and reinstalling valetudo, but it didn't help. I also checked the quality of the connection, it is excellent and does not cause problems.

I went ahead and installed miiocli, tried to execute commands to the robot (info and status), sometimes the command was executed with a delay of 5-6 seconds, and sometimes it immediately returned the result. Probably in valetudo you can increase the timeout, tell me how to do it? Or tell me how else to solve my problem?

 

### Screenshots
![2020-12-13_00-16-32](https://user-images.githubusercontent.com/13836073/102027229-c21c3180-3db3-11eb-8c46-5d45235a90bb.png)

### Vacuum Model
viomi v.7

### Valetudo Version
0.6.1

### Firmware Version
3.5.3_0047

## Additional context
Probably because of this error, the control via MQTT works very badly, the commands are not executed the first time, sometimes it takes 5 or 8 times to execute the command for the robot to start working.

**Comment by Hypfer** [comment]
Since pretty much the whole codebase changed recently, please re-check if this is still an issue in [the latest beta](https://github.com/Hypfer/Valetudo/releases/tag/2021.01.0b0) and if yes open a new issue.

Thank you!
