### ISSUE TITLE
HHTP Authentication Settings - default pw

### ISSUE THREAD

**Issue by faceforfpv** [Hypfer/Valetudo#633]
## Describe the bug

When enabling HTTP Authentication in the Settings, the default password gets set to Valetudo, which is fine in itself, but having some kind of indication that this is the case would be good and would prevent people from getting locked out.

## To Reproduce

Steps to reproduce the behaviour:
1. Go to 'Settings'
2. Click on 'Access Control'
3. Click on "Enabled' without entering a new password
4. Password gets set to Valetudo

### Vacuum Model
Viomi v8, but I imagine is would be the same for all supported vacuums

### Valetudo Version
0.6.1 

## Expected behaviour

Some kind of indication in the GUI that the default password is Valetudo

**Comment by Hypfer** [comment]
![image](https://user-images.githubusercontent.com/974410/103207132-dc9af280-48fd-11eb-968c-6e0ac05fdf68.png)

Should be fixed in the upcoming merge of #584

Thank you for pointing this out :)
