### ISSUE TITLE
Error 1

### ISSUE THREAD

**Issue by uPagge** [Hypfer/Valetudo#637]
Hello

A week after the update to 0.10.0, I decided to start the vacuum cleaner. I saw that it was no longer available via IP, I decided to launch it by clicking the button, to which I received an answer: error 1. At the same time, the lidar stopped rotating, could it be somehow connected with the update or a problem in the hardware?

I checked the motor that drives the lidar by connecting external power, it works.
But when it is inserted into the vacuum cleaner, it does not rotate even if the belt is removed from it.
I also do not understand why the control interface stopped opening

I described my problem and what I did in more detail, perhaps this will help to understand.

https://blog.upagge.ru/en/posts/guide/smart_home/roborock_error_one/

**Comment by Hypfer** [comment]
- Completely ignoring issue templates
- Completely ignoring the fact that this issue tracker is not for support
- Completely ignoring that there is no Valetudo 0.10.0
- Complaining in the Valetudo issue tracker about issues with some fork (Valetudo RE)
- Complaining in the Valetudo issue tracker about hardware issues
- Linking to their own blog for some reason
- Writing angry emails after being banned for misbehaving

10/10 Would become a foss maintainer again
