### ISSUE TITLE
Resume Zone Cleaning doesn't work (Roborock S50 Gen2)

### ISSUE THREAD

**Issue by ottelo9** [Hypfer/Valetudo#639]
## Describe the bug

I created a zone and start a zone cleanup. Robo starts the cleaning ... then I press pause, robo says "paused". If I try to resume the zone cleanup the robo starts a completely new cleaning cycle without zones (robo is displayed at home for few seconds and then correctly displayed where it should be). If I try to resume via pause button nothing happens.

## To Reproduce
1. Go to Start Page of Valetudo and start zone cleanup
2. wait few seconds then press pause
3. press Start -> Dont resume, press Pause -> nothing happens

### Screenshots

![2021-01-02 16_49_12-Window](https://user-images.githubusercontent.com/33122175/103460915-9b01b180-4d1a-11eb-845e-5ce91b8338e4.png)
![2021-01-02 16_49_35-Window](https://user-images.githubusercontent.com/33122175/103460916-9b9a4800-4d1a-11eb-8239-c552343f4332.png)
![2021-01-02 16_49_51-Window](https://user-images.githubusercontent.com/33122175/103460917-9b9a4800-4d1a-11eb-89eb-e7bccd60260d.png)

### Vacuum Model

Gen2/S50

### Valetudo Version

0.6.1

### Firmware Version

2008

### User-Agent

Version 87.0.4280.88 (Offizieller Build) (64-Bit)

## Expected behavior
Press pause, then press start to resume zone cleanup.

**Comment by Hypfer** [comment]
Since pretty much the whole codebase changed recently, please re-check if this is still an issue in [the latest beta](https://github.com/Hypfer/Valetudo/releases/tag/2021.01.0b0) and if yes open a new issue.

Thank you!
