### ISSUE TITLE
[RELEASE] Provide tarball or zip with binary including deployment dir

### ISSUE THREAD

**Issue by cryptomilk** [Hypfer/Valetudo#64]
Hi,

could you please provide a zip or tarball for releases which contain the binary + the deployment directory. Like in the soruce directory when you compile it:

```
+ valetudo
+ deployment
 \ - Readme.md
   - valetudo.conf
```

This way I could add a --valetudo-path to the imagebulider.sh of dustcloud and directly add it when building the firmware.

Thanks.

**Comment by Hypfer** [comment]
Maybe it would be better to provide a .deb package for easy installation/upgrades 🤔

**Comment by cryptomilk** [comment]
Would also be possible :-)

**Comment by cryptomilk** [comment]
But then we should have all together, dummycloud and valetudo.

**Comment by Hypfer** [comment]
stale
