### ISSUE TITLE
No Wifi connection possible.

### ISSUE THREAD

**Issue by gn4rlymax** [Hypfer/Valetudo#642]
## Describe the bug

When updating from 0.5.0 to 0.6.1 (with reset to stock firmware in between), after connecting to 192.168.8.1 and giving the vacuum (Roborock S5) my SSID and password, it never connects to my Wifi afterwards. Wifi LED keeps blinking fast and my router doesn't show the connection of the vacuum. After downgrading to 0.5.0 again, everything is fine.

## To Reproduce

1. Install Valetudo 0.6.1
2. Connect to 192.168.1.8
3. Save SSID and password
4. Wifi doesn't connect, Wifi LED keeps blinking fast

### Vacuum Model

Roborock S5

### Valetudo Version

0.6.1

### Firmware Version

2008

### User-Agent

Mozilla Firefox 84.0.1 (Windows)
Google Chrome 87.0.4280.101 (Android)

## Expected behavior

A connection to my Wifi.

**Comment by Hypfer** [comment]
I can assure you that this is not a Bug in Valetudo, since there are a plethora of S5 running Valetudo 0.6.1 out there, which can be joined to a wifi network with no issues at all.
