### ISSUE TITLE
35c3

### ISSUE THREAD

**Issue by matthiasharrer** [Hypfer/Valetudo#67]
Hi all,

is anybody of you attending this years chaos communication congress?

**Comment by Hypfer** [comment]
Yup, I will arrive this evening

**Comment by matthiasharrer** [comment]
I will arrive tomorrow morning. If you've got some spare time I would be happy to meet you and maybe work on some valetudo related improvements :)

**Comment by Hypfer** [comment]
DECT 3520

**Comment by matthiasharrer** [comment]
Tried to call you without any luck :/

**Comment by Hypfer** [comment]
Sorry, the phone was muted

**Comment by Hypfer** [comment]
11:30-12:00
