### ISSUE TITLE
Firefox not showing webpage (blank page)

### ISSUE THREAD

**Issue by deku-m** [Hypfer/Valetudo#674]
## Describe the bug

When going to the valetudo webpage with firefox. Firefox isnt showing the page completly.
Only shows hamburger menu icon, home and below navitgation. The rest of functions arent shown.
Looks like error in js file for firefox?

## To Reproduce

1. Go to Firefox
2. Got to ip of valetudo interface
3. See blank page.
4. See error with debugger console. (added as image)

### Screenshots

![Knipsel](https://user-images.githubusercontent.com/37069737/106585376-9281de00-6547-11eb-9694-f682ebef1604.PNG)
![Knipsel2](https://user-images.githubusercontent.com/37069737/106585378-931a7480-6547-11eb-9a75-2c8b0ca61140.PNG)

### Vacuum Model

Xiaomi Miija STYJ02YM 

### Valetudo Version

2021.01.1
### Firmware Version

2021.01.1

### User-Agent

Firefox 85.0 / Win10
## Expected behavior

If possible to see a working display on firefox.

## Additional context

Workaround is to use Edge

**Comment by Hypfer** [comment]
Development is done using Firefox on W10 so this should definitely work.

Maybe there are Add-Ons interfering? Unstable network connection? Try a hard refresh (ctrl + f5) and please also check the network tab for possibly missing resources

**Comment by deku-m** [comment]
Thanks Hypfer for the fast response and help pointing me to the solution.
Its because my anti-virus is scanning/interfering the js files that i didnt know about.

**Comment by Hypfer** [comment]
Just for reference: Which antivirus software is it?

**Comment by deku-m** [comment]
Kaspersky Antivirus. Located under network settings. 
I disabled scan secure traffic and inject script into webtraffic.

In the debug on webconsole of firefox there is mentioning a kaspersky... js file.
