### ISSUE TITLE
Missing zone cleaning capability in viomi.v8

### ISSUE THREAD

**Issue by maxbischoff** [Hypfer/Valetudo#679]
## Describe the bug

After upgrading to 2021.01.1 my `Xiaomi Mijia STYTJ02YM` doesn't display the Option to edit zones in the Zones tab anymore. When switching to the Zobes tab, I am getting following two errors on the bottom: `Cannot GET /api/v2/robot/capabilities/ZoneCleaningCapability/presets_legacy` and then `Cannot GET /api/v2/robot/capabilities/GoToLocationCapability/presets_legacy`. I think the latter one is related to the spot cleaning feature, which never worked on my vacuum.

## To Reproduce

1. Go to the Zones tab
2. Observe the error `Cannot GET /api/v2/robot/capabilities/ZoneCleaningCapability/presets_legacy` pop up
3. Observe the error `Cannot GET /api/v2/robot/capabilities/GoToLocationCapability/presets_legacy` pop up
4. Observe the missing button

### Screenshots

![zones tab](https://user-images.githubusercontent.com/12122170/107117402-6ed9d300-687a-11eb-9e86-79fde43a91e8.png)

### Vacuum Model

Xiaomi Mijia STYTJ02YM

### Valetudo Version

Currently master (`bef609efbe772632b270c67efb660ef2b8f06c0f`), but the same error appeared on the latest release (`2021.01.1`) aswell
### Firmware Version

I don't know but hopefully unrelated? Otherwise I can try to find out.
### User-Agent

Chrome 88.0.4324.150

## Expected behavior

I would expect the edit zones button to appear and be able to edit zones.

## Additional context

Unrelated to the actual problem: I could neither copy the error texts nor the device information, I hope they are accurate.

**Comment by Kaan88** [comment]
#675
