### ISSUE TITLE
Feature Request: Support for Roborock S6 MaxV

### ISSUE THREAD

**Issue by RubenKelevra** [Hypfer/Valetudo#684]
Currently only the S6 is supported, is there a chance to get support for my S6 MaxV? 🤔

**Comment by Hypfer** [comment]
![image](https://user-images.githubusercontent.com/974410/107409667-afe91600-6b0c-11eb-9e5d-635e28ce2ec3.png)

You do realize that this is not a bug and therefore invalid, right? Please stop.

Anyways
https://github.com/Hypfer/Valetudo/blob/1509be361552f76148c4f38b3d7ec1da3c400735/lib/robots/roborock/RoborockS6MaxVValetudoRobot.js#L6-L13
