### ISSUE TITLE
MQTT & HA: not all items populated

### ISSUE THREAD

**Issue by Kugelfang666** [Hypfer/Valetudo#693]
## Describe the bug

Valetudo 2021_2 installed and connected to MQTT Server on HA, I can see in MQTT Topics for the Consumables, however they don't become populated in Home Assistant (see screenshot)

### Vacuum Model

Gen 1 
### Valetudo Version

2021_0
<img width="969" alt="Screenshot" src="https://user-images.githubusercontent.com/3289654/108203067-4a0b1880-7122-11eb-8071-4989acc146d2.png">
2

**Comment by Hypfer** [comment]
Yep that happens. It's not a bug in Valetudo though but rather in the home assistant autodiscovery logic.
My hypothesis is, that it doesn't handle newly appearing entities with the same device info properly.

Unfortunately, there's nothing I can do about that

Deleting the device and restarting valetudo + ha a few times is the only workaround available

**Comment by Kugelfang666** [comment]
ok i See rebooting the robot a few Times indeed fixed it for me

**Comment by Hypfer** [comment]
See also: #686
