### ISSUE TITLE
Valetudo tries to connect to pool.ntp.org despite other NTP server was specified for building

### ISSUE THREAD

**Issue by tlpbu** [Hypfer/Valetudo#716]
## Describe the bug

Valetudo logs show attempts to connect to pool.ntp.org although this should not even happen because another NTP server was specified for building currently flashed Valetudo image
```./builder_vacuum.sh  --ntpserver=xyz ..```

Vaccum is restricted to LAN only therefor requests fail with:
```
[2021-02-27T07:06:16.245Z] [WARN] Error during time sync: Error: queryA ECONNREFUSED pool.ntp.org
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:203:19) {
  errno: undefined,
  code: 'ECONNREFUSED',
  syscall: 'queryA',
  hostname: 'pool.ntp.org'
}
```

### Vacuum Model

Xiaomi Roborock Gen 1
### Valetudo Version

2021.2.0
## Expected behavior

Use only NTPserver specified in build command.

**Comment by Hypfer** [comment]
I have absolutely no idea what that build flag does.

The NTP server is configured in the Valetudo configuration file. To find out where that is, check out the log which is visible in the info section of the settings.
