### ISSUE TITLE
NTP server set in config, but i see drops on firewall for other NTP hosts

### ISSUE THREAD

**Issue by darootler** [Hypfer/Valetudo#745]
## Describe the bug

I am using the following NTP configuration in valetudo_config.json:

```
  "ntpClient": {
    "enabled": true,
    "server": "myinternal.ntp.local",
    "port": 123,
    "interval": 28800000,
    "timeout": 10000
  },
```

The logs are stating that everything is okay:

`[2021-03-08T07:27:48.003Z] [INFO] Successfully set the robot time via NTP to 2021-03-08T07:27:48.890Z`

But i see drops on my firewall for public NTP servers:
![image](https://user-images.githubusercontent.com/11849583/110288711-baea7580-7fe8-11eb-8175-c9b066fc9b0b.png)

## To Reproduce

1.) Configure the NTP server using "valetudo_config.json"
2.) Restart valetudo
3.) Watch the firewall logs for connections on UDP port 123

### Screenshots
See above

### Vacuum Model
Beijing Roborock Technology Co., Ltd. Xiaomi Mi SDJQR02RR (RoborockV1ValetudoRobot)

### Valetudo Version
2021.02.0

## Expected behavior
The configured NTP server should be used

**Comment by darootler** [comment]
Setting the NTP in /opt/rockrobo/watchdog/ntpserver.conf "fixes" the problem. Hmm, is this working as expected? I wonder why there are two places to configure the NTP server.

Regards
Richard

**Comment by Hypfer** [comment]
There are other things inside the firmware which may do NTP stuff. This isn't a bug in Valetudo

Please don't open Bugs for things that aren't.

**Comment by darootler** [comment]
If i know that this isn't a bug i wouldn't open an issue, a simple clarification would be enough.

Regards
Richard

**Comment by Hypfer** [comment]
![image](https://user-images.githubusercontent.com/974410/110294650-6a771600-7ff0-11eb-9c98-1d3aa3351644.png)

**Comment by darootler** [comment]
I am a user of (for sure) a wonderful software. I configured a NTP server and i see that this server isn't used by the device. Is there anything in documentation that states that there are other "NTP things" done by the firmware? Is that a thing a "user" should know?

Sorry, but you can't assume everyone knows exactly what your software or the firmware is doing.

Regards
Richard

**Comment by Hypfer** [comment]
Sure, however I can expect that users stick to the rules layed out and use e.g. the telegram group or discussions to clarify that what they're experiencing is actually a bug before opening a bug report

**Comment by darootler** [comment]
Thank you for clarification, and by the way: Great job with valetudo!

In case someone is reading this:

I had to change the NTP server in "/opt/rockrobo/watchdog/ntpserver.conf" to have the "whole" device talk to my internal NTP server.

Regards
Richard
