### ISSUE TITLE
Viomi Zone Cleaning doesn't show path/time/area or robot moving

### ISSUE THREAD

**Issue by markthehipster** [Hypfer/Valetudo#747]
## Describe the bug

When Zone Cleaning is set, the vacuum will show up as being on the charger, no path is recorded, and only zones are marked in a static form. The main page will also say paused and not show Area or Time of cleaning. 

## To Reproduce

1. Go to 'Home'
2. Click on 'Zones'
3. Select a specified Zone and start cleaning that area

### Screenshots
![IMG_026159638549-1](https://user-images.githubusercontent.com/46720448/110844066-472ac000-82a9-11eb-924d-b50c9b7b40b5.jpeg)
![IMG_EDEC157862E8-1](https://user-images.githubusercontent.com/46720448/110844240-79d4b880-82a9-11eb-9317-c24fa48d4440.jpeg)
^ the values at area and time are from a separate start/stop.

### Vacuum Model
Viomi.v7 

### Valetudo Version
 Latest build from master as of commit d996beb4291146e71c90971dc3654926ed72f698 
However I've also seen this since Zoned cleaning is built in.
## Expected behavior
Expected to see the vacuum's path during zoned cleaning, and also expected to see that it's 'cleaning' + area and time since it started.

**Comment by Kaan88** [comment]
In one of the builds before the capabilities rewrite, map updated correctly when you started zone cleaning from the map page, but it was still broken when it was done via preset zones. 

I can't remember it exactly but I think it was a build from this branch: https://github.com/fhorinek/Valetudo/commits/master

**Comment by Depau** [comment]
For both this and #731 which is very likely related: I'll look it into it this weekend or next week.

The cleaning commands are pretty much just wrong, the only thing that works correctly is all-house cleaning. You haven't noticed but zone mopping won't mop, it just vacuums.

**Comment by exotsk** [comment]
![image](https://user-images.githubusercontent.com/54969124/112090305-e3b46280-8bc5-11eb-9ec0-0d15d627e029.png)
All works! Thank to Jan Loewe.

**Comment by Kaan88** [comment]
@exotsk it works for segment cleaning but not for zone, so the issue still persists.

**Comment by exotsk** [comment]
![image](https://user-images.githubusercontent.com/54969124/112751802-0bf2f580-8ffa-11eb-80e3-3a21c66fc87b.png)
 Fixed now. Thanks!

**Comment by Depau** [comment]
Yeah this should all work now. If you notice related issues, please tag me so I see it.

**Comment by forast3r** [comment]
@Depau I installed a recent commit (two days ago) and found that area is reporting now is showing right square meters, but time seems to be reporting only hours:minutes, for example if the viomi has been vacuuming for 7 minutes 10 seconds it shows 00:00:07
The same data in a rockrobo unit shows 00:07:10

**Comment by markthehipster** [comment]
@forast3r Yeah, I can confirm the same, however it's not tied to this bugreport, since I saw that happening for ages now.
Could you please open a separate bugreport?
