### ISSUE TITLE
Map orientation 

### ISSUE THREAD

**Issue by panoslouk** [Hypfer/Valetudo#751]
Sometimes maps does not have the right orientation. Is this a bug?
Usually the map has horizontal or vertical orientation but sometimes when i start cleaning it starts creating a new map over the old with 25-30 degree shifting

### Screenshots

![image](https://user-images.githubusercontent.com/50794979/111128498-a294d080-857d-11eb-9d71-58f9730efb01.png)

### Vacuum Model
Viomi v8

### Valetudo Version
2021.02.0

**Comment by Hypfer** [comment]
> Is this a bug?

![image](https://user-images.githubusercontent.com/974410/111135244-b68c0280-857c-11eb-9561-bcd2594d227d.png)

...


Anyways, not a bug in valetudo.
