### ISSUE TITLE
Fix Viomi "Unknown water grade" not work

### ISSUE THREAD

**Issue by exotsk** [Hypfer/Valetudo#789]
Changing "water grade" option make a change on "power mode". WG option still medium after that.

## To Reproduce

1. Go to 'Main menu'
2. Click on 'Water Grade'
3. Change to to any

### Screenshots
![image](https://user-images.githubusercontent.com/54969124/112741215-c6a8d680-8fad-11eb-9b13-c64bf6b818a4.png)

### Vacuum Model
Viomi STY**T**J but in Valetudo in info as Viomi V7 

### Valetudo Version
2021.03.0 Dev 28/03/2021

## Expected behavior
Changing water grade and working mop mode, but mop don`t work at all with istalled water tank.

**Comment by Hypfer** [comment]
What about https://github.com/Hypfer/Valetudo/pull/784?

**Comment by exotsk** [comment]
i check it after fix was added. 
![image](https://user-images.githubusercontent.com/54969124/112752190-f54d9e00-8ffb-11eb-9c0a-d66d22558648.png)
at last check with mop container, all the same. Changing power, no mop funcion.

**Comment by Depau** [comment]
Fixed in #791
