### ISSUE TITLE
viomi: Incorrect cleaning time

### ISSUE THREAD

**Issue by Depau** [Hypfer/Valetudo#794]
> @Depau I installed a recent commit (two days ago) and found that area is reporting now is showing right square meters, but time seems to be reporting only hours:minutes, for example if the viomi has been vacuuming for 7 minutes 10 seconds it shows 00:00:07
The same data in a rockrobo unit shows 00:07:10

_Originally posted by @forast3r in https://github.com/Hypfer/Valetudo/issues/747#issuecomment-808924362_

---

Will check.

**Comment by exotsk** [comment]
![image](https://user-images.githubusercontent.com/54969124/112775548-70986980-9067-11eb-967f-c06fcdb89cd3.png)
the same

**Comment by exotsk** [comment]
![image](https://user-images.githubusercontent.com/54969124/114274742-1b3a6000-9a4a-11eb-814b-9f425ff866a8.png)
Consumables counting wrong.

**Comment by Hypfer** [comment]
Possibly related to #754 ?

**Comment by Depau** [comment]
> ![image](https://user-images.githubusercontent.com/54969124/114274742-1b3a6000-9a4a-11eb-814b-9f425ff866a8.png)
> Consumables counting wrong.

What's the problem here?

**Comment by exotsk** [comment]
What's the problem here?
Wrong time(second equal minute) is a good for consumables  =)
