### ISSUE TITLE
Add Cleaning history page.

### ISSUE THREAD

**Issue by wbaars** [Hypfer/Valetudo#81]
It would be nice to have a cleaning history page added to Valetudo.
Maybe show last weeks or last 7 cleanings.

**Comment by stefanct** [comment]
What information would/should that include? Some ideas:

- Start timestamp
- End timestamp
- Duration
- Area cleaned
- Snapshot of the map
- Energy used

**Comment by Bennedetto** [comment]
I just implemented most of the suggested functionality and created a Pull Request for the changes.
To keep the implementation efford as low as possible, I only implemented those items that are already provided by xiaomi. Thus the start-time, duration, area and possible errors are listed. 

The remaining ideas would require additional information that are currently not available.

**Comment by wbaars** [comment]
Bennedetto, your implementation looks great!
Can't wait to test it out!

**Comment by Bennedetto** [comment]
No need to wait for testing it. Just download the release 0.0.10b on https://github.com/Bennedetto/Valetudo/releases/tag/0.0.10b.
This contains all my changes that are currently published as PRs.
