### ISSUE TITLE
Valetudo won't save settings

### ISSUE THREAD

**Issue by michel72** [Hypfer/Valetudo#83]
Rooted a Roborock S50, firmware v3.3.9_001710 (downgraded to 001702)

Installed valetudo, webui works.

Changed the wifi settings to my network, connection lost.

Then reset the wifi again, tried saving the sound settings, but also that fails. Seems to be an issue saving settings. Is does read the firmware version, token, etc.

Anyone?

**Comment by michel72** [comment]
Right after settings the wifi, it does show up in my wifi network briefly, I can ping it, but no webuit and not ssh possible.

**Comment by michel72** [comment]
Looks to be a more generic problem.

When setting the wifi using the descibed method on the DC website:

**Comment by michel72** [comment]
Someone advised me to use https://github.com/LazyT/rrcc/ and that did work setting wifi :)

**Comment by Hypfer** [comment]
Interesting. Both tools call the same miio command. I wonder what might be different 🤔

**Comment by michel72** [comment]
I've tied several times using mirobo, but it failed.

**Comment by Hypfer** [comment]
Any special characters/spaces/etc. in SSID or password?

**Comment by michel72** [comment]
yes, but it's the same ssid and pass I used with rrcc.

It's almost the same as:

ssid: kkmm
pass: KkMm.17.Nlt.15-mklsvdfers.Hnssfr

**Comment by michel72** [comment]
I also tried ssid: tester and pass: 1234567890 to exclude the password character issue.

**Comment by Hypfer** [comment]
And tester:1234567890 did not work with mirobo nor valetudo?

**Comment by michel72** [comment]
No. I did not test this specific ssid with rrcc, since rrcc worked right away with my normal ssid.

**Comment by michel72** [comment]
The only difference I can think of is that I used a different ssh key, since rrc required a private key wothoud password do I added one specifically for rrcc, but that should not be the issue either since I was able to connect via ssh when using the AP mode with roborock ssid.

**Comment by Hypfer** [comment]
https://github.com/Hypfer/Valetudo/blob/master/miio/Vacuum.js#L300
https://github.com/LazyT/rrcc/blob/8b4800a999c248a393932a2161ae2c926ba3a91d/mainwindow.h#L111
https://github.com/rytilahti/python-miio/blob/f08b6153f4b68b4c1fea5cccaf3f6c94cdb92395/miio/device.py#L350

Okay so the only difference here is that rrcc uses null instead of 0?
