### ISSUE TITLE
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['availability_mode']

### ISSUE THREAD

**Issue by makuser** [Hypfer/Valetudo#858]
## Describe the bug
https://github.com/Hypfer/Valetudo/blob/7d28ac85cea7a4081f49fe199f19adf678778f78/lib/mqtt/homeassistant/components/HassComponent.js#L189
availability_mode is a relatively new attribute, unfortunately since it is not expected by hass.
https://github.com/home-assistant/core/commit/d60fc0de3807cc680016713670767d4efeba8d38#diff-0d67e0c95bc8b8efc20c8d5491b8ed7a6634598a9fcdc954f96a1077a2c77e7aR81
Any version prior to 2021.4.6 will probably throw an exception and not work with it.

## To Reproduce
1. Install latest Home Assistant on latest packaged python on Raspbian (Home Assistant 2021.1.5), or hey actually any version before 2021.4.6, which was released JUST SEVEN DAYS AGO... https://www.home-assistant.io/blog/2021/04/07/release-20214/#release-202146---april-19
2. Update Valetudo to 2021.04.0
3. Do the workaround to rediscover mqtt devices as described on the release page
4. No longer be able to use valetudo with hass...

### Vacuum Model
Roborock S5 Max

### Valetudo Version
2021.04.0

## Additional context
Since all it does is to set the "availability_mode" to 'latest', you can just scratch that, since it's the default anyway...

**Comment by Hypfer** [comment]
Interestingly, I didn't experience any issues while testing against my local setup that is Home Assistant 2021.4.0

Either I've missed something or they've added a more tolerant error handling in a HA version newer than 2021.1.5 but older than 2021.4.6

**Comment by Depau** [comment]
Oh okay I see then. Disregard my comment in the PR then. I'd suggest to leave it commented in the code though, and explain why it is commented. So that someone who wants to change it to a different value gets the opportunity to think twice and make an informed choice.
