### ISSUE TITLE
Token: Unable to select token to copy it.

### ISSUE THREAD

**Issue by cryptomilk** [Hypfer/Valetudo#89]
It isn't possible to "select" the token with the mouse to copy it. You nave to go to the source code of the page to be able to do that.

**Comment by Hypfer** [comment]
![image](https://user-images.githubusercontent.com/974410/52538411-8a38a300-2d72-11e9-97e1-241f078090d4.png)


Which browser are you using?

**Comment by cryptomilk** [comment]
Firefox

**Comment by Hypfer** [comment]
Indeed.
Neither Firefox nor Edge allow token selection. Chrome works, though
