### ISSUE TITLE
Valetudo sends 500-700 messages per minute to MQTT broker

### ISSUE THREAD

**Issue by definitio** [Hypfer/Valetudo#896]
## Describe the bug

Even when a vacuum doesn't do anything (docked), Valetudo sends up to 700 messages to MQTT broker. That's several times more than all my other devices. It's a useless waste of CPU cycles. Also subscribing to everything via CLI clients for debugging is impossible now without filtering out topics related to Valetudo. This is not a problem, but really annoying.

### Vacuum Model

Gen 1

### Valetudo Version

2021.04.0

## Expected behavior

Data should be sent on change or at least once per minute.

**Comment by Hypfer** [comment]
If you would be me and receive this report, what would you do next?

What should I make out of this? Tell you "works on my machine" and close it?

> Data should be sent on change or at least once per minute.

What data?

**Comment by definitio** [comment]
Sorry, this is not a real issue.
