### ISSUE TITLE
No add Button in the Timer Menu

### ISSUE THREAD

**Issue by h4ckerle** [Hypfer/Valetudo#899]
## Describe the bug
There is no add-button shown in the Timers Menu. Works in neither Day, nor Night Theme.

## To Reproduce

1. Goto Settings
2. Click on Timers
3. See no add Button
### Screenshots

![image](https://user-images.githubusercontent.com/76652420/117288768-24152a80-ae6c-11eb-9c70-83502beac717.png)
![image](https://user-images.githubusercontent.com/76652420/117288845-38f1be00-ae6c-11eb-98fc-ac88ecaad1fa.png)

### Vacuum Model

Roborock S5
### Valetudo Version

2021.04.0/Commit 7d28ac85cea7a4081f49fe199f19adf678778f78
## Expected behavior

Add button available.

**Comment by h4ckerle** [comment]
HM? Why is it invalid?

**Comment by Depau** [comment]
https://github.com/Hypfer/Valetudo/discussions/824

**Comment by h4ckerle** [comment]
Oh. So that's intended behaviour. Thank you for sharing. Just searched the Issues but not the discussions. OK, then ill have a look at the home automation services out there.
