### ISSUE TITLE
Wrong folder regex pattern in rrlog

### ISSUE THREAD

**Issue by Quantum1337** [Hypfer/Valetudo#9]
Hey,

i found a bug that referrers to line 421 in WebServer.js:
`if(/^([0-9]{6})\.([0-9]{17})_R([0-9]{4})S([0-9]{8})_([0-9]{10})REL$/.test(filename)) {
..
`
The folder structure on my Vacuum Cleaner V1 with latest firmware looks like:
`000068.20180730053838787_1387101066286_2018062200REL`

In my case i changed that line to
`if(/^([0-9]{6})\.([0-9]{17})_([0-9]{13})_([0-9]{10})REL$/.test(filename)) { ...`

This works for me, but that is not a generic solution... Please have a look on it. Thank you

**Comment by Hypfer** [comment]
Fixed
