### ISSUE TITLE
Refactor index.html

### ISSUE THREAD

**Issue by Hypfer** [Hypfer/Valetudo#90]
Seriously. Just do it.
It hurts to see this abomination of a "WebApp".

**Comment by legomind** [comment]
Good grief. If it hurts you that bad to use free software, then don't use it.
Problem solved.

**Comment by legomind** [comment]
Lol you had me ready to comment about complaining about free software before I realized you were the repo owner.
Haha.

**Comment by Hypfer** [comment]
I'm thinking about dropping Onsen UI.
It was easy to use the example and just change some elements, however splitting it up doesn't feel quite right.
Also, it's not really responsive but rather a mobile UI which gets very large on desktop systems and renders with a different CSS if you're on android.

This decision isn't final, though.

**Comment by MeisterTR** [comment]
whats with the vue exaple of wolfspiritM [https://codesandbox.io/s/52y028o3qn](url) or maybe with vuetify (modern Material) i started a few weeks ago with vue. but i think im not good enoght to realize this... if i have some free time i will try..

**Comment by Hypfer** [comment]
There's not just the example but rather a (seemingly nearly complete) branch in his fork:
https://github.com/WolfspiritM/Valetudo/tree/vue-integration

**Comment by Poeschl** [comment]
Are they plans to continue on your fork @WolfspiritM ? Otherwise I would fork and take on the missing points.
