### ISSUE TITLE
Home Assistant Integration wont work

### ISSUE THREAD

**Issue by b-reich** [Hypfer/Valetudo#909]
## Home Assistant wont work
Home Assistant wont work until Homie auto discovery is enabled. 

## To Reproduce
1. Disable Homie auto discovery
2. HA stop working
3. Enable Homie again
4. HA start working again

### Vacuum Model
Roborock S5

### Valetudo Version
 2021.4.0

## Expected behavior
HA should work without Homie auto discovery enabled

**Comment by Depau** [comment]
If you had searched you know this was already solved and will be fixed in the next release.

Keep homie enabled until you update.
