### ISSUE TITLE
Manual Control is gone

### ISSUE THREAD

**Issue by valknut89** [Hypfer/Valetudo#977]
Since the "new" release names Manuals control is gone. I use the actual prebuild firmware, which is linked in instructions

**Comment by rmickael62** [comment]
Did you find the manual control of valetudo? because I can't find it either

**Comment by valknut89** [comment]
No, but I read in FAQ that the function maybe will come back in one of the next releases.
Didn't Check the july release yet.

10.07.2021 11:55:27 rmickael62 ***@***.***>:
