### ISSUE TITLE
More/Better Swagger Examples

### ISSUE THREAD

**Issue by Hypfer** [Hypfer/Valetudo#987]
The swagger docs could use some more examples for common things to do such as ordered Segment Cleaning as well as additional proof-reading.

The actual spec is built from many small json files spread all around the project in `doc` folders via the `build_openapi_schema` npm script to keep them readable.
e.g.
https://github.com/Hypfer/Valetudo/blob/master/backend/lib/webserver/capabilityRouters/doc/MapSegmentationCapabilityRouter.openapi.json

**Comment by kcindric** [comment]
Could you write a list of endpoints which could use additional examples?

**Comment by Hypfer** [comment]
Actually basically all of them. Only the TimerRouter has some examples

The rest is just infered from the schema by the swagger ui

**Comment by kcindric** [comment]
Ok, I'll try to commit to this. What a better way to learn a project than go through each and every endpoint :)
