### ISSUE TITLE
"Zones" not shown anymore

### ISSUE THREAD

**Issue by tetzlav** [Hypfer/Valetudo#988]
## Describe the bug
After update from 2021.04.0 to 2021.06.0 "Zones" not shown in "Home" page anymore.

## To Reproduce
If i copy back the 2021.04.0 binary and restart the "Zones" are shown again.

### Screenshots
2021.04.0
![screenshot_2021-07-14](https://user-images.githubusercontent.com/1469508/125584784-6cf8f230-d03a-4b17-ad2b-456af78eb476.png)
![screenshot_2021-07-14 (2)](https://user-images.githubusercontent.com/1469508/125586504-517f4b31-6409-4c58-bb1e-85040cce57eb.png)
2021.06.0
![screenshot_2021-07-14 (1)](https://user-images.githubusercontent.com/1469508/125584844-51d5f979-7a76-457b-96b7-2c4b7c347107.png)

### Vacuum [Model](url)
Roborock S5 Max### Valetudo Version

### Config files
[valetudo_config.json.txt](https://github.com/Hypfer/Valetudo/files/6814490/valetudo_config.json.txt)

**Comment by tetzlav** [comment]
any more info why closed?

**Comment by Hypfer** [comment]
https://github.com/Hypfer/Valetudo/discussions/968#discussioncomment-919167

https://github.com/Hypfer/Valetudo/issues/952
